import {
  Trophy, Coins, Puzzle, Zap, Leaf, Heart, Target, BookOpen, GraduationCap, ShoppingCart, Book, Droplets, ClipboardList, Gift, Paintbrush, PenSquare, PartyPopper, HelpCircle, Recycle, Sun, Cloud, TreePine, Image, Clipboard
} from "lucide-react";

import buildIds from "../buildGameIds";

export const sustainabilityGameIdsKids = buildIds("sustainability", "kids")

export const getSustainabilityKidsGames = (gameCompletionStatus)=> {
    const sustainabilityGamesKids = [
        {
          id: "sustainability-kids-1",
          title: "Eco Sort Story",
          description: "You see trash on the ground. Do you pick it up or leave it?",
          icon: <Leaf className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-1"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/eco-sort-story",
          index: 0,
        },
        {
          id: "sustainability-kids-2",
          title: "Quiz on Recycling",
          description: "What goes in recycling? (a) Plastic bottle, (b) Banana peel, (c) Broken toy",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-2"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-recycling",
          index: 1,
        },
        {
          id: "sustainability-kids-3",
          title: "Reflex Recycle",
          description: "Tap quickly for 'Recycle' items, avoid 'Trash' items",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-3"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-recycle",
          index: 2,
        },
        {
          id: "sustainability-kids-4",
          title: "Puzzle: Sort the Waste",
          description: "Match 'Plastic Bottle → Recycle, Apple Core → Compost, Broken Toy → Trash'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-4"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-sort-waste",
          index: 3,
        },
        {
          id: "sustainability-kids-5",
          title: "Litter Story",
          description: "You finish a snack. Do you throw wrapper on ground or find a bin?",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-5"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/litter-story",
          index: 4,
        },
        {
          id: "sustainability-kids-6",
          title: "Poster: Reduce, Reuse, Recycle",
          description: "Create/select poster: '3 Rs Save Our Planet'",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-6"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-3rs",
          index: 5,
        },
        {
          id: "sustainability-kids-7",
          title: "Journal of Recycling",
          description: "Write: 'One thing I recycled today was ___'",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-7"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-recycling",
          index: 6,
        },
        {
          id: "sustainability-kids-8",
          title: "Plastic Bag Story",
          description: "Shop gives plastic bag. Do you take it or use your own bag?",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-8"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/plastic-bag-story",
          index: 7,
        },
        {
          id: "sustainability-kids-9",
          title: "Reflex Waste Choice",
          description: "Tap for 'Reusable,' avoid 'Single-use'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-9"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-waste-choice",
          index: 8,
        },
        {
          id: "sustainability-kids-10",
          title: "Badge: Eco Helper Kid",
          description: "Sort waste correctly 5 times to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-10"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-eco-helper-kid",
          index: 9,
        },
        {
          id: "sustainability-kids-11",
          title: "Lights Off Story",
          description: "You leave room. Do you turn off lights or leave them on?",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-11"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/lights-off-story",
          index: 10,
        },
        {
          id: "sustainability-kids-12",
          title: "Quiz on Saving Energy",
          description: "What saves energy? (a) Turn off TV when not watching, (b) Leave all lights on, (c) Keep AC on all day",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-12"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-saving-energy",
          index: 11,
        },
        {
          id: "sustainability-kids-13",
          title: "Reflex Energy Saver",
          description: "Tap for 'Turn Off,' avoid 'Leave On'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-13"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-energy-saver",
          index: 12,
        },
        {
          id: "sustainability-kids-14",
          title: "Puzzle: Energy Sources",
          description: "Match 'Sun → Solar Energy, Wind → Wind Energy, Coal → Dirty Energy'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-14"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-energy-sources",
          index: 13,
        },
        {
          id: "sustainability-kids-15",
          title: "Water Tap Story",
          description: "You see tap dripping. Do you tell an adult or ignore it?",
          icon: <Droplets className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-15"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/water-tap-story",
          index: 14,
        },
        {
          id: "sustainability-kids-16",
          title: "Poster: Save Water",
          description: "Create/select poster: 'Every Drop Counts'",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-16"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-save-water",
          index: 15,
        },
        {
          id: "sustainability-kids-17",
          title: "Journal of Green Habits",
          description: "Write: 'One green habit I practice is ___'",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-17"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-green-habits",
          index: 16,
        },
        {
          id: "sustainability-kids-18",
          title: "Tree Planting Story",
          description: "School plants a tree. Do you help water it or ignore it?",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-18"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/tree-planting-story",
          index: 17,
        },
        {
          id: "sustainability-kids-19",
          title: "Reflex Nature Care",
          description: "Tap for 'Protect Nature,' avoid 'Harm Nature'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-19"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-nature-care",
          index: 18,
        },
        {
          id: "sustainability-kids-20",
          title: "Badge: Planet Protector Kid",
          description: "Complete 5 eco-friendly actions to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-20"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-planet-protector-kid",
          index: 19,
        },
        {
          id: "sustainability-kids-21",
          title: "Ocean Cleanup Story",
          description: "You see plastic in the ocean. Do you help clean it or walk away?",
          icon: <Droplets className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-21"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/ocean-cleanup-story",
          index: 20,
        },
        {
          id: "sustainability-kids-22",
          title: "Quiz on Wildlife Protection",
          description: "What helps protect animals? (a) Littering, (b) Protecting habitats, (c) Cutting trees",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-22"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-wildlife-protection",
          index: 21,
        },
        {
          id: "sustainability-kids-23",
          title: "Reflex Clean Air",
          description: "Tap for 'Clean Air' actions, avoid 'Pollution' actions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-23"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-clean-air",
          index: 22,
        },
        {
          id: "sustainability-kids-24",
          title: "Puzzle: Green Transportation",
          description: "Match 'Bike → Clean, Car → Pollutes, Walk → Healthy'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-24"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-green-transportation",
          index: 23,
        },
        {
          id: "sustainability-kids-25",
          title: "Badge: Earth Guardian",
          description: "Complete all eco-challenges to become an Earth Guardian",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-25"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-earth-guardian",
          index: 24,
        },
        {
          id: "sustainability-kids-26",
          title: "Water Bottle Story",
          description: "You finish a water bottle. Do you reuse it or throw it away?",
          icon: <Droplets className="w-6 h-6" />, // Using droplets icon for water
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-26"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/water-bottle-story",
          index: 25,
        },
        {
          id: "sustainability-kids-27",
          title: "Quiz on Water Conservation",
          description: "What saves water? (a) Long showers, (b) Turn off tap, (c) Leave water running",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-27"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-water-conservation",
          index: 26,
        },
        {
          id: "sustainability-kids-28",
          title: "Reflex Water Saver",
          description: "Tap for 'Save Water,' avoid 'Waste Water'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-28"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-water-saver",
          index: 27,
        },
        {
          id: "sustainability-kids-29",
          title: "Puzzle: Water Sources",
          description: "Match 'Rain → Water, Ocean → Salty, Tap → Drinkable'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-29"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-water-sources",
          index: 28,
        },
        {
          id: "sustainability-kids-30",
          title: "Rain Story",
          description: "It's raining. Do you collect rainwater or let it drain?",
          icon: <Cloud className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-30"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/rain-story",
          index: 29,
        },
        {
          id: "sustainability-kids-31",
          title: "Poster: Clean Air",
          description: "Create/select poster: 'Breathe Clean Air'",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-31"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-clean-air",
          index: 30,
        },
        {
          id: "sustainability-kids-32",
          title: "Journal of Water Habits",
          description: "Write: 'One way I save water is ___'",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-32"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-water-habits",
          index: 31,
        },
        {
          id: "sustainability-kids-33",
          title: "Plant Story",
          description: "You see a wilting plant. Do you water it or ignore it?",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-33"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/plant-story",
          index: 32,
        },
        {
          id: "sustainability-kids-34",
          title: "Reflex Air Quality",
          description: "Tap for 'Clean Air' actions, avoid 'Pollution' actions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-34"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-air-quality",
          index: 33,
        },
        {
          id: "sustainability-kids-35",
          title: "Badge: Water Warrior Kid",
          description: "Complete 5 water-saving actions to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-35"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-water-warrior-kid",
          index: 34,
        },
        {
          id: "sustainability-kids-36",
          title: "Leftover Food Story",
          description: "You have leftover food. Do you save it or throw it away?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-36"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/leftover-food-story",
          index: 35,
        },
        {
          id: "sustainability-kids-37",
          title: "Quiz on Food Waste",
          description: "What reduces food waste? (a) Throw away half, (b) Eat what you take, (c) Buy extra)",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-37"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-food-waste",
          index: 36,
        },
        {
          id: "sustainability-kids-38",
          title: "Reflex Food Saver",
          description: "Tap for 'Save Food,' avoid 'Waste Food'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-38"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-food-saver",
          index: 37,
        },
        {
          id: "sustainability-kids-39",
          title: "Puzzle: Compost Items",
          description: "Match 'Apple Core → Compost, Plastic → Trash, Paper → Recycle'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-39"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-compost-items",
          index: 38,
        },
        {
          id: "sustainability-kids-40",
          title: "Garden Story",
          description: "You see a community garden. Do you help or walk away?",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-40"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/garden-story",
          index: 39,
        },
        {
          id: "sustainability-kids-41",
          title: "Poster: Reduce Food Waste",
          description: "Create/select poster: 'Eat All You Take'",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-41"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-reduce-food-waste",
          index: 40,
        },
        {
          id: "sustainability-kids-42",
          title: "Journal of Food Habits",
          description: "Write: 'One way I reduce food waste is ___'",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-42"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-food-habits",
          index: 41,
        },
        {
          id: "sustainability-kids-43",
          title: "Compost Story",
          description: "You see food scraps. Do you compost them or trash them?",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-43"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/compost-story",
          index: 42,
        },
        {
          id: "sustainability-kids-44",
          title: "Reflex Compost Helper",
          description: "Tap for 'Compost,' avoid 'Trash'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-44"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-compost-helper",
          index: 43,
        },
        {
          id: "sustainability-kids-45",
          title: "Badge: Food Saver Kid",
          description: "Reduce food waste 5 times to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-45"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-food-saver-kid",
          index: 44,
        },
        {
          id: "sustainability-kids-46",
          title: "Bike Story",
          description: "You need to go nearby. Do you bike or ask for a car ride?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-46"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/bike-story",
          index: 45,
        },
        {
          id: "sustainability-kids-47",
          title: "Quiz on Green Transport",
          description: "What's better for Earth? (a) Walk, (b) Drive alone, (c) Bike",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-47"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-green-transport",
          index: 46,
        },
        {
          id: "sustainability-kids-48",
          title: "Reflex Transport Choice",
          description: "Tap for 'Green Transport,' avoid 'Polluting Transport'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-48"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-transport-choice",
          index: 47,
        },
        {
          id: "sustainability-kids-49",
          title: "Puzzle: Energy Choices",
          description: "Match 'Sun → Solar, Wind → Clean, Coal → Dirty'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-49"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-energy-choices",
          index: 48,
        },
        {
          id: "sustainability-kids-50",
          title: "Unplug Story",
          description: "You finish charging. Do you unplug or leave it plugged?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-50"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/unplug-story",
          index: 49,
        },
        {
          id: "sustainability-kids-51",
          title: "Poster: Save Energy",
          description: "Create/select poster: 'Energy Smart, Earth Smart'",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-51"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-save-energy",
          index: 50,
        },
        {
          id: "sustainability-kids-52",
          title: "Journal of Transport",
          description: "Write: 'One green way I travel is ___'",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-52"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-transport",
          index: 51,
        },
        {
          id: "sustainability-kids-53",
          title: "Bus Story",
          description: "Going to school. Do you take the bus or drive?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-53"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/bus-story",
          index: 52,
        },
        {
          id: "sustainability-kids-54",
          title: "Reflex Energy Wise",
          description: "Tap for 'Save Energy,' avoid 'Waste Energy'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-54"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-energy-wise",
          index: 53,
        },
        {
          id: "sustainability-kids-55",
          title: "Badge: Green Traveler Kid",
          description: "Use green transport 5 times to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-55"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-green-traveler-kid",
          index: 54,
        },
        {
          id: "sustainability-kids-56",
          title: "Animal Story",
          description: "You see an injured bird. Do you help or ignore it?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-56"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/animal-story",
          index: 55,
        },
        {
          id: "sustainability-kids-57",
          title: "Quiz on Wildlife",
          description: "What helps animals? (a) Feed wildlife, (b) Protect habitats, (c) Pick flowers",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-57"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-wildlife",
          index: 56,
        },
        {
          id: "sustainability-kids-58",
          title: "Reflex Animal Care",
          description: "Tap for 'Help Animals,' avoid 'Harm Animals'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-58"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-animal-care",
          index: 57,
        },
        {
          id: "sustainability-kids-59",
          title: "Puzzle: Animal Homes",
          description: "Match 'Bird → Nest, Bee → Hive, Fish → Ocean'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-59"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-animal-homes",
          index: 58,
        },
        {
          id: "sustainability-kids-60",
          title: "Forest Story",
          description: "You see someone cutting trees. Do you tell an adult or ignore?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-60"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/forest-story",
          index: 59,
        },
        {
          id: "sustainability-kids-61",
          title: "Poster: Protect Wildlife",
          description: "Create/select poster: 'Animals Need Our Help'",
          icon: <Paintbrush className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-61"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-protect-wildlife",
          index: 60,
        },
        {
          id: "sustainability-kids-62",
          title: "Journal of Nature Care",
          description: "Write: 'One way I help nature is ___'",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-62"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-nature-care",
          index: 61,
        },
        {
          id: "sustainability-kids-63",
          title: "Bee Story",
          description: "You see a bee. Do you leave it alone or swat it?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-63"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/bee-story",
          index: 62,
        },
        {
          id: "sustainability-kids-64",
          title: "Reflex Habitat Helper",
          description: "Tap for 'Protect Habitat,' avoid 'Destroy Habitat'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-64"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-habitat-helper",
          index: 63,
        },
        {
          id: "sustainability-kids-65",
          title: "Badge: Wildlife Friend Kid",
          description: "Help wildlife 5 times to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-65"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-wildlife-friend-kid",
          index: 64,
        },
        {
          id: "sustainability-kids-66",
          title: "Paper Story",
          description: "You finish using paper. Do you recycle or throw away?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-66"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/paper-story",
          index: 65,
        },
        {
          id: "sustainability-kids-67",
          title: "Quiz on Upcycling",
          description: "What is upcycling? (a) Throw away, (b) Make new from old, (c) Buy new",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-67"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-upcycling",
          index: 66,
        },
        {
          id: "sustainability-kids-68",
          title: "Reflex Upcycle Master",
          description: "Tap for 'Reuse,' avoid 'Waste'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-68"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-upcycle-master",
          index: 67,
        },
        {
          id: "sustainability-kids-69",
          title: "Puzzle: Material Life",
          description: "Match 'Bottle → Reuse, Box → Recycle, Crayon → Upcycle'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-69"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-material-life",
          index: 68,
        },
        {
          id: "sustainability-kids-70",
          title: "Craft Story",
          description: "You have an old box. Do you make art or throw it?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-70"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/craft-story",
          index: 69,
        },
        {
          id: "sustainability-kids-71",
          title: "Poster: Upcycle Ideas",
          description: "Create/select poster: 'Old Things, New Uses'",
          icon: <Paintbrush className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-71"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-upcycle-ideas",
          index: 70,
        },
        {
          id: "sustainability-kids-72",
          title: "Journal of Reuse",
          description: "Write: 'One thing I reused was ___'",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-72"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-reuse",
          index: 71,
        },
        {
          id: "sustainability-kids-73",
          title: "Donation Story",
          description: "You outgrow toys. Do you donate or throw away?",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-73"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/donation-story",
          index: 72,
        },
        {
          id: "sustainability-kids-74",
          title: "Reflex Resource Saver",
          description: "Tap for 'Reuse Resource,' avoid 'Waste Resource'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-74"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-resource-saver",
          index: 73,
        },
        {
          id: "sustainability-kids-75",
          title: "Badge: Upcycle Champion Kid",
          description: "Upcycle 5 items to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-75"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-upcycle-champion-kid",
          index: 74,
        },
        {
          id: "sustainability-kids-76",
          title: "Weather Story",
          description: "It's very hot outside. Do you turn on AC full or use a fan?",
          icon: <Cloud className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-76"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/weather-story",
          index: 75,
        },
        {
          id: "sustainability-kids-77",
          title: "Quiz on Climate Change",
          description: "What causes climate change? (a) Trees, (b) Too much pollution, (c) Rain",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-77"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-climate-change",
          index: 76,
        },
        {
          id: "sustainability-kids-78",
          title: "Reflex Climate Helper",
          description: "Tap for 'Fight Climate Change,' avoid 'Add to Problem'",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-78"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-climate-helper",
          index: 77,
        },
        {
          id: "sustainability-kids-79",
          title: "Puzzle: Climate Solutions",
          description: "Match 'Trees → Cool Air, Cars → Pollution, Bikes → Clean'",
          icon: <Target className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-79"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-climate-solutions",
          index: 78,
        },
        {
          id: "sustainability-kids-80",
          title: "Season Story",
          description: "Seasons feel different. Do you learn why or ignore?",
          icon: <Cloud className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-80"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/season-story",
          index: 79,
        },
        {
          id: "sustainability-kids-81",
          title: "Poster: Climate Action",
          description: "Create/select poster: 'We Can Help the Earth'",
          icon: <Paintbrush className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-81"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-climate-action",
          index: 80,
        },
        {
          id: "sustainability-kids-82",
          title: "Journal of Green Choices",
          description: "Write: 'One green choice I made is ___'",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-82"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-green-choices",
          index: 81,
        },
        {
          id: "sustainability-kids-83",
          title: "Carbon Story",
          description: "You learn about carbon. Do you reduce yours or ignore?",
          icon: <Cloud className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-83"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/carbon-story",
          index: 82,
        },
        {
          id: "sustainability-kids-84",
          title: "Reflex Green Future",
          description: "Tap for 'Green Choice,' avoid 'Harmful Choice'",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-84"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-green-future",
          index: 83,
        },
        {
          id: "sustainability-kids-85",
          title: "Badge: Climate Helper Kid",
          description: "Make 5 climate-friendly choices to earn your badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-85"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-climate-helper-kid",
          index: 84,
        },
        {
          id: "sustainability-kids-86",
          title: "Community Story",
          description: "Your school starts a green club. Do you join or skip?",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-86"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/community-story",
          index: 85,
        },
        {
          id: "sustainability-kids-87",
          title: "Quiz on Sustainable Living",
          description: "What is sustainable living? (a) Waste lots, (b) Use less, save more, (c) Buy everything",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-87"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-sustainable-living",
          index: 86,
        },
        {
          id: "sustainability-kids-88",
          title: "Reflex Sustainable Life",
          description: "Tap for 'Sustainable,' avoid 'Wasteful'",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-88"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-sustainable-life",
          index: 87,
        },
        {
          id: "sustainability-kids-89",
          title: "Puzzle: Daily Habits",
          description: "Match 'Turn Off → Save, Leave On → Waste, Reuse → Smart'",
          icon: <Target className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-89"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-daily-habits",
          index: 88,
        },
        {
          id: "sustainability-kids-90",
          title: "Neighbor Story",
          description: "Neighbor asks for recycling help. Do you help or say no?",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-90"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/neighbor-story",
          index: 89,
        },
        {
          id: "sustainability-kids-91",
          title: "Poster: Community Action",
          description: "Create/select poster: 'Together We Can'",
          icon: <Paintbrush className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-91"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-community-action",
          index: 90,
        },
        {
          id: "sustainability-kids-92",
          title: "Journal of Community Help",
          description: "Write: 'One way I helped my community is ___'",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-92"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-community-help",
          index: 91,
        },
        {
          id: "sustainability-kids-93",
          title: "Event Story",
          description: "School has a cleanup day. Do you join or stay home?",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-93"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/event-story",
          index: 92,
        },
        {
          id: "sustainability-kids-94",
          title: "Reflex Community Care",
          description: "Tap for 'Help Community,' avoid 'Ignore Community'",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-94"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-community-care",
          index: 93,
        },
        {
          id: "sustainability-kids-95",
          title: "Badge: Community Green Kid",
          description: "Help community 5 times to earn your badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-95"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-community-green-kid",
          index: 94,
        },
        {
          id: "sustainability-kids-96",
          title: "Future Story",
          description: "You think about Earth's future. Do you take action or wait?",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-96"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/future-story",
          index: 95,
        },
        {
          id: "sustainability-kids-97",
          title: "Quiz on Earth Care",
          description: "How can kids help Earth? (a) Waste resources, (b) Save resources, (c) Ignore problems",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-97"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-earth-care",
          index: 96,
        },
        {
          id: "sustainability-kids-98",
          title: "Reflex Earth Guardian",
          description: "Tap for 'Protect Earth,' avoid 'Harm Earth'",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-98"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-earth-guardian",
          index: 97,
        },
        {
          id: "sustainability-kids-99",
          title: "Puzzle: Earth Solutions",
          description: "Match 'Recycle → Less Waste, Save Energy → Less Pollution, Plant Trees → More Oxygen'",
          icon: <Target className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-99"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-earth-solutions",
          index: 98,
        },
        {
          id: "sustainability-kids-100",
          title: "Badge: Master Earth Guardian Kid",
          description: "Complete all eco-challenges to become a Master Earth Guardian",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-100"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-master-earth-guardian-kid",
          index: 99,
        },
      ];

    return sustainabilityGamesKids;
}