import {
  Trophy, Coins, Puzzle, Zap, Leaf, Heart, Target, BookOpen, GraduationCap, ShoppingCart, Book, Droplets, ClipboardList, Gift, Paintbrush, PenSquare, PartyPopper, HelpCircle, Recycle, Sun, Cloud, TreePine, Image, Clipboard, Wind, Factory, Car, Bike, Home, DollarSign, BarChart2, Scale, Building, Banknote, LineChart, Briefcase, Megaphone, ClipboardCheck, ThumbsUp, Edit3, Handshake, LogOut, Speech, Bell, Siren, Mail, Link, MapPin, X, Loader2, Lightbulb, Trash2, Globe, Users, FlaskConical
} from "lucide-react";

import buildIds from "../buildGameIds";

export const sustainabilityGameIdsTeen = buildIds("sustainability", "teens")

export const getSustainabilityTeenGames = (gameCompletionStatus)=> {
    const sustainabilityGamesTeen = [
        {
          id: "sustainability-teens-1",
          title: "Climate Action Story",
          description: "You learn about climate change. How do you take action?",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-1"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/climate-action-story",
          index: 0,
        },
        {
          id: "sustainability-teens-2",
          title: "Quiz on Carbon Footprint",
          description: "What is a carbon footprint? (a) Shoe size, (b) Environmental impact, (c) Weather",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-2"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-carbon-footprint",
          index: 1,
        },
        {
          id: "sustainability-teens-3",
          title: "Reflex Eco Choice",
          description: 'Tap quickly for "Sustainable" actions, avoid "Wasteful" actions',
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-3"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-eco-choice",
          index: 2,
        },
        {
          id: "sustainability-teens-4",
          title: "Puzzle: Sustainable Solutions",
          description: "Match environmental problems with sustainable solutions",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-4"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-sustainable-solutions",
          index: 3,
        },
        {
          id: "sustainability-teens-5",
          title: "Renewable Energy Story",
          description: "Your school considers solar panels. What's your role?",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-5"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/renewable-energy-story",
          index: 4,
        },
        {
          id: "sustainability-teens-6",
          title: "Debate: Fossil Fuels vs Renewables",
          description: "Participate in a debate on energy sources",
          icon: <Speech className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-6"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-fossil-fuels-vs-renewables",
          index: 5,
        },
        {
          id: "sustainability-teens-7",
          title: "Journal of Green Living",
          description: "Reflect on your daily environmental impact",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-7"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-green-living",
          index: 6,
        },
        {
          id: "sustainability-teens-8",
          title: "Simulation: Eco-Friendly City",
          description: "Design a sustainable city with green solutions",
          icon: <Building className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-8"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-eco-friendly-city",
          index: 7,
        },
        {
          id: "sustainability-teens-9",
          title: "Reflex Green Habits",
          description: "Quickly identify sustainable daily habits",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-9"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-green-habits",
          index: 8,
        },
        {
          id: "sustainability-teens-10",
          title: "Badge: Climate Activist",
          description: "Earn your Climate Activist badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-10"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-climate-activist",
          index: 9,
        },
        {
          id: "sustainability-teens-11",
          title: "Waste Reduction Story",
          description: "Your school wants to reduce waste. How do you help?",
          icon: <Trash2 className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-11"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/waste-reduction-story",
          index: 10,
        },
        {
          id: "sustainability-teens-12",
          title: "Quiz on Circular Economy",
          description: "Test your knowledge on waste reduction and recycling",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-12"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-circular-economy",
          index: 11,
        },
        {
          id: "sustainability-teens-13",
          title: "Reflex Zero Waste",
          description: "Quickly identify zero-waste alternatives",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-13"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-zero-waste",
          index: 12,
        },
        {
          id: "sustainability-teens-14",
          title: "Puzzle: Waste Hierarchy",
          description: "Arrange waste management strategies in order of priority",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-14"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-waste-hierarchy",
          index: 13,
        },
        {
          id: "sustainability-teens-15",
          title: "Plastic Pollution Story",
          description: "You see plastic pollution in your community. What's your response?",
          icon: <Recycle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-15"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/plastic-pollution-story",
          index: 14,
        },
        {
          id: "sustainability-teens-16",
          title: "Debate: Single-Use vs Reusable",
          description: "Debate the impact of single-use plastics",
          icon: <Speech className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-16"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-single-use-vs-reusable",
          index: 15,
        },
        {
          id: "sustainability-teens-17",
          title: "Journal of Waste Audit",
          description: "Track and reflect on your waste generation",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-17"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-waste-audit",
          index: 16,
        },
        {
          id: "sustainability-teens-18",
          title: "Simulation: Recycling Program",
          description: "Design and implement a school recycling program",
          icon: <ClipboardCheck className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-18"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-recycling-program",
          index: 17,
        },
        {
          id: "sustainability-teens-19",
          title: "Reflex Compost Master",
          description: "Quickly identify compostable vs non-compostable items",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-19"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-compost-master",
          index: 18,
        },
        {
          id: "sustainability-teens-20",
          title: "Badge: Zero Waste Champion",
          description: "Earn your Zero Waste Champion badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-20"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-zero-waste-champion",
          index: 19,
        },
        {
          id: "sustainability-teens-21",
          title: "Biodiversity Conservation Story",
          description: "Your community plans to build on a forest. What's your stance?",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-21"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/biodiversity-conservation-story",
          index: 20,
        },
        {
          id: "sustainability-teens-22",
          title: "Quiz on Sustainable Agriculture",
          description: "Test your knowledge on eco-friendly farming practices",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-22"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-sustainable-agriculture",
          index: 21,
        },
        {
          id: "sustainability-teens-23",
          title: "Reflex Ocean Protector",
          description: "Quickly identify actions that protect marine life",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-23"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-ocean-protector",
          index: 22,
        },
        {
          id: "sustainability-teens-24",
          title: "Simulation: Green Community Project",
          description: "Plan and execute a community sustainability initiative",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-24"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-green-community-project",
          index: 23,
        },
        {
          id: "sustainability-teens-25",
          title: "Badge: Sustainability Leader",
          description: "Master all sustainability challenges to become a leader",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-25"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-sustainability-leader",
          index: 24,
        },
        {
          id: "sustainability-teens-26",
          title: "Fast Fashion Story",
          description: "Your friend buys new clothes weekly. What's your advice?",
          icon: <ShoppingCart className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-26"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/fast-fashion-story",
          index: 25,
        },
        {
          id: "sustainability-teens-27",
          title: "Quiz on Circular Economy",
          description: "Test your knowledge on reducing, reusing, and recycling",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-27"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-circular-economy-2",
          index: 26,
        },
        {
          id: "sustainability-teens-28",
          title: "Reflex Conscious Consumer",
          description: "Quickly identify sustainable shopping choices",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-28"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-conscious-consumer",
          index: 27,
        },
        {
          id: "sustainability-teens-29",
          title: "Puzzle: Product Lifecycle",
          description: "Match products with their most sustainable disposal method",
          icon: <Puzzle className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-29"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-product-lifecycle",
          index: 28,
        },
        {
          id: "sustainability-teens-30",
          title: "Minimalism Story",
          description: "You want to declutter. How do you do it sustainably?",
          icon: <Home className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-30"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/minimalism-story",
          index: 29,
        },
        {
          id: "sustainability-teens-31",
          title: "Debate: Quality vs Quantity",
          description: "Debate the impact of buying less but better quality",
          icon: <Speech className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-31"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-quality-vs-quantity",
          index: 30,
        },
        {
          id: "sustainability-teens-32",
          title: "Journal of Consumption",
          description: "Reflect on your consumption habits and their impact",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-32"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-consumption",
          index: 31,
        },
        {
          id: "sustainability-teens-33",
          title: "Simulation: Sustainable Shopping",
          description: "Plan a sustainable shopping trip with minimal waste",
          icon: <ClipboardCheck className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-33"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-sustainable-shopping",
          index: 32,
        },
        {
          id: "sustainability-teens-34",
          title: "Reflex Ethical Buyer",
          description: "Quickly identify ethical and sustainable brands",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-34"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-ethical-buyer",
          index: 33,
        },
        {
          id: "sustainability-teens-35",
          title: "Badge: Conscious Consumer",
          description: "Earn your Conscious Consumer badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-35"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-conscious-consumer",
          index: 34,
        },
        {
          id: "sustainability-teens-36",
          title: "Solar Panel Story",
          description: "Your family considers solar panels. What's your research?",
          icon: <Sun className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-36"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/solar-panel-story",
          index: 35,
        },
        {
          id: "sustainability-teens-37",
          title: "Quiz on Energy Transition",
          description: "Test your knowledge on renewable energy technologies",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-37"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-energy-transition",
          index: 36,
        },
        {
          id: "sustainability-teens-38",
          title: "Reflex Energy Innovator",
          description: "Quickly identify innovative energy solutions",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-38"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-energy-innovator",
          index: 37,
        },
        {
          id: "sustainability-teens-39",
          title: "Puzzle: Energy Systems",
          description: "Match energy sources with their environmental impacts",
          icon: <Puzzle className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-39"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-energy-systems",
          index: 38,
        },
        {
          id: "sustainability-teens-40",
          title: "Wind Farm Story",
          description: "A wind farm is proposed nearby. What's your stance?",
          icon: <Wind className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-40"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/wind-farm-story",
          index: 39,
        },
        {
          id: "sustainability-teens-41",
          title: "Debate: Nuclear vs Renewables",
          description: "Debate different energy solutions for the future",
          icon: <Speech className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-41"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-nuclear-vs-renewables",
          index: 40,
        },
        {
          id: "sustainability-teens-42",
          title: "Journal of Energy Use",
          description: "Track and analyze your personal energy consumption",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-42"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-energy-use",
          index: 41,
        },
        {
          id: "sustainability-teens-43",
          title: "Simulation: Energy Audit",
          description: "Conduct an energy audit for your home or school",
          icon: <Building className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-43"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-energy-audit",
          index: 42,
        },
        {
          id: "sustainability-teens-44",
          title: "Reflex Energy Tech",
          description: "Quickly identify emerging green technologies",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-44"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-energy-tech",
          index: 43,
        },
        {
          id: "sustainability-teens-45",
          title: "Badge: Energy Innovator",
          description: "Earn your Energy Innovator badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-45"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-energy-innovator",
          index: 44,
        },
        {
          id: "sustainability-teens-46",
          title: "Water Crisis Story",
          description: "Your area faces water shortages. How do you respond?",
          icon: <Droplets className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-46"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/water-crisis-story",
          index: 45,
        },
        {
          id: "sustainability-teens-47",
          title: "Quiz on Water Systems",
          description: "Test your knowledge on water conservation and management",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-47"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-water-systems",
          index: 46,
        },
        {
          id: "sustainability-teens-48",
          title: "Reflex Water Manager",
          description: "Quickly identify effective water conservation strategies",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-48"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-water-manager",
          index: 47,
        },
        {
          id: "sustainability-teens-49",
          title: "Puzzle: Water Cycle",
          description: "Match water sources with sustainable usage practices",
          icon: <Puzzle className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-49"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-water-cycle",
          index: 48,
        },
        {
          id: "sustainability-teens-50",
          title: "Rainwater Story",
          description: "You want to collect rainwater. How do you start?",
          icon: <Cloud className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-teens-50"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/rainwater-story",
          index: 49,
        },
        {
          id: "sustainability-teens-51",
          title: "Debate: Water Rights",
          description: "Debate access to clean water as a human right",
          icon: <Speech className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-51"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-water-rights",
          index: 50,
        },
        {
          id: "sustainability-teens-52",
          title: "Journal of Water Footprint",
          description: "Calculate and reflect on your water footprint",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-52"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-water-footprint",
          index: 51,
        },
        {
          id: "sustainability-teens-53",
          title: "Simulation: Water Conservation Plan",
          description: "Design a water conservation program for your community",
          icon: <ClipboardCheck className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-53"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-water-conservation-plan",
          index: 52,
        },
        {
          id: "sustainability-teens-54",
          title: "Reflex Water Solutions",
          description: "Quickly identify innovative water-saving technologies",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-54"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-water-solutions",
          index: 53,
        },
        {
          id: "sustainability-teens-55",
          title: "Badge: Water Steward",
          description: "Earn your Water Steward badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-55"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-water-steward",
          index: 54,
        },
        {
          id: "sustainability-teens-56",
          title: "Forest Conservation Story",
          description: "Local forest is threatened by development. What's your action?",
          icon: <TreePine className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-56"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/forest-conservation-story",
          index: 55,
        },
        {
          id: "sustainability-teens-57",
          title: "Quiz on Biodiversity",
          description: "Test your knowledge on ecosystems and species protection",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-57"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-biodiversity",
          index: 56,
        },
        {
          id: "sustainability-teens-58",
          title: "Reflex Ecosystem Defender",
          description: "Quickly identify actions that protect biodiversity",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-58"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-ecosystem-defender",
          index: 57,
        },
        {
          id: "sustainability-teens-59",
          title: "Puzzle: Ecosystem Balance",
          description: "Match species with their role in maintaining ecosystem health",
          icon: <Puzzle className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-59"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-ecosystem-balance",
          index: 58,
        },
        {
          id: "sustainability-teens-60",
          title: "Marine Life Story",
          description: "You learn about ocean pollution. How do you take action?",
          icon: <Droplets className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-60"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/marine-life-story",
          index: 59,
        },
        {
          id: "sustainability-teens-61",
          title: "Debate: Conservation vs Development",
          description: "Debate balancing economic development with conservation",
          icon: <Speech className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-61"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-conservation-vs-development",
          index: 60,
        },
        {
          id: "sustainability-teens-62",
          title: "Journal of Nature Connection",
          description: "Reflect on your relationship with nature and wildlife",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-62"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-nature-connection",
          index: 61,
        },
        {
          id: "sustainability-teens-63",
          title: "Simulation: Wildlife Conservation Project",
          description: "Design a conservation initiative for endangered species",
          icon: <ClipboardCheck className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-63"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-wildlife-conservation-project",
          index: 62,
        },
        {
          id: "sustainability-teens-64",
          title: "Reflex Habitat Protector",
          description: "Quickly identify threats to biodiversity and solutions",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-64"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-habitat-protector",
          index: 63,
        },
        {
          id: "sustainability-teens-65",
          title: "Badge: Biodiversity Champion",
          description: "Earn your Biodiversity Champion badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-65"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-biodiversity-champion",
          index: 64,
        },
        {
          id: "sustainability-teens-66",
          title: "Climate March Story",
          description: "A climate protest is organized. Do you participate?",
          icon: <Globe className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-66"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/climate-march-story",
          index: 65,
        },
        {
          id: "sustainability-teens-67",
          title: "Quiz on Climate Science",
          description: "Test your understanding of climate change causes and effects",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-67"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-climate-science",
          index: 66,
        },
        {
          id: "sustainability-teens-68",
          title: "Reflex Climate Advocate",
          description: "Quickly identify effective climate action strategies",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-68"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-climate-advocate",
          index: 67,
        },
        {
          id: "sustainability-teens-69",
          title: "Puzzle: Climate Policies",
          description: "Match policy solutions with climate challenges",
          icon: <Puzzle className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-69"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-climate-policies",
          index: 68,
        },
        {
          id: "sustainability-teens-70",
          title: "School Policy Story",
          description: "Your school wants climate policies. What do you propose?",
          icon: <Building className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-70"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/school-policy-story",
          index: 69,
        },
        {
          id: "sustainability-teens-71",
          title: "Debate: Individual vs Systemic Change",
          description: "Debate the role of individual vs government action",
          icon: <Speech className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-71"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-individual-vs-systemic-change",
          index: 70,
        },
        {
          id: "sustainability-teens-72",
          title: "Journal of Climate Action",
          description: "Document your journey as a climate activist",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-72"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-climate-action",
          index: 71,
        },
        {
          id: "sustainability-teens-73",
          title: "Simulation: Climate Policy Proposal",
          description: "Draft a climate action plan for your school or city",
          icon: <ClipboardCheck className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-73"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-climate-policy-proposal",
          index: 72,
        },
        {
          id: "sustainability-teens-74",
          title: "Reflex Policy Solutions",
          description: "Quickly identify effective climate policies",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-74"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-policy-solutions",
          index: 73,
        },
        {
          id: "sustainability-teens-75",
          title: "Badge: Climate Advocate",
          description: "Earn your Climate Advocate badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-teens-75"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-climate-advocate",
          index: 74,
        },
    
        {
          id: "sustainability-teens-76",
          title: "Local Farm Story",
          description: "You discover a local organic farm. How do you support it?",
          icon: <TreePine className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-76"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/local-farm-story",
          index: 75,
        },
        {
          id: "sustainability-teens-77",
          title: "Quiz on Sustainable Agriculture",
          description: "Test your knowledge on eco-friendly farming practices",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-77"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-sustainable-agriculture-2",
          index: 76,
        },
        {
          id: "sustainability-teens-78",
          title: "Reflex Food System Thinker",
          description: "Quickly identify sustainable food choices",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-78"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-food-system-thinker",
          index: 77,
        },
        {
          id: "sustainability-teens-79",
          title: "Puzzle: Food Chain Impact",
          description: "Match food choices with their environmental footprint",
          icon: <Puzzle className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-79"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-food-chain-impact",
          index: 78,
        },
        {
          id: "sustainability-teens-80",
          title: "Urban Garden Story",
          description: "You want to start a community garden. How do you begin?",
          icon: <TreePine className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-80"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/urban-garden-story",
          index: 79,
        },
        {
          id: "sustainability-teens-81",
          title: "Debate: Organic vs Conventional",
          description: "Debate different farming approaches and their impacts",
          icon: <Speech className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-81"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-organic-vs-conventional",
          index: 80,
        },
        {
          id: "sustainability-teens-82",
          title: "Journal of Food Ethics",
          description: "Reflect on the ethics of your food choices",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-82"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-food-ethics",
          index: 81,
        },
        {
          id: "sustainability-teens-83",
          title: "Simulation: Farm-to-Table Project",
          description: "Design a local food system initiative",
          icon: <ClipboardCheck className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-83"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-farm-to-table-project",
          index: 82,
        },
        {
          id: "sustainability-teens-84",
          title: "Reflex Sustainable Food",
          description: "Quickly identify sustainable and ethical food sources",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-84"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-sustainable-food",
          index: 83,
        },
        {
          id: "sustainability-teens-85",
          title: "Badge: Food System Champion",
          description: "Earn your Food System Champion badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-85"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-food-system-champion",
          index: 84,
        },
        {
          id: "sustainability-teens-86",
          title: "Eco-Innovation Story",
          description: "You have an idea for green technology. How do you develop it?",
          icon: <Lightbulb className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-86"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/eco-innovation-story",
          index: 85,
        },
        {
          id: "sustainability-teens-87",
          title: "Quiz on Green Tech",
          description: "Test your knowledge on sustainable technology solutions",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-87"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-green-tech",
          index: 86,
        },
        {
          id: "sustainability-teens-88",
          title: "Reflex Tech Innovator",
          description: "Quickly identify green technology opportunities",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-88"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-tech-innovator",
          index: 87,
        },
        {
          id: "sustainability-teens-89",
          title: "Puzzle: Technology Impact",
          description: "Match technologies with their sustainability potential",
          icon: <Puzzle className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-89"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-technology-impact",
          index: 88,
        },
        {
          id: "sustainability-teens-90",
          title: "Startup Story",
          description: "You want to start an eco-business. What's your plan?",
          icon: <Briefcase className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-90"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/startup-story",
          index: 89,
        },
        {
          id: "sustainability-teens-91",
          title: "Debate: Tech Solution vs Behavior Change",
          description: "Debate technology vs lifestyle changes for sustainability",
          icon: <Speech className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-91"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-tech-solution-vs-behavior-change",
          index: 90,
        },
        {
          id: "sustainability-teens-92",
          title: "Journal of Innovation",
          description: "Document your ideas for sustainable innovations",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-92"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-innovation",
          index: 91,
        },
        {
          id: "sustainability-teens-93",
          title: "Simulation: Green Startup Plan",
          description: "Develop a business plan for a sustainable venture",
          icon: <ClipboardCheck className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-93"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-green-startup-plan",
          index: 92,
        },
        {
          id: "sustainability-teens-94",
          title: "Reflex Innovation Solutions",
          description: "Quickly identify green technology solutions to problems",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-94"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-innovation-solutions",
          index: 93,
        },
        {
          id: "sustainability-teens-95",
          title: "Badge: Green Innovator",
          description: "Earn your Green Innovator badge",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-95"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-green-innovator",
          index: 94,
        },
        {
          id: "sustainability-teens-96",
          title: "Leadership Story",
          description: "You're asked to lead a sustainability initiative. How do you inspire others?",
          icon: <Users className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-96"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/leadership-story",
          index: 95,
        },
        {
          id: "sustainability-teens-97",
          title: "Quiz on Sustainability Leadership",
          description: "Test your knowledge on leading change for sustainability",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-97"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-sustainability-leadership",
          index: 96,
        },
        {
          id: "sustainability-teens-98",
          title: "Reflex Change Leader",
          description: "Quickly identify effective leadership strategies for sustainability",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-98"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-change-leader",
          index: 97,
        },
        {
          id: "sustainability-teens-99",
          title: "Simulation: Community Sustainability Plan",
          description: "Design a comprehensive sustainability plan for your community",
          icon: <ClipboardCheck className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-99"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-community-sustainability-plan",
          index: 98,
        },
        {
          id: "sustainability-teens-100",
          title: "Badge: Master Sustainability Leader",
          description: "Master all sustainability challenges to become a leader",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-teens-100"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-master-sustainability-leader",
          index: 99,
        }
    ];
    
    return sustainabilityGamesTeen;
};
