import Program from "../models/Program.js";
import ProgramSchool from "../models/ProgramSchool.js";
import ProgramCheckpoint from "../models/ProgramCheckpoint.js";
import ProgramMetrics from "../models/ProgramMetrics.js";
import CSRSponsor from "../models/CSRSponsor.js";
import reportGenerationService from "../services/reportGenerationService.js";

/**
 * Validate CSR ownership of program
 */
const validateCSROwnership = async (programId, user) => {
  const sponsor = await CSRSponsor.findOne({ userId: user._id });
  if (!sponsor) {
    const error = new Error("CSR Partner profile not found");
    error.status = 404;
    throw error;
  }

  const program = await Program.findOne({
    $or: [{ _id: programId }, { programId }],
  });

  if (!program) {
    const error = new Error("Program not found");
    error.status = 404;
    throw error;
  }

  if (program.csrPartnerId.toString() !== sponsor._id.toString()) {
    const error = new Error("You do not have access to this program");
    error.status = 403;
    throw error;
  }

  return { sponsor, program };
};

/**
 * List available reports for a program
 */
export const listReports = async (req, res) => {
  try {
    const { programId } = req.params;
    await validateCSROwnership(programId, req.user);

    const program = await Program.findOne({
      $or: [{ _id: programId }, { programId }],
    });

    // Get metrics to check if data is available
    const metrics = await ProgramMetrics.findOne({ programId: program._id });
    const schoolCount = await ProgramSchool.countDocuments({ programId: program._id });
    const getPublishedAt = (type) => {
      const entry = (program.publishedReports || []).find((r) => r.reportType === type);
      return entry?.publishedAt || null;
    };

    res.json({
      data: {
        reports: [
          {
            type: "impact_summary",
            name: "Impact Summary",
            description: "2-4 page summary for CSR/ESG reports",
            format: "pdf",
            available: true,
            generatedAt: metrics?.lastComputedAt || new Date(),
            publishedAt: getPublishedAt("impact_summary"),
          },
          {
            type: "school_coverage",
            name: "School Coverage Report",
            description: "Detailed school-level coverage for audits",
            formats: ["excel", "pdf"],
            available: schoolCount > 0,
            generatedAt: new Date(),
            publishedAt: getPublishedAt("school_coverage"),
          },
          {
            type: "compliance",
            name: "Compliance Summary",
            description: "Compliance and governance documentation",
            format: "pdf",
            available: true,
            generatedAt: new Date(),
            publishedAt: getPublishedAt("compliance"),
          },
        ],
        note: "Reports are generated by WiseStudent and cannot be edited. Recognition metrics in Impact Summary match your Recognition page (certificates issued, badges, kits in progress).",
      },
    });
  } catch (error) {
    console.error("List reports error:", error);
    res.status(error.status || 500).json({
      message: error.message || "Failed to list reports",
    });
  }
};

/**
 * Download Impact Summary PDF
 */
export const downloadImpactSummary = async (req, res) => {
  try {
    const { programId } = req.params;
    await validateCSROwnership(programId, req.user);

    // Find program by ID or programId
    const program = await Program.findOne({
      $or: [{ _id: programId }, { programId }],
    });

    if (!program) {
      return res.status(404).json({ message: "Program not found" });
    }

    // Generate PDF using the service
    const pdfBuffer = await reportGenerationService.generateImpactSummaryPDF(program._id);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="impact-summary-${program.programId || program._id}.pdf"`
    );
    res.send(pdfBuffer);
  } catch (error) {
    console.error("Download impact summary error:", error);
    res.status(error.status || 500).json({
      message: error.message || "Failed to download impact summary",
    });
  }
};

/**
 * Download School Coverage Report (Excel or PDF)
 */
export const downloadSchoolCoverage = async (req, res) => {
  try {
    const { programId } = req.params;
    const { format = "pdf" } = req.query;
    await validateCSROwnership(programId, req.user);

    // Find program by ID or programId
    const program = await Program.findOne({
      $or: [{ _id: programId }, { programId }],
    });

    if (!program) {
      return res.status(404).json({ message: "Program not found" });
    }

    let buffer;
    let contentType;
    let extension;

    if (format === "excel") {
      buffer = await reportGenerationService.generateSchoolCoverageExcel(program._id);
      contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
      extension = "xlsx";
    } else {
      buffer = await reportGenerationService.generateSchoolCoveragePDF(program._id);
      contentType = "application/pdf";
      extension = "pdf";
    }

    res.setHeader("Content-Type", contentType);
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="school-coverage-${program.programId || program._id}.${extension}"`
    );
    res.send(buffer);
  } catch (error) {
    console.error("Download school coverage error:", error);
    res.status(error.status || 500).json({
      message: error.message || "Failed to download school coverage report",
    });
  }
};

/**
 * Download Compliance Summary PDF
 */
export const downloadComplianceSummary = async (req, res) => {
  try {
    const { programId } = req.params;
    await validateCSROwnership(programId, req.user);

    // Find program by ID or programId
    const program = await Program.findOne({
      $or: [{ _id: programId }, { programId }],
    });

    if (!program) {
      return res.status(404).json({ message: "Program not found" });
    }

    // Generate PDF using the service
    const pdfBuffer = await reportGenerationService.generateCompliancePDF(program._id);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="compliance-summary-${program.programId || program._id}.pdf"`
    );
    res.send(pdfBuffer);
  } catch (error) {
    console.error("Download compliance summary error:", error);
    res.status(error.status || 500).json({
      message: error.message || "Failed to download compliance summary",
    });
  }
};

export default {
  listReports,
  downloadImpactSummary,
  downloadSchoolCoverage,
  downloadComplianceSummary,
};
