import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  FileText,
  Table,
  CheckSquare,
  Download,
  AlertCircle,
  RefreshCw,
} from "lucide-react";
import toast from "react-hot-toast";
import csrProgramService from "../../services/csr/programService";

const formatDate = (date) => {
  if (!date) return "N/A";
  return new Date(date).toLocaleDateString("en-IN", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
};

const DEFAULT_NOTE =
  "Reports are generated by WiseStudent and cannot be edited. Impact Summary includes recognition metrics (certificates issued, badges issued, kits in progress) aligned with your Recognition page. Contact support if you need corrections.";

const getReportByType = (reports, type) =>
  Array.isArray(reports?.reports)
    ? reports.reports.find((r) => r.type === type)
    : null;

const CSRImpactReports = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [reports, setReports] = useState(null);
  const [error, setError] = useState("");
  const [downloading, setDownloading] = useState(null);
  const [programId, setProgramId] = useState(null);

  const fetchData = async (showToast = false) => {
    if (!refreshing) setLoading(true);
    setRefreshing(true);
    setError("");
    try {
      const programsRes = await csrProgramService.getMyPrograms();
      const programs = programsRes?.data || [];

      if (programs.length === 0) {
        navigate("/csr/no-program", { replace: true });
        return;
      }

      const id = programs[0]._id;
      setProgramId(id);
      const res = await csrProgramService.getReports(id);
      const payload = res?.data ?? res;

      if (payload) {
        setReports(payload);
        if (showToast) toast.success("Reports list refreshed");
      } else {
        setError("Failed to load reports");
      }
    } catch (err) {
      console.error("Failed to load reports:", err);
      const errorMessage =
        err?.response?.data?.message || "Failed to load reports";
      setError(errorMessage);

      if (
        err?.response?.status === 404 ||
        errorMessage.toLowerCase().includes("no programs")
      ) {
        navigate("/csr/no-program", { replace: true });
        return;
      }

      if (showToast) toast.error(errorMessage);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleRefresh = () => fetchData(true);

  const handleDownload = async (reportType, format = "pdf") => {
    if (!programId) return;

    const key = `${reportType}-${format}`;
    setDownloading(key);
    try {
      toast.loading("Generating report...", { id: "report-dl" });

      let blob;
      const ext = format === "excel" ? "xlsx" : "pdf";
      const baseName = `${reportType.replace(/_/g, "-")}-${programId}`;

      if (reportType === "impact_summary") {
        blob = await csrProgramService.downloadImpactSummary(programId);
      } else if (reportType === "school_coverage") {
        blob = await csrProgramService.downloadSchoolCoverage(programId, format);
      } else if (reportType === "compliance") {
        blob = await csrProgramService.downloadComplianceSummary(programId);
      } else {
        throw new Error("Unknown report type");
      }

      if (blob instanceof Blob && blob.type?.includes("application/json")) {
        const text = await blob.text();
        const json = JSON.parse(text);
        throw new Error(json?.message || "Download failed");
      }

      const url = window.URL.createObjectURL(new Blob([blob]));
      const a = document.createElement("a");
      a.href = url;
      a.download = `${baseName}.${ext}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();

      toast.success("Report downloaded successfully", { id: "report-dl" });
    } catch (err) {
      console.error("Download error:", err);
      const msg =
        err?.response?.data?.message || err?.message || "Failed to download report";
      toast.error(msg, { id: "report-dl" });
    } finally {
      setDownloading(null);
    }
  };

  if (loading && !reports) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="flex items-center gap-2 text-slate-500">
          <RefreshCw className="w-5 h-5 animate-spin" />
          <span>Loading reports...</span>
        </div>
      </div>
    );
  }

  if (error && !reports) {
    return (
      <div className="min-h-screen bg-slate-50">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 shadow-sm text-center">
            <AlertCircle className="w-12 h-12 text-amber-500 mx-auto mb-3" />
            <h2 className="text-lg font-semibold text-amber-900 mb-2">{error}</h2>
            <p className="text-sm text-amber-700 mb-4">
              Please try again or contact support if the issue persists.
            </p>
            <div className="flex gap-2 justify-center">
              <button
                onClick={handleRefresh}
                className="inline-flex items-center gap-2 rounded-xl border border-amber-200 bg-white px-4 py-2 text-xs font-semibold uppercase tracking-wide text-amber-700 hover:bg-amber-50 transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                Retry
              </button>
              <button
                onClick={() => navigate("/csr/profile")}
                className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold uppercase tracking-wide text-slate-700 hover:bg-slate-50 transition-colors"
              >
                View Profile
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const note = reports?.note || DEFAULT_NOTE;

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="max-w-4xl mx-auto px-4 py-8 space-y-6">
        {/* HEADER */}
        <header className="flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400">
                Reports
              </p>
              <h1 className="text-3xl font-bold text-slate-900">
                Impact Reports
              </h1>
              <p className="text-sm text-slate-500 mt-1">
                Download reports for your CSR/ESG annual reporting. Includes reach, engagement, recognition (certificates issued, badges issued, kits in progress), and readiness exposure.
              </p>
            </div>
            <button
              onClick={handleRefresh}
              disabled={refreshing}
              className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold uppercase tracking-wide text-slate-600 hover:bg-slate-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <RefreshCw className={`w-4 h-4 ${refreshing ? "animate-spin" : ""}`} />
              Refresh
            </button>
          </div>
        </header>

        {/* REPORT CARDS - equal height; footer pinned to bottom of each card */}
        <section className="grid gap-4 md:grid-cols-1 lg:grid-cols-3">
          <article className="bg-white rounded-2xl border border-slate-100 p-5 shadow-sm hover:shadow-md transition-shadow flex flex-col h-full">
            <div className="flex-1 min-h-0 flex flex-col">
            <div className="flex items-start gap-3">
              <div className="p-3 rounded-xl bg-gradient-to-br from-indigo-50 to-indigo-100">
                <FileText className="w-5 h-5 text-indigo-600" />
              </div>
              <div className="flex-1">
                <h3 className="text-base font-semibold text-slate-900">
                  Impact Summary
                </h3>
                <p className="text-sm text-slate-500 mt-1">
                  2–4 page summary: reach, engagement, recognition (certificates issued, badges issued, kits in progress), readiness exposure
                </p>
              </div>
            </div>
            </div>
            <div className="pt-2 mt-4 border-t border-slate-100 flex flex-col space-y-4 shrink-0">
              <div>
                <p className="text-xs text-slate-400">Format: PDF</p>
                <p className="text-xs text-slate-400">
                  Last generated:{" "}
                  {formatDate(getReportByType(reports, "impact_summary")?.generatedAt)}
                </p>
              </div>
              <button
                onClick={() => handleDownload("impact_summary", "pdf")}
                disabled={downloading === "impact_summary-pdf"}
                className="w-full flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 px-4 py-2.5 text-xs font-semibold uppercase tracking-wide text-white shadow-md hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Download className="w-4 h-4" />
                {downloading === "impact_summary-pdf" ? "Downloading..." : "Download PDF"}
              </button>
            </div>
          </article>

          <article className="bg-white rounded-2xl border border-slate-100 p-5 shadow-sm hover:shadow-md transition-shadow flex flex-col h-full">
            <div className="flex-1 min-h-0 flex flex-col">
            <div className="flex items-start gap-3">
              <div className="p-3 rounded-xl bg-gradient-to-br from-emerald-50 to-emerald-100">
                <Table className="w-5 h-5 text-emerald-600" />
              </div>
              <div className="flex-1">
                <h3 className="text-base font-semibold text-slate-900">
                  School Coverage Report
                </h3>
                <p className="text-sm text-slate-500 mt-1">
                  School-level coverage: students covered per school, districts, status—for audits
                </p>
              </div>
            </div>
            </div>
            <div className="pt-2 mt-4 border-t border-slate-100 flex flex-col space-y-4 shrink-0">
              <div>
                <p className="text-xs text-slate-400">Format: Excel / PDF</p>
                <p className="text-xs text-slate-400">
                  Last generated:{" "}
                  {formatDate(getReportByType(reports, "school_coverage")?.generatedAt)}
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => handleDownload("school_coverage", "excel")}
                  disabled={downloading === "school_coverage-excel"}
                  className="flex-1 flex items-center justify-center gap-2 rounded-xl border border-emerald-500 px-3 py-2.5 text-xs font-semibold uppercase tracking-wide text-emerald-600 hover:bg-emerald-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <Download className="w-4 h-4" />
                  {downloading === "school_coverage-excel" ? "..." : "Excel"}
                </button>
                <button
                  onClick={() => handleDownload("school_coverage", "pdf")}
                  disabled={downloading === "school_coverage-pdf"}
                  className="flex-1 flex items-center justify-center gap-2 rounded-xl border border-emerald-500 px-3 py-2.5 text-xs font-semibold uppercase tracking-wide text-emerald-600 hover:bg-emerald-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <Download className="w-4 h-4" />
                  {downloading === "school_coverage-pdf" ? "..." : "PDF"}
                </button>
              </div>
            </div>
          </article>

          <article className="bg-white rounded-2xl border border-slate-100 p-5 shadow-sm hover:shadow-md transition-shadow flex flex-col h-full">
            <div className="flex-1 min-h-0 flex flex-col">
            <div className="flex items-start gap-3">
              <div className="p-3 rounded-xl bg-gradient-to-br from-purple-50 to-purple-100">
                <CheckSquare className="w-5 h-5 text-purple-600" />
              </div>
              <div className="flex-1">
                <h3 className="text-base font-semibold text-slate-900">
                  Compliance Summary
                </h3>
                <p className="text-sm text-slate-500 mt-1">
                  Governance and compliance documentation for the program
                </p>
              </div>
            </div>
            </div>
            <div className="pt-2 mt-4 border-t border-slate-100 flex flex-col space-y-4 shrink-0">
              <div>
                <p className="text-xs text-slate-400">Format: PDF</p>
                <p className="text-xs text-slate-400">
                  Last generated:{" "}
                  {formatDate(getReportByType(reports, "compliance")?.generatedAt)}
                </p>
              </div>
              <button
                onClick={() => handleDownload("compliance", "pdf")}
                disabled={downloading === "compliance-pdf"}
                className="w-full flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-purple-600 to-pink-600 px-4 py-2.5 text-xs font-semibold uppercase tracking-wide text-white shadow-md hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Download className="w-4 h-4" />
                {downloading === "compliance-pdf" ? "Downloading..." : "Download PDF"}
              </button>
            </div>
          </article>
        </section>

        {/* INFO NOTE */}
        <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5 shadow-sm">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-5 h-5 text-slate-400 flex-shrink-0" />
            <p className="text-sm text-slate-600">{note}</p>
          </div>
        </section>

        {refreshing && reports && (
          <div className="fixed bottom-4 right-4 bg-white rounded-xl border border-slate-200 px-4 py-2 shadow-lg flex items-center gap-2">
            <RefreshCw className="w-4 h-4 animate-spin text-indigo-600" />
            <span className="text-xs text-slate-600">Refreshing...</span>
          </div>
        )}
      </div>
    </div>
  );
};

export default CSRImpactReports;
