import {
    Coins,
    Puzzle,
    Users,
    Zap,
    Heart,
    Shield,
    Target,
    BookOpen,
    GraduationCap,
    HandHeart,
    Eye,
    MessageSquare,
    Award,
    HelpCircle,
    Mic,
    Notebook,
    Edit3,
    Moon,
    PenTool,
    UserCheck,
  } from "lucide-react";
import buildIds from "../buildGameIds";


export const moralGamesTeenIds = buildIds("moral", "teen")

export const getMoralTeenGames = (gameCompletionStatus)=> {
    const moralGamesTeen = [
        {
          id: "moral-teen-1",
          title: "Friend's Lie Story",
          description: "Refuse to lie for friend",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-1"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/friend-lie-story",
          index: 0,
        },
        {
          id: "moral-teen-2",
          title: "White Lie Quiz",
          description: "Can small lies be harmless?",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-2"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/white-lie-quiz",
          index: 1,
        },
        {
          id: "moral-teen-3",
          title: "Reflex: Spot Fake",
          description: "Identify fake news quickly",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-3"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/reflex-spot-fake",
          index: 2,
        },
        {
          id: "moral-teen-4",
          title: "Puzzle of Integrity",
          description: "Integrity = Doing right when unseen",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-4"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/puzzle-of-integrity",
          index: 3,
        },
        {
          id: "moral-teen-5",
          title: "Bribe Simulation",
          description: "Refuse bribe and report it",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7-9 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-5"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/bribe-simulation",
          index: 4,
        },
        {
          id: "moral-teen-6",
          title: "Debate: Lying for Friend",
          description: "Is lying okay to protect a friend?",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-6"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/debate-lying-for-friend",
          index: 5,
        },
        {
          id: "moral-teen-7",
          title: "Integrity Journal",
          description: "Write about telling a hard truth",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-7"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/integrity-journal",
          index: 6,
        },
        {
          id: "moral-teen-8",
          title: "Exam Cheating Story",
          description: "Resist temptation to cheat",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-8"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/exam-cheating-story",
          index: 7,
        },
        {
          id: "moral-teen-9",
          title: "Roleplay: Truthful Leader",
          description: "Lead group with honesty",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-9"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/roleplay-truthful-leader",
          index: 8,
        },
        {
          id: "moral-teen-10",
          title: "Badge: Integrity Hero",
          description: "Complete 5 integrity dilemmas",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-10"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/badge-integrity-hero",
          index: 9,
        },
        {
          id: "moral-teen-11",
          title: "Debate: Obey or Question",
          description: "Respect vs blind obedience",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-11"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/debate-obey-or-question",
          index: 10,
        },
        {
          id: "moral-teen-12",
          title: "Gratitude Story",
          description: "Thank friend for sharing notes",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-12"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/gratitude-story",
          index: 11,
        },
        {
          id: "moral-teen-13",
          title: "Reflex: Politeness",
          description: "Tap polite vs rude phrases",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-13"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/reflex-politeness",
          index: 12,
        },
        {
          id: "moral-teen-14",
          title: "Puzzle of Gratitude",
          description: "Thanks → Smile, Ignore → Hurt",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-14"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/puzzle-of-gratitude",
          index: 13,
        },
        {
          id: "moral-teen-15",
          title: "Service Story",
          description: "Return dropped money to conductor",
          icon: <Coins className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-15"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/service-story",
          index: 14,
        },
        {
          id: "moral-teen-16",
          title: "Respect Journal",
          description: "This week I showed respect by...",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-16"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/respect-journal",
          index: 15,
        },
        {
          id: "moral-teen-17",
          title: "Debate: Respect Teachers",
          description: "Argue rudely with teachers?",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-17"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/debate-respect-teachers",
          index: 16,
        },
        {
          id: "moral-teen-18",
          title: "Roleplay: Respect Leader",
          description: "Lead by listening to everyone",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-18"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/roleplay-respect-leader",
          index: 17,
        },
        {
          id: "moral-teen-19",
          title: "Reflex: Gratitude",
          description: "Spot thank you vs rude emojis",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-19"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/reflex-gratitude",
          index: 18,
        },
        {
          id: "moral-teen-20",
          title: "Badge: Gratitude Hero",
          description: "Complete 5 gratitude acts",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-20"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/badge-gratitude-hero",
          index: 19,
        },
        {
        id: "moral-teen-21",
        title: "Empathy Story",
        description: "New student feels lonely. Do you invite them? → Yes.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-21"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/empathy-story",
        index: 20,
        },
        {
        id: "moral-teen-22",
        title: "Quiz of Feelings",
        description: "Classmate cries. What do you do? Correct = Comfort.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-22"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-feelings",
        index: 21,
        },
        {
        id: "moral-teen-23",
        title: "Reflex Empathy",
        description: "Tap for ‘Understand,’ avoid ‘Ignore.’",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-23"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-empathy",
        index: 22,
        },
        {
        id: "moral-teen-24",
        title: "Puzzle: Feelings Match",
        description: "Match ‘Smile → Happy, Tears → Sad, Frown → Angry.’",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-24"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/feelings-puzzle",
        index: 23,
        },
        {
        id: "moral-teen-25",
        title: "Roleplay: Walk in Shoes",
        description: "Pretend you are a new student. How would you feel? → Lonely.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-25"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-walk-in-shoes",
        index: 24,
        },
        {
        id: "moral-teen-26",
        title: "Debate: Kindness or Strength",
        description: "Is kindness weakness or strength? → Strength.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-26"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-kindness-strength",
        index: 25,
        },
        {
        id: "moral-teen-27",
        title: "Journal of Empathy",
        description: "Write: ‘One time I understood someone’s feelings was ___.’",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-27"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-empathy1",
        index: 26,
        },
        {
        id: "moral-teen-28",
        title: "Helping Hand Story",
        description: "Classmate drops books. Do you help? → Yes.",
        icon: <HandHeart className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-28"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/helping-hand-story",
        index: 27,
        },
        {
        id: "moral-teen-29",
        title: "Reflex Comfort",
        description: "Tap when ‘Comfort’ appears, avoid ‘Laugh at.’",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-29"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-comfort",
        index: 28,
        },
        {
        id: "moral-teen-30",
        title: "Badge: Empathy Hero",
        description: "Complete 5 empathy actions to earn your badge.",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-30"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-empathy-hero",
        index: 29,
        },
        {
        id: "moral-teen-31",
        title: "Responsibility Story",
        description: "You’re leader of project. Do you divide work fairly or dump on others? → Divide fairly.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-31"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/responsibility-story",
        index: 30,
        },
        {
        id: "moral-teen-32",
        title: "Quiz of Discipline",
        description: "Which is disciplined? Correct = Submitting early.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-32"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-discipline",
        index: 31,
        },
        {
        id: "moral-teen-33",
        title: "Reflex Time Management",
        description: "Tap for ‘Plan Study,’ avoid ‘Last-minute Panic.’",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-33"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-time-management",
        index: 32,
        },
        {
        id: "moral-teen-34",
        title: "Puzzle of Self Control",
        description: "Match ‘Discipline → Success, Laziness → Failure.’",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-34"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-self-control",
        index: 33,
        },
        {
        id: "moral-teen-35",
        title: "Late Night Party Story",
        description: "Exam tomorrow, friends want party. Correct = Stay home.",
        icon: <Moon className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-35"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/late-night-party-story",
        index: 34,
        },
        {
        id: "moral-teen-36",
        title: "Debate: Rules vs Freedom",
        description: "Do rules kill freedom or create order? → Create order.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-36"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-rules-vs-freedom",
        index: 35,
        },
        {
        id: "moral-teen-37",
        title: "Journal of Discipline",
        description: "Write: ‘One self-discipline habit I’m proud of is ___.’",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-37"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-discipline",
        index: 36,
        },
        {
        id: "moral-teen-38",
        title: "Roleplay: Group Leader",
        description: "Play as leader ensuring team finishes tasks on time.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-38"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-group-leader",
        index: 37,
        },
        {
        id: "moral-teen-39",
        title: "Reflex Duty Check",
        description: "Tap for ‘Keep Promise,’ avoid ‘Break Promise.’",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-39"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-duty-check",
        index: 38,
        },
        {
        id: "moral-teen-40",
        title: "Badge: Discipline Hero",
        description: "Complete 5 discipline actions to earn your badge.",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-40"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-discipline-hero",
        index: 39,
        },
        {
        id: "moral-teen-41",
        title: "Classroom Story",
        description: "Teacher blames wrong student. Do you defend them? → Yes.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-41"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/classroom-story2",
        index: 40,
        },
        {
        id: "moral-teen-42",
        title: "Justice Quiz",
        description: "Which is just? Correct = Punishing the guilty, not the innocent.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-42"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/justice-quiz",
        index: 41,
        },
        {
        id: "moral-teen-43",
        title: "Reflex Justice Symbols",
        description: "Tap for ⚖️ (justice) and avoid ❌ (injustice).",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-43"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-justice-symbols",
        index: 42,
        },
        {
        id: "moral-teen-44",
        title: "Puzzle of Fairness",
        description: "Match ‘Equality → Justice, Bullying → Injustice.’",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-44"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-fairness1",
        index: 43,
        },
        {
        id: "moral-teen-45",
        title: "Bully Story",
        description: "Friend is bullied. Do you stand with the victim? → Yes.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-45"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/bully-story2",
        index: 44,
        },
        {
        id: "moral-teen-46",
        title: "Debate: Equal vs Fair",
        description: "Is ‘equal’ always fair? → Sometimes fair means need-based.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-46"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-equal-vs-fair",
        index: 45,
        },
        {
        id: "moral-teen-47",
        title: "Journal of Fairness",
        description: "Write: ‘One injustice I noticed and wanted to fix was ___.’",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-47"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-fairness",
        index: 46,
        },
        {
        id: "moral-teen-48",
        title: "Roleplay: Justice Leader",
        description: "Be class captain ensuring rules are fair for all.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-48"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-justice-leader",
        index: 47,
        },
        {
        id: "moral-teen-49",
        title: "Reflex Stand Up",
        description: "Tap for ‘Stand for Truth,’ avoid ‘Stay Silent.’",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-49"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-stand-up",
        index: 48,
        },
        {
        id: "moral-teen-50",
        title: "Badge: Justice Hero",
        description: "Complete 5 justice actions to earn your badge.",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6–8 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-50"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-justice-hero",
        index: 49,
        },
        {
        id: "moral-teen-51",
        title: "Witness Story",
        description: "You see cheating in exam. Do you report or stay silent? → Report.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-51"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/witness-story",
        index: 50,
        },
        {
        id: "moral-teen-52",
        title: "Courage Quiz",
        description: "Which is real courage? Correct = Protecting others.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-52"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/courage-quiz1",
        index: 51,
        },
        {
        id: "moral-teen-53",
        title: "Reflex Moral Courage",
        description: "Tap for ‘Tell Truth,’ avoid ‘Hide Wrong.’",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-53"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-moral-courage",
        index: 52,
        },
        {
        id: "moral-teen-54",
        title: "Puzzle of Heroes",
        description: "Match ‘Mahatma Gandhi → Non-violence, Malala → Education.’",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-54"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-heroes",
        index: 53,
        },
        {
        id: "moral-teen-55",
        title: "Group Pressure Story",
        description: "Friends tease new student. Do you join or stop? → Stop.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-55"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/group-pressure-story",
        index: 54,
        },
        {
        id: "moral-teen-56",
        title: "Debate: Fear vs Courage",
        description: "Is courage the absence of fear? → No, it’s acting despite fear.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-56"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-fear-vs-courage",
        index: 55,
        },
        {
        id: "moral-teen-57",
        title: "Courage Journal",
        description: "Write: ‘A time I stood up for someone was ___.’",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-57"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/courage-journal1",
        index: 56,
        },
        {
        id: "moral-teen-58",
        title: "Bravery Story",
        description: "Class blames one student wrongly. Do you defend them? → Yes.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-58"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/bravery-story",
        index: 57,
        },
        {
        id: "moral-teen-59",
        title: "Roleplay: Courageous Leader",
        description: "Lead a group and stop unfair practice.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-59"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-courageous-leader",
        index: 58,
        },
        {
        id: "moral-teen-60",
        title: "Badge: Courage Hero",
        description: "Complete 5 courageous acts to earn your badge.",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6–8 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-60"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-courage-hero",
        index: 59,
        },
        {
        id: "moral-teen-61",
        title: "Group Project Story",
        description: "Leader ignores ideas. Is that cooperation? → No.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-61"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/group-project-story",
        index: 60,
        },
        {
        id: "moral-teen-62",
        title: "Quiz on Team Skills",
        description: "Best teamwork trait? (a) Listening, (b) Arguing, (c) Blaming). Correct = Listening.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-62"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-team-skills",
        index: 61,
        },
        {
        id: "moral-teen-63",
        title: "Reflex Collaboration",
        description: "Tap for “Encourage,” for “Mock.”",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-63"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-collaboration",
        index: 62,
        },
        {
        id: "moral-teen-64",
        title: "Puzzle: Great Teams",
        description: "Match “Wright Brothers → Airplane, Cricket Team → Victory.”",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-64"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-great-teams",
        index: 63,
        },
        {
        id: "moral-teen-65",
        title: "Leadership Story",
        description: "Captain takes credit for all work. Is this fair? → No.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-65"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/leadership-story",
        index: 64,
        },
        {
        id: "moral-teen-66",
        title: "Debate: Team vs Individual",
        description: "Which is better — working alone or in team? → Team.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "8 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-66"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-team-vs-individual",
        index: 65,
        },
        {
        id: "moral-teen-67",
        title: "Journal of Cooperation",
        description: "Write: “One time my team achieved more than I could alone was ___.”",
        icon: <Edit3 className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-67"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-cooperation",
        index: 66,
        },
        {
        id: "moral-teen-68",
        title: "Roleplay: Good Teammate",
        description: "Act as teammate who listens and encourages.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-68"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-good-teammate",
        index: 67,
        },
        {
        id: "moral-teen-69",
        title: "Reflex Fair Share",
        description: "Tap when “Share Credit” shows, for “Take All Credit.”",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-69"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-fair-share",
        index: 68,
        },
        {
        id: "moral-teen-70",
        title: "Badge: Team Hero",
        description: "Complete 5 cooperation actions to earn the Badge “Team Hero.”",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "10 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-70"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-team-hero",
        index: 69,
        },
        {
        id: "moral-teen-71",
        title: "Leader Story",
        description: "Leader eats first before team. Is this good leadership? → No.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-71"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/leader-story",
        index: 70,
        },
        {
        id: "moral-teen-72",
        title: "Quiz on Leadership",
        description: "Best leader is one who (a) Commands, (b) Serves, (c) Ignores). Correct = Serves.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-72"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-leadership",
        index: 71,
        },
        {
        id: "moral-teen-73",
        title: "Reflex Leadership Traits",
        description: "Tap for “Inspire,” for “Order Rudely.”",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-73"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-leadership-traits",
        index: 72,
        },
        {
        id: "moral-teen-74",
        title: "Puzzle of Leaders",
        description: "Match “Gandhi → Non-violence, Mother Teresa → Service.”",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-74"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-leaders",
        index: 73,
        },
        {
        id: "moral-teen-75",
        title: "Community Story",
        description: "Local park is dirty. Do you lead friends to clean? → Yes.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-75"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/community-story",
        index: 74,
        },
        {
        id: "moral-teen-76",
        title: "Debate: Boss vs Leader",
        description: "Is a boss the same as a leader? → No, leader serves.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "8 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-76"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-boss-vs-leader",
        index: 75,
        },
        {
        id: "moral-teen-77",
        title: "Journal of Leadership",
        description: "Write: “One time I led others by example was ___.”",
        icon: <Edit3 className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-77"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-leadership",
        index: 76,
        },
        {
        id: "moral-teen-78",
        title: "Roleplay: True Leader",
        description: "Act as leader who serves team first.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-78"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-true-leader",
        index: 77,
        },
        {
        id: "moral-teen-79",
        title: "Reflex Team First",
        description: "Tap when “Serve Others” shows, for “Me First.”",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-79"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-team-first",
        index: 78,
        },
        {
        id: "moral-teen-80",
        title: "Badge: Service Leader",
        description: "Complete 5 leadership actions to earn the Badge “Service Leader.”",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "10 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-80"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-service-leader",
        index: 79,
        },
        {
        id: "moral-teen-81",
        title: "Class Argument Story",
        description: "Two classmates argue loudly. Do you mediate? → Yes.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-81"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/class-argument-story",
        index: 80,
        },
        {
        id: "moral-teen-82",
        title: "Quiz on Conflict",
        description: "Best way to solve conflict? (a) Listen, (b) Shout louder, (c) Ignore). Correct = Listen.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-82"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-on-conflict",
        index: 81,
        },
        {
        id: "moral-teen-83",
        title: "Reflex Peace Symbols",
        description: "Tap for peace symbol, avoid conflict symbol.",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-83"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-peace-symbols",
        index: 82,
        },
        {
        id: "moral-teen-84",
        title: "Puzzle of Resolution",
        description: "Match “Talk → Solution, Violence → Problem.”",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-84"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-resolution",
        index: 83,
        },
        {
        id: "moral-teen-85",
        title: "Friend Group Story",
        description: "Two friends argue over project credit. Do you split credit fairly? → Yes.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-85"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/friend-group-story",
        index: 84,
        },
        {
        id: "moral-teen-86",
        title: "Debate: Peace vs Revenge",
        description: "Does revenge bring peace? → No.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "8 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-86"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-peace-vs-revenge",
        index: 85,
        },
        {
        id: "moral-teen-87",
        title: "Journal of Resolution",
        description: "Write: “One time I resolved a conflict was ___.”",
        icon: <Edit3 className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-87"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-of-resolution",
        index: 86,
        },
        {
        id: "moral-teen-88",
        title: "Roleplay: Mediator",
        description: "Act as mediator calming two fighting students.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-88"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-mediator",
        index: 87,
        },
        {
        id: "moral-teen-89",
        title: "Reflex Calm Action",
        description: "Tap for “Take Deep Breath,” avoid “Shout Back.”",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-89"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-calm-action",
        index: 88,
        },
        {
        id: "moral-teen-90",
        title: "Badge: Peace Hero",
        description: "Complete 5 conflict resolutions to earn the Badge “Peace Hero.”",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "10 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-90"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-peace-hero",
        index: 89,
        },
        {
        id: "moral-teen-91",
        title: "Money Found Story",
        description: "You find money on the road. Keep or give to teacher? → Give to teacher.",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-91"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/money-found-story",
        index: 90,
        },
        {
        id: "moral-teen-92",
        title: "Ethical Quiz",
        description: "Is it okay to copy small homework? → No.",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2-3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-92"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/ethical-quiz",
        index: 91,
        },
        {
        id: "moral-teen-93",
        title: "Reflex: Right vs Easy",
        description: "Tap for right actions, avoid shortcuts.",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2-3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-93"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-right-vs-easy",
        index: 92,
        },
        {
        id: "moral-teen-94",
        title: "Puzzle of Ethics",
        description: "Match 'Fairness → Justice' and 'Stealing → Wrong'.",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-94"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-ethics",
        index: 93,
        },
        {
        id: "moral-teen-95",
        title: "Peer Pressure Story",
        description: "Friends push you to break rule. Correct = Refuse.",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3-4 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-95"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/peer-pressure-story1",
        index: 94,
        },
        {
        id: "moral-teen-96",
        title: "Debate: Right vs Popular",
        description: "Should you do what’s popular or what’s right? → What’s right.",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "5-6 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-96"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-right-vs-popular",
        index: 95,
        },
        {
        id: "moral-teen-97",
        title: "Journal of Ethics",
        description: "Write: 'One hard but right choice I made was ___.'",
        icon: <PenTool className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-97"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-of-ethics",
        index: 96,
        },
        {
        id: "moral-teen-98",
        title: "Roleplay: Ethical Leader",
        description: "Act as leader choosing fair rules for all.",
        icon: <UserCheck className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-6 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-98"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-ethical-leader",
        index: 97,
        },
        {
        id: "moral-teen-99",
        title: "Reflex: True Hero",
        description: "Tap for 'Speak Truth', avoid 'Hide Wrong'.",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2-3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-99"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-true-hero",
        index: 98,
        },
        {
        id: "moral-teen-100",
        title: "Badge: Ethical Hero",
        description: "Complete 5 ethical dilemmas.",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-100"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-ethical-hero",
        index: 99,
        },

    ];

    return moralGamesTeen;
}
