import { Briefcase, Puzzle } from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGameIdsAdults = buildIds("ehe", "adults");

export const getEheAdultGames = (gameCompletionStatus) => {
    const eheAdultGames = [
        {
            id: "ehe-adults-1",
            title: "Career Is Not Just a Job",
            description:
                "Story: You work daily but feel your job is only for income. Do you focus on just the salary, or do you build long-term skills?",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "8 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-1"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/career-is-not-just-a-job",
            index: 0,
        },
        {
            id: "ehe-adults-2",
            title: "Puzzle: Skill vs Experience",
            description:
                "Match the situations: Understand why '5 years + no new skills' leads to career stagnation, while 'Continuous learning' drives faster promotion.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-2"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-skill-vs-experience",
            index: 1,
        },
        {
            id: "ehe-adults-3",
            title: "Reflex: Professional Discipline",
            description:
                "Story: You arrive late frequently but complete work. Tap for 'Discipline & Reliability', avoid 'Excuses' and 'Personal Mood'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-3"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-professional-discipline",
            index: 2,
        },
        {
            id: "ehe-adults-4",
            title: "Quiz: Lifelong Learning",
            description:
                "Scenario: You believe learning stops after a certain age. What is actually correct? Test your awareness on the importance of continuous skill development.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-4"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-lifelong-learning",
            index: 3,
        },
        {
            id: "ehe-adults-5",
            title: "Simulation: Slow Growth",
            description:
                "Story: Growth is slow in your current company. Choices: Blame management only / Stop working seriously / Improve skills and explore options.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-5"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-slow-growth",
            index: 4,
        },
        {
            id: "ehe-adults-6",
            title: "Debate: Reputation Matters",
            description:
                "Colleagues describe you as “inconsistent.” Does your reputation not matter, or does it affect promotions and trust? It affects promotions and trust.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-6"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-reputation-matters",
            index: 5,
        },
        {
            id: "ehe-adults-7",
            title: "Puzzle: Salary vs Skill",
            description:
                "Match the situations: Understand why 'Small salary growth + no learning' is an immediate risky focus, while 'Skill-building opportunities' are safer long-term.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-7"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-salary-vs-skill",
            index: 6,
        },
        {
            id: "ehe-adults-8",
            title: "Reflex: Job Switching",
            description:
                "Story: You change jobs every 6 months. Tap for 'Doubt about stability', avoid 'Strong credibility' and 'Higher respect'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-8"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-job-switching",
            index: 7,
        },
        {
            id: "ehe-adults-9",
            title: "Journal: Career Planning",
            description:
                "Scenario: You never defined a career direction. Write how it impacts your progression instead of clear advancement.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-9"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-career-planning",
            index: 8,
        },
        {
            id: "ehe-adults-10",
            title: "Badge: Career Foundation Ready",
            description:
                "Badge: Career Foundation Ready • Task: Make 5 correct professional discipline decisions. • Mechanic: Achievement • Reward: Badge – “Career Foundation Ready”",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            isBadgeGame: true,
            badgeName: 'Badge: Career Foundation Ready',
            badgeImage: '/badges/ehe/adult/Career-Foundation-Ready.png',
            completed: gameCompletionStatus["ehe-adults-10"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-career-foundation-ready",
            index: 9,
        },
        {
            id: "ehe-adults-11",
            title: "Story: Promotion Discussion",
            description:
                "Story: You have worked consistently for years but never discussed growth. Do you wait patiently or schedule a meeting to communicate goals? Communicate goals.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-11"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/promotion-discussion-story",
            index: 10,
        },
        {
            id: "ehe-adults-12",
            title: "Quiz: Appraisal Prep",
            description:
                "Story: Appraisal is tomorrow, and you haven't prepared an achievements list. What is the risk? Test your awareness on performance evaluations.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-12"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-appraisal-prep",
            index: 11,
        },
        {
            id: "ehe-adults-13",
            title: "Reflex: Initiative",
            description:
                "Story: A new project needs a leader. Tap for 'Take Calculated Initiative', avoid 'Wait for Assignment'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-13"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-initiative",
            index: 12,
        },
        {
            id: "ehe-adults-14",
            title: "Puzzle: Office Politics",
            description:
                "Match the situations: Understand why 'Office Politics' is a distraction and risk, while 'Neutrality & Performance' is a safe strategy.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-14"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-office-politics",
            index: 13,
        },
        {
            id: "ehe-adults-15",
            title: "Story: Skill Upgrade",
            description:
                "Story: A higher role requires a new technical certification. Do you ignore the requirement or invest time in the certification? Invest time.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-15"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/skill-upgrade-story",
            index: 14,
        },
        {
            id: "ehe-adults-16",
            title: "Debate: Leadership Trust",
            description:
                "As a manager facing project delays, is it better to publicly blame the team or provide structured guidance and accountability? Structured guidance.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-16"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-leadership-trust",
            index: 15,
        },
        {
            id: "ehe-adults-17",
            title: "Journal: Feedback",
            description:
                "Scenario: Senior management highlights a weakness in your performance. Write your plan for improvement rather than becoming defensive.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-17"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-feedback",
            index: 16,
        },
        {
            id: "ehe-adults-18",
            title: "Simulation: Salary Negotiation",
            description:
                "Story: You are offered a promotion with unclear compensation terms. Choices: Accept immediately / Reject emotionally / Clarify expectations.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-18"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-salary-negotiation",
            index: 17,
        },
        {
            id: "ehe-adults-19",
            title: "Reflex: Visibility",
            description:
                "Story: Tap for 'Share Contributions Professionally', avoid 'Stay Invisible' and 'Overstate Achievements'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-19"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-visibility",
            index: 18,
        },
        {
            id: "ehe-adults-20",
            title: "Badge: Career Growth Strategist",
            description:
                "Badge: Career Growth Strategist • Task: Make 5 correct career growth decisions in this module. • Mechanic: Achievement. • Reward: Badge “Career Growth Strategist”.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            isBadgeGame: true,
            badgeName: 'Badge: Career Growth Strategist',
            badgeImage: '/badges/ehe/adult/Career-Growth-Strategist.png',
            completed: gameCompletionStatus["ehe-adults-20"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-career-growth-strategist",
            index: 19,
        },
        {
            id: "ehe-adults-21",
            title: "Story: Industry Disruption",
            description:
                "Story: Technology changes are reducing demand in your current field. Do you ignore the changes or upgrade your skills proactively? Upgrade skills proactively.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-21"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/industry-disruption-story",
            index: 20,
        },
        {
            id: "ehe-adults-22",
            title: "Quiz: Layoff Signs",
            description:
                "Story: Company revenue declines and hiring freezes begin. What should you prepare? Test your awareness on reading warning signals.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-22"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-layoff-signs",
            index: 21,
        },
        {
            id: "ehe-adults-23",
            title: "Reflex: Financial Safety",
            description:
                "Story: Your household depends entirely on your single income. Tap for 'Emergency Fund Planning', avoid 'Lifestyle Expansion' and 'Ignoring Risk'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-23"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-financial-safety",
            index: 22,
        },
        {
            id: "ehe-adults-24",
            title: "Puzzle: Contract vs Permanent",
            description:
                "Match the roles to their characteristics: Understand why a 'Contract Role' brings higher pay but high risk, whereas a 'Permanent Role' brings stability and long-term benefits.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-24"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-contract-vs-permanent",
            index: 23,
        },
        {
            id: "ehe-adults-25",
            title: "Story: Burnout Risk",
            description:
                "Story: Long working hours are affecting your health and family time. Do you ignore your health or choose structured workload management? Structured workload management.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["ehe-adults-25"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/burnout-risk-story",
            index: 24,
        },
        {
            id: "ehe-adults-26",
            title: "Debate: Reputation Damage",
            description:
                "If a professional mistake affects client trust, is it better to deny it or make a transparent correction? Transparent correction builds trust.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-26"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-reputation-damage",
            index: 25,
        },
        {
            id: "ehe-adults-27",
            title: "Journal: Career Break Planning",
            description:
                "Scenario: You plan a 6-month career break. Write your financial and skill plan before taking the break.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-27"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-career-break",
            index: 26,
        },
        {
            id: "ehe-adults-28",
            title: "Simulation: Relocation Decision",
            description:
                "Story: A role in another city offers higher growth but a much higher cost of living. Options: (a) Look at salary only (b) Calculate net savings and stability.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-28"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-relocation-decision",
            index: 27,
        },
        {
            id: "ehe-adults-29",
            title: "Reflex: Skill Check",
            description:
                "Story: Your current technical skill is slowly becoming outdated. Tap for 'Continuous Learning', avoid 'Relying on Experience Alone'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-29"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-skill-check",
            index: 28,
        },
        {
            id: "ehe-adults-30",
            title: "Badge: Career Stability Guardian",
            description:
                "Badge: Career Stability Guardian • Task: Make 5 correct risk-management decisions in this module. • Mechanic: Achievement. • Reward: Badge “Career Stability Guardian”.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Career Stability Guardian',
            badgeImage: '/badges/ehe/adult/Career-Stability-Guardian.png',
            completed: gameCompletionStatus["ehe-adults-30"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-career-stability-guardian",
            index: 29,
        },
        {
            id: "ehe-adults-31",
            title: "Story: Leadership Transition",
            description:
                "Story: You are promoted from team member to team manager. What changes the most? Do you focus only on the salary or take responsibility for team outcomes? Responsibility for team outcomes.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-31"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/leadership-transition-story",
            index: 30,
        },
        {
            id: "ehe-adults-32",
            title: "Quiz: Delegation",
            description:
                "Story: You attempt to handle all the work personally instead of delegating to your team. What is the risk? Test your delegation and leadership skills.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-32"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-delegation",
            index: 31,
        },
        {
            id: "ehe-adults-33",
            title: "Reflex: Conflict Resolution",
            description:
                "Story: Two senior employees disagree publicly. Tap for 'Structured & Neutral Resolution', avoid 'Taking Sides' and 'Escalating Conflict'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-33"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-conflict-resolution",
            index: 32,
        },
        {
            id: "ehe-adults-34",
            title: "Puzzle: Accountability Culture",
            description:
                "Story: Match 'Project Fails' to 'Accept Accountability & Improve', and 'Hide Issue' to 'Deny Responsibility (Wrong)' to understand workplace accountability.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-34"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-accountability-culture",
            index: 33,
        },
        {
            id: "ehe-adults-35",
            title: "Simulation: Under Pressure",
            description:
                "Simulation: Under Pressure • Story: You must make a time-sensitive business decision. Options: Emotional reaction / Delay indefinitely / Structured evaluation of impact. Correct = Structured evaluation. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-35"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-under-pressure",
            index: 34,
        },
        {
            id: "ehe-adults-36",
            title: "Debate: Ethical Leadership",
            description:
                "Debate: Ethical Leadership • Topic: A shortcut increases profit but reduces compliance transparency. Should you accept the shortcut to show fast results? No, maintain compliance integrity. • Mechanic: Debate.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-36"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-ethical-leadership",
            index: 35,
        },
        {
            id: "ehe-adults-37",
            title: "Journal: Fairness",
            description:
                "Journal of Fairness • Task: Write: “When evaluating employees for promotion, I will ensure fairness by focusing on ___ rather than personal preference.” • Mechanic: Journal.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-37"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-fairness",
            index: 36,
        },
        {
            id: "ehe-adults-38",
            title: "Story: Restructuring",
            description:
                "Story: Company restructuring creates uncertainty in the office. Do you stay silent or provide transparent and clear updates? Transparent and clear updates.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-38"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/restructuring-story",
            index: 37,
        },
        {
            id: "ehe-adults-39",
            title: "Reflex: Credibility",
            description:
                "Story: Your leadership style is perceived by the team as inconsistent. Tap for 'Review Behavior & Adjust', avoid 'Blame Subordinates' and 'Defend Aggressively'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-39"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-credibility",
            index: 38,
        },
        {
            id: "ehe-adults-40",
            title: "Badge: Responsible Leader",
            description:
                "Badge: Responsible Leader • Task: Make 7 correct leadership decisions in this module. • Mechanic: Achievement. • Reward: Badge “Responsible Leader”.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Responsible Leader',
            badgeImage: '/badges/ehe/adult/Responsible-Leader.png',
            completed: gameCompletionStatus["ehe-adults-40"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-responsible-leader",
            index: 39,
        },
        {
            id: "ehe-adults-41",
            title: "Story: Freelance vs Business",
            description:
                "Story: You earn money occasionally through small freelance work. To build a true business, do you rely on occasional income or build a consistent system? Consistent system.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-41"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/freelance-vs-business-story",
            index: 40,
        },
        {
            id: "ehe-adults-42",
            title: "Quiz: Business Planning",
            description:
                "Story: You want to start a shop. What is the most critical step before starting? Test your business planning acumen.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-42"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-business-planning",
            index: 41,
        },
        {
            id: "ehe-adults-43",
            title: "Reflex: Capital Management",
            description:
                "Story: You have savings to invest in a new business. Tap for 'Calculated Investment', avoid 'Invest All Savings at Once'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-43"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-capital-management",
            index: 42,
        },
        {
            id: "ehe-adults-44",
            title: "Puzzle: Market Research",
            description:
                "Story: Match 'Low Demand Area' to 'Financial Risk', and 'Demand Analysis' to 'Smart Planning' to understand business strategy.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-44"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-market-research",
            index: 43,
        },
        {
            id: "ehe-adults-45",
            title: "Story: Pricing Strategy",
            description:
                "Story: You set your product price lower than the cost to attract customers. Will this lead to stable growth or financial loss long-term? Financial loss.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-45"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/pricing-strategy-story",
            index: 44,
        },
        {
            id: "ehe-adults-46",
            title: "Debate: Cash vs Revenue",
            description:
                "Debate: Cash vs Revenue • Topic: Your sales are strong, but cash reserves are low. Should you focus only on revenue or manage your cash flow carefully? Manage cash flow. • Mechanic: Debate",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-46"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-cash-vs-revenue",
            index: 45,
        },
        {
            id: "ehe-adults-47",
            title: "Simulation: Business Loan",
            description:
                "Simulation: Business Loan • Story: A high-interest loan is offered for quick expansion. Choices: Accept immediately / Evaluate repayment capacity / Ask friends. Correct = Evaluate repayment capacity. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-47"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-business-loan",
            index: 46,
        },
        {
            id: "ehe-adults-48",
            title: "Reflex: Risk Buffer",
            description:
                "Story: A slow month hits your business and sales drop. Tap for 'Emergency Reserve Fund', avoid 'Panic Reaction' and 'No Preparation'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-48"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-risk-buffer",
            index: 47,
        },
        {
            id: "ehe-adults-49",
            title: "Journal: Compliance",
            description:
                "Journal of Compliance • Task: Write: \"If I skip basic business registration to save money, the long-term risk for my business will be ___.\" • Mechanic: Journal",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["ehe-adults-49"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-compliance",
            index: 48,
        },
        {
            id: "ehe-adults-50",
            title: "Badge: Entrepreneurship Foundation Ready",
            description:
                "Badge: Entrepreneurship Foundation Ready • Task: Make 5 correct foundational business decisions. • Mechanic: Achievement • Reward: Badge “Entrepreneurship Foundation Ready”",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Entrepreneurship Foundation Ready',
            badgeImage: '/badges/ehe/adult/Entrepreneurship-Foundation-Ready.png',
            completed: gameCompletionStatus["ehe-adults-50"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-entrepreneurship-foundation-ready",
            index: 49,
        },
        {
            id: "ehe-adults-51",
            title: "Simulation: Rapid Expansion",
            description:
                "Simulation: Rapid Expansion • Story: Your startup has been profitable for 3 months. You have funds to expand. Choices: Open 2 branches instantly / Evaluate operational stability first. Correct = Evaluate stability. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-51"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-rapid-expansion",
            index: 50,
        },
        {
            id: "ehe-adults-52",
            title: "Reflex: Hiring",
            description:
                "Story: Workload is increasing, and you need staff. Tap for 'Role clarity & skill', avoid 'Hiring friends only'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-52"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-hiring",
            index: 51,
        },
        {
            id: "ehe-adults-53",
            title: "Puzzle of Customers",
            description:
                "Story: Match 'New Customers' to 'Initial Sales' and 'Repeat Customers' to 'Long-term Stability' to understand customer relationships.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-53"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-of-customers",
            index: 52,
        },
        {
            id: "ehe-adults-54",
            title: "Story: Profit Reinvestment",
            description:
                "Story: Your business earns its first major profit. Do you spend it all personally or reinvest in operations? Reinvest in operations.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-54"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/profit-reinvestment-story",
            index: 53,
        },
        {
            id: "ehe-adults-55",
            title: "Debate: Price War",
            description:
                "Debate: Price War • Topic: A competitor drops their prices significantly. Should you reduce your prices below cost or improve value and service differentiation? Improve value. • Mechanic: Debate",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-55"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-price-war",
            index: 54,
        },
        {
            id: "ehe-adults-56",
            title: "Quiz: Business Systems",
            description:
                "Story: Operations depend entirely on your personal presence. What limits your growth? Test your knowledge on system automation.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-56"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-business-systems",
            index: 55,
        },
        {
            id: "ehe-adults-57",
            title: "Reflex: Digital Presence",
            description:
                "Story: Your business has no online visibility. Tap for 'Build Digital Reach', avoid 'Stay Completely Offline'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-57"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-digital-presence",
            index: 56,
        },
        {
            id: "ehe-adults-58",
            title: "Puzzle of Partnerships",
            description:
                "Story: Match 'Verbal Promises Only' to 'Legal Risk' and 'Mutual Value & Legal Clarity' to 'Safe Partnership' to understand business collaborations.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-58"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-of-partnerships",
            index: 57,
        },
        {
            id: "ehe-adults-59",
            title: "Simulation: Inventory Management",
            description:
                "Simulation: Inventory Management • Story: You feel optimistic about seasonal sales. Choices: Over-purchase stock immediately / Evaluate cash blockage and storage loss. Correct = Evaluate cash blockage. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-59"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-inventory-management",
            index: 58,
        },
        {
            id: "ehe-adults-60",
            title: "Badge: Strategic Business Builder",
            description:
                "Badge: Strategic Business Builder • Task: Make 7 correct business expansion decisions in this module. • Mechanic: Achievement • Reward: Badge \"Strategic Business Builder\"",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            isBadgeGame: true,
            badgeName: 'Badge: Strategic Business Builder',
            badgeImage: '/badges/ehe/adult/Strategic-Business-Builder.png',
            completed: gameCompletionStatus["ehe-adults-60"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-strategic-business-builder",
            index: 59,
        },
        {
            id: "ehe-adults-61",
            title: "Story: Mixed Funds",
            description:
                "Story: You use the exact same bank account for both personal groceries and business expenses. Does this give you better control, or does it lead to financial confusion and tax complications? Financial confusion.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-61"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/mixed-funds-story",
            index: 60,
        },
        {
            id: "ehe-adults-62",
            title: "Reflex: Tax Deadlines",
            description:
                "Story: Tap for 'File Taxes on Time', avoid 'Delay Deadlines' and 'Pay Penalties'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-62"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-tax-deadlines",
            index: 61,
        },
        {
            id: "ehe-adults-63",
            title: "Quiz: Client Reliance",
            description:
                "Story: 70% of your business revenue comes from a single customer. What is the biggest risk here? Test your knowledge on client concentration.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-63"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-client-reliance",
            index: 62,
        },
        {
            id: "ehe-adults-64",
            title: "Puzzle of Agreements",
            description:
                "Story: Match 'Verbal Deal' to 'Legal Disputes & Misunderstandings' and 'Written Contract' to 'Clear Expectations & Safety' to understand contracts.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-64"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-of-agreements",
            index: 63,
        },
        {
            id: "ehe-adults-65",
            title: "Simulation: Expense Tracking",
            description:
                "Simulation: Expense Tracking • Story: You need to determine if your business is truly profitable. Choices: Look at bank account balance / Review a P&L statement. Correct = Review P&L statement. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-65"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-expense-tracking",
            index: 64,
        },
        {
            id: "ehe-adults-66",
            title: "Debate: Insurance Cost",
            description:
                "Debate: Insurance Cost • Topic: You bought expensive machinery for your business. Should you skip insurance to save money, or pay the premium to prevent major financial loss during damage? Pay the premium to prevent major loss. • Mechanic: Debate",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-66"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-insurance-cost",
            index: 65,
        },
        {
            id: "ehe-adults-67",
            title: "Reflex: Loan Management",
            description:
                "Story: You face a short-term cash gap. Tap for 'Evaluate Cash Flow', avoid 'Rapidly Accumulate Small Loans' and 'Increase Debt Burden'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-67"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-loan-management",
            index: 66,
        },
        {
            id: "ehe-adults-68",
            title: "Journal: Record Keeping",
            description:
                "Journal of Record Keeping • Task: Write: \"To avoid audit complications and loss of clarity, I will manage my invoices and receipts by ___.\" • Mechanic: Journal",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-68"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-record-keeping",
            index: 67,
        },
        {
            id: "ehe-adults-69",
            title: "Story: Compliance Update",
            description:
                "Story: Regulatory rules in your industry just changed. Do you ignore them because your old processes work fine, or update your processes to avoid legal risk? Update processes.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-69"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/compliance-update-story",
            index: 68,
        },
        {
            id: "ehe-adults-70",
            title: "Badge: Business Stability Guardian",
            description:
                "Badge: Business Stability Guardian • Task: Make 7 correct financial control and compliance decisions in this module. • Mechanic: Achievement • Reward: Badge \"Business Stability Guardian\"",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            isBadgeGame: true,
            badgeName: 'Badge: Business Stability Guardian',
            badgeImage: '/badges/ehe/adult/Business-Stability-Guardian.png',
            completed: gameCompletionStatus["ehe-adults-70"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-business-stability-guardian",
            index: 69,
        },
        {
            id: "ehe-adults-71",
            title: "Puzzle of Delegation",
            description:
                "Story: Match 'Founder approves everything' to 'Limits Growth' and 'Leadership Delegation' to 'Scalable Business' to understand business scaling.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-71"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-of-delegation",
            index: 70,
        },
        {
            id: "ehe-adults-72",
            title: "Story: Succession Planning",
            description:
                "Story: Your business operates successfully, but no successor is trained. Do you ignore this or prepare to avoid business disruption during your absence? Prepare to avoid disruption.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-72"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/succession-planning-story",
            index: 71,
        },
        {
            id: "ehe-adults-73",
            title: "Quiz: Employee Retention",
            description:
                "Quiz on Employee Retention • Story: Skilled employees leave your company frequently. What should you review? (a) Employee replaceability, (b) Work culture and growth opportunities. Correct = Work culture and growth opportunities. • Mechanic: Quiz",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-73"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-employee-retention",
            index: 72,
        },
        {
            id: "ehe-adults-74",
            title: "Debate: Brand Reputation",
            description:
                "Debate: Brand Reputation • Topic: Customers question the transparency of your product claims. Should you use marketing exaggeration to hide it, or use honest and clear communication? Honest and clear communication. • Mechanic: Debate",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-74"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-brand-reputation",
            index: 73,
        },
        {
            id: "ehe-adults-75",
            title: "Reflex: Sustainability",
            description:
                "Story: Your production methods create avoidable waste. Tap for 'Improve Resource Efficiency', avoid 'Ignore Impact' and 'Focus Only on Profit'.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["ehe-adults-75"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-sustainability",
            index: 74,
        },
        {
            id: "ehe-adults-76",
            title: "Simulation: Diversification",
            description:
                "Simulation: Diversification • Story: Your revenue depends entirely on one product line. A market shift happens. Choices: Stick to single product / Short-term discounting / Build diversified revenue streams. Correct = Build diversified revenue streams. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-76"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-diversification",
            index: 75,
        },
        {
            id: "ehe-adults-77",
            title: "Story: Leadership Empowerment",
            description:
                "Story: Managers under you lack decision-making authority. Do you maintain centralized control or invest in leadership training and empowerment? Leadership training and empowerment.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-77"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/leadership-empowerment-story",
            index: 76,
        },
        {
            id: "ehe-adults-78",
            title: "Journal: Vision",
            description:
                "Journal of Vision • Task: Write: \"To avoid directionless expansion, my defined 5-year plan for the business will focus on ___.\" • Mechanic: Journal",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-78"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-vision",
            index: 77,
        },
        {
            id: "ehe-adults-79",
            title: "Quiz: Crisis",
            description:
                "Quiz on Crisis • Story: An unexpected economic slowdown impacts revenue. What ensures survival? (a) Panic reaction, (b) Reserve planning and cost control, (c) Blaming the market. Correct = Reserve planning and cost control. • Mechanic: Quiz",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-79"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-crisis",
            index: 78,
        },
        {
            id: "ehe-adults-80",
            title: "Badge: Sustainable Business Leader",
            description:
                "Badge: Sustainable Business Leader • Task: Make 5 correct long-term sustainability decisions in this module. • Mechanic: Achievement • Reward: Badge \"Sustainable Business Leader\"",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Sustainable Business Leader',
            badgeImage: '/badges/ehe/adult/Sustainable-Business-Leader.png',
            completed: gameCompletionStatus["ehe-adults-80"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-sustainable-business-leader",
            index: 79,
        },
        {
            id: "ehe-adults-81",
            title: "Story: Degree Alignment",
            description:
                "Story: You enroll in an expensive degree program without thinking about your future job. Do you expect an automatic promotion or realize it might lead to career misalignment? Realize career misalignment.",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-81"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/degree-alignment-story",
            index: 80,
        },
        {
            id: "ehe-adults-82",
            title: "Puzzle: Certification Value",
            description:
                "Match the situations: Understand why 'Brand Name Only' is 'Vanity', while 'Relevance to Career Demand' brings 'True Value'.",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-82"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-certification-value",
            index: 81,
        },
        {
            id: "ehe-adults-83",
            title: "Simulation: Education Loan",
            description:
                "Simulation: Education Loan • Story: You are offered a massive education loan for higher studies. Choices: Accept for the social prestige / Ignore the cost / Calculate Return on Investment (ROI) & repayment capacity. Correct = Calculate ROI. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-83"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-education-loan",
            index: 82,
        },
        {
            id: "ehe-adults-84",
            title: "Reflex: Work & Study",
            description:
                "Reflex Work & Study • Story: You plan to pursue part-time education while employed. Tap for \"Structured Schedule & Discipline\", avoid \"Ignoring Workload\" and \"No Time Planning\". • Mechanic: Reflex",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-84"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-work-and-study",
            index: 83,
        },
        {
            id: "ehe-adults-85",
            title: "Debate: Overseas Education",
            description:
                "Debate: Overseas Education • Topic: You want to study abroad. Should you make the decision based on social prestige and emotional excitement, or carefully evaluate the long-term financial impact and career value? Evaluate financial impact. • Mechanic: Debate",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-85"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-overseas-education",
            index: 84,
        },
        {
            id: "ehe-adults-86",
            title: "Story: Full-Time Study",
            description:
                "Full-Time Study Story • Story: You want to leave your stable job to study full-time. Do you resign immediately or build a financial buffer and review the career impact first? Build a financial buffer. • Mechanic: Story Choice",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-86"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/full-time-study-story",
            index: 85,
        },
        {
            id: "ehe-adults-87",
            title: "Quiz: Lifelong Learning Advance",
            description:
                "Quiz on Lifelong Learning advance • Story: You believe your college degree is enough for your entire life. What actually ensures career longevity? (A) Your current job title, (B) Continuous skill updating. Correct = Continuous skill updating. • Mechanic: Quiz",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-87"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-lifelong-learning-advance",
            index: 86,
        },
        {
            id: "ehe-adults-88",
            title: "Puzzle of Institutions",
            description:
                "Puzzle of Institutions • Story: Match “Institution Advertising Marketing” and “Faculty Quality & Curriculum Real Learning Outcomes.” • Mechanic: Puzzle",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-88"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-of-institutions",
            index: 87,
        },
        {
            id: "ehe-adults-89",
            title: "Journal of Enrollment",
            description:
                "Journal of Enrollment • Task: Write: \"Before I enroll in a new advanced course, I must research the final course outcomes to avoid a mismatch between ___ and ___.\" • Mechanic: Journal",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-89"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-enrollment",
            index: 88,
        },
        {
            id: "ehe-adults-90",
            title: "Badge: Education Strategy Planner",
            description:
                "Badge: Education Strategy Planner • Task: Make 7 correct education planning decisions in this module. • Mechanic: Achievement • Reward: Badge \"Education Strategy Planner\"",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Education Strategy Planner',
            badgeImage: '/badges/ehe/adult/Education-Strategy-Planner.png',
            completed: gameCompletionStatus["ehe-adults-90"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-education-strategy-planner",
            index: 89,
        },
        {
            id: "ehe-adults-91",
            title: "Quiz: Mid-Career Specialisation",
            description:
                "Quiz on Mid-Career Specialisation • Story: You consider specialising in a niche field after 10 years of general experience. What should guide your decision? (a) Instagram trends and popularity, (b) Market demand and personal capability. Correct = Market demand and personal capability. • Mechanic: Quiz",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-91"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/quiz-mid-career-specialisation",
            index: 90,
        },
        {
            id: "ehe-adults-92",
            title: "Simulation: Switching Industries",
            description:
                "Simulation: Switching Industries • Story: You want to change your industry by pursuing a new qualification. Choices: Make an emotional impulse jump / Expect an immediate salary hike / Evaluate the skill gap and transition timeline. Correct = Evaluate the skill gap and transition timeline. • Mechanic: Simulation",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-92"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/simulation-switching-industries",
            index: 91,
        },
        {
            id: "ehe-adults-93",
            title: "Puzzle: Short vs Long Course",
            description:
                "Puzzle: Short vs Long Course • Story: Match \"Brand Popularity Just Hype\" and \"Career Objective & ROI Right Course Choice.\" • Mechanic: Puzzle",
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-93"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/puzzle-short-vs-long-course",
            index: 92,
        },
        {
            id: "ehe-adults-94",
            title: "Reflex: Certification",
            description:
                "Reflex Certification • Story: You complete multiple new certifications. Tap for \"Practical Implementation at Work\", avoid \"Just for Certificate Display\" and \"No Application\". • Mechanic: Reflex",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-94"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-certification",
            index: 93,
        },
        {
            id: "ehe-adults-95",
            title: "Debate: Employer Sponsorship",
            description:
                "Debate: Employer Sponsorship • Topic: Your employer offers to sponsor your advanced study. Should you accept blindly for the social prestige, or carefully review the service bond and long-term commitment required? Review service bond and commitment. • Mechanic: Debate",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-95"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/debate-employer-sponsorship",
            index: 94,
        },
        {
            id: "ehe-adults-96",
            title: "Story: Time Investment",
            description:
                "Time Investment Story • Story: Advanced education requires weekend and evening study alongside your job. Do you just try to manage without a schedule, or create a structured time allocation plan? Structured time allocation plan. • Mechanic: Story Choice",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-96"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/time-investment-story",
            index: 95,
        },
        {
            id: "ehe-adults-97",
            title: "Journal of Education ROI",
            description:
                "Journal of Education ROI • Task: Write: \"Before paying a high tuition fee for an advanced degree, I will calculate my expected return on education by looking at ___.\" • Mechanic: Journal",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-97"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/journal-of-education-roi",
            index: 96,
        },
        {
            id: "ehe-adults-98",
            title: "Reflex: Adaptability",
            description:
                "Reflex Adaptability • Story: Learning a brand new technology feels difficult and overwhelming. Tap for \"Gradual Adaptation & Persistence\", avoid \"Avoiding Change\" and \"Complaining\". • Mechanic: Reflex",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-98"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/reflex-adaptability",
            index: 97,
        },
        {
            id: "ehe-adults-99",
            title: "Story: Course Completion",
            description:
                "Course Completion Story • Story: Halfway through your advanced course, your motivation completely declines. Do you withdraw and blame your workload, or create a consistent completion plan to push through? Consistent completion plan. • Mechanic: Story Choice",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["ehe-adults-99"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/course-completion-story",
            index: 98,
        },
        {
            id: "ehe-adults-100",
            title: "Badge: Higher Education Master",
            description:
                "Badge: Higher Education Master • Task: Make 5 correct advanced education and transition decisions in this module. • Mechanic: Achievement • Reward: Badge \"Higher Education Master\"",
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "5 min",
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Higher Education Master',
            badgeImage: '/badges/ehe/adult/Higher-Education-Master.png',
            completed: gameCompletionStatus["ehe-adults-100"] || false,
            isSpecial: true,
            reflective: false,
            path: "/student/ehe/adult/badge-higher-education-master",
            index: 99,
        },
    ];

    return eheAdultGames;
};

