import { Briefcase, Puzzle, Zap } from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGameIdsYoungAdult = buildIds("ehe", "young-adult");

export const getEheYoungAdultGames = (gameCompletionStatus) => {
  const eheYoungAdultGames = [
    {
      id: "ehe-young-adult-1",
      title: "Job vs Career",
      description:
        "Understand the mindset difference between viewing work as a job versus building a career through strategic questioning.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "8 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-1"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/job-vs-career",
      index: 0,
    },
    {
      id: "ehe-young-adult-2",
      title: "Puzzle: Resume Preparation",
      description:
        "Match resume traits to their real-world outcomes. Learn how resume quality directly impacts your professional credibility and opportunity visibility.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "6 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-2"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-resume-prep",
      index: 1,
    },
    {
      id: "ehe-young-adult-3",
      title: "Reflex: Internship",
      description:
        "An unpaid internship offers practical exposure. Tap for 'Skill development opportunity', avoid 'Salary only' and 'Social status'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-3"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-internship",
      index: 2,
    },
    {
      id: "ehe-young-adult-4",
      title: "Quiz: Skill Development",
      description:
        "Scenario: You complete a degree but learn no additional practical skills. Test your awareness on the impact of practical skills.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-4"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-skill-development",
      index: 3,
    },
    {
      id: "ehe-young-adult-5",
      title: "Debate: Punctuality",
      description:
        "You arrive late frequently during your internship. Does this just show a casual attitude, or does it severely impact your professional discipline and long-term growth?",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-5"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-punctuality",
      index: 4,
    },
    {
      id: "ehe-young-adult-6",
      title: "Simulation: Learning After Graduation",
      description:
        "Scenario: You graduate and get a job. Choices: Stop learning completely / Wait for opportunities / Continue learning new skills.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-6"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-learning-after-graduation",
      index: 5,
    },
    {
      id: "ehe-young-adult-7",
      title: "Journal: Preparation",
      description:
        "Scenario: Friends get jobs faster than you. Write your preparation strategy instead of blaming the system.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-7"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-preparation",
      index: 6,
    },
    {
      id: "ehe-young-adult-8",
      title: "Reflex: First Salary",
      description:
        "Scenario: You receive your first income. Tap for 'Allocate savings and expenses', avoid 'Spend immediately' and 'Borrow for lifestyle'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-8"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-first-salary",
      index: 7,
    },
    {
      id: "ehe-young-adult-9",
      title: "Story: Professional Behaviour",
      description:
        "Scenario: You are tempted to post negative comments about your employer online. Do you post it for social popularity or hold back to protect your digital reputation? Hold back.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-9"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-professional-behaviour",
      index: 8,
    },
    {
      id: "ehe-young-adult-10",
      title: "Badge: Young Career Starter",
      description:
        "Career Foundation Checkpoint • Task: Make 5 correct early-career decisions. • Mechanic: Achievement • Outcome Message: You understand structured career foundations and professional discipline. • Reward: Badge – “Young Career Starter”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "10 min",
      coins: 5,
      xp: 10,
      isBadgeGame: true,
      badgeName: 'Badge: Young Career Starter',
      badgeImage: '/badges/ehe/young-adult/Young-Career-Starter.png',
      completed: gameCompletionStatus["ehe-young-adult-10"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-career-starter",
      index: 9,
    },
    {
      id: "ehe-young-adult-11",
      title: "Reflex: Initiative",
      description:
        "Scenario: You complete assigned work but never volunteer for extra responsibility. Tap for 'Take Initiative', avoid 'Stay Unnoticed' and 'Complain about Workload'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-11"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-initiative",
      index: 10,
    },
    {
      id: "ehe-young-adult-12",
      title: "Story: Feedback Handling",
      description:
        "Scenario: Your manager highlights areas of improvement. Do you react defensively or implement an improvement plan? Implement improvement plan.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-12"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-feedback-handling",
      index: 11,
    },
    {
      id: "ehe-young-adult-13",
      title: "Quiz: Adaptability",
      description:
        "Scenario: Your company adopts new software systems. What protects your relevance? Test your awareness on adaptability.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-13"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-adaptability",
      index: 12,
    },
    {
      id: "ehe-young-adult-14",
      title: "Puzzle: Visibility of Work",
      description:
        "Match workplace behaviors to their real-world outcomes. Discover why silently working hard often goes unnoticed, and how to professionally share results.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-14"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-visibility-work",
      index: 13,
    },
    {
      id: "ehe-young-adult-15",
      title: "Simulation: Salary Negotiation",
      description:
        "Scenario: You receive a job offer with an unclear salary structure. Choices: Accept immediately / Reject emotionally / Clarify terms professionally.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-15"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-salary-negotiation",
      index: 14,
    },
    {
      id: "ehe-young-adult-16",
      title: "Debate: Workplace Reputation",
      description:
        "Colleagues describe you as inconsistent. Should you try to fix this by frequent job switching or by demonstrating consistent performance? Consistent performance.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-16"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-reputation",
      index: 15,
    },
    {
      id: "ehe-young-adult-17",
      title: "Journal: Upskilling",
      description:
        "Scenario: A higher role requires additional certification. Write your upskilling strategy instead of waiting for an automatic promotion.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-17"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-upskilling",
      index: 16,
    },
    {
      id: "ehe-young-adult-18",
      title: "Story: Office Competition",
      description:
        "Scenario: Peers compete for limited promotion roles. Do you undermine others or focus on improving your own performance? Improve own performance.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-18"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-office-competition",
      index: 17,
    },
    {
      id: "ehe-young-adult-19",
      title: "Reflex: Early Leadership",
      description:
        "Scenario: You are asked to lead a small project. Tap for 'Accept and Prepare', avoid 'Decline due to fear' and 'Delegate everything'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-19"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-early-leadership",
      index: 18,
    },
    {
      id: "ehe-young-adult-20",
      title: "Badge: Emerging Professional",
      description:
        "Early Career Growth Checkpoint • Task: Make 5 correct growth and promotion decisions. • Mechanic: Achievement • Outcome Message: You understand structured early-career advancement strategy. • Reward: Badge – “Emerging Professional”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "10 min",
      coins: 5,
      xp: 10,
       isBadgeGame: true,
      badgeName: 'Badge: Emerging Professiona',
      badgeImage: '/badges/ehe/young-adult/Emerging-Professional.png',
      completed: gameCompletionStatus["ehe-young-adult-20"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-emerging-professional",
      index: 19,
    },
    {
      id: "ehe-young-adult-21",
      title: "Puzzle: Short-Term Job Switching",
      description:
        "Match workplace behaviors to their career impacts. Understand why changing jobs every 5 months is perceived as instability and why staying to build skills creates strong credibility.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-21"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-short-term-job-switching",
      index: 20,
    },
    {
      id: "ehe-young-adult-22",
      title: "Story: Industry Change Awareness",
      description:
        "Scenario: Your field is increasingly affected by automation. Do you ignore the trends or start learning future-ready skills? Learn future-ready skills.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-22"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-industry-change-awareness",
      index: 21,
    },
    {
      id: "ehe-young-adult-23",
      title: "Reflex: Financial Safety",
      description:
        "Scenario: You rely fully on your monthly salary with zero savings. Tap for 'Build Emergency Funds', avoid 'Financial Vulnerability' and 'Higher Lifestyle Spending'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-23"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-financial-safety",
      index: 22,
    },
    {
      id: "ehe-young-adult-24",
      title: "Simulation: Contract Role Decision",
      description:
        "Scenario: You receive a short-term contract job with higher pay but absolutely no benefits. Choices: Look at salary only / Ask peers for opinions / Evaluate long-term stability and future prospects.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-24"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-contract-role-decision",
      index: 23,
    },
    {
      id: "ehe-young-adult-25",
      title: "Journal: Skill Gaps",
      description:
        "Scenario: Your job requires certain software skills you do not fully possess. Write your strategy to bridge this gap instead of hiding it.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 5,
      xp: 10,
      completed: gameCompletionStatus["ehe-young-adult-25"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-skill-gaps",
      index: 24,
    },
    {
      id: "ehe-young-adult-26",
      title: "Debate: Workplace Behaviour",
      description:
        "You are invited to join in on daily office gossip. Is this just harmless fun, or does it cause severe reputation damage over time? It causes reputation damage.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-26"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-workplace-behaviour",
      index: 25,
    },
    {
      id: "ehe-young-adult-27",
      title: "Quiz: Early Burnout",
      description:
        "Scenario: You work excessive hours without any rest to prove yourself. What actually ensures long-term sustainability? Test your awareness.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-27"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-early-burnout",
      index: 26,
    },
    {
      id: "ehe-young-adult-28",
      title: "Story: Career Direction",
      description:
        "Scenario: You accept random roles without any long-term planning. Do you achieve a structured progression or end up with a random, confusing career path? Random career path.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-28"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-career-direction",
      index: 27,
    },
    {
      id: "ehe-young-adult-29",
      title: "Reflex: Professional Documentation",
      description:
        "Scenario: You need to keep track of your wins. Tap for 'Documented Performance & Certifications', avoid 'No Records' and 'Reduced Promotion Readiness'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-29"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-professional-documentation",
      index: 28,
    },
    {
      id: "ehe-young-adult-30",
      title: "Badge: Career Stability Aware",
      description:
        "Career Stability Checkpoint • Task: Make 5 correct stability and risk-management decisions. • Mechanic: Achievement • Outcome Message: You understand early-career protection and professional stability. • Reward: Badge – “Career Stability Aware”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
       isBadgeGame: true,
      badgeName: 'Badge: Career Stability Aware',
      badgeImage: '/badges/ehe/young-adult/Career-Stability-Aware.png',
      completed: gameCompletionStatus["ehe-young-adult-30"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-career-stability-aware",
      index: 29,
    },
    {
      id: "ehe-young-adult-31",
      title: "Story: Business Idea Excitement",
      description:
        "Scenario: You have an idea and want to start immediately. Do you invest all your savings right away, or validate the market demand first? Validate demand.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-31"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-business-idea-excitement",
      index: 30,
    },
    {
      id: "ehe-young-adult-32",
      title: "Puzzle: Passion vs Demand",
      description:
        "Understand market viability. Match behaviors to outcomes, such as why passion alone carries a high risk of low sales compared to thorough market demand analysis.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-32"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-passion-vs-demand",
      index: 31,
    },
    {
      id: "ehe-young-adult-33",
      title: "Reflex: Startup Capital",
      description:
        "Scenario: You need funds to start your business. Tap for 'Separate & Planned Capital', avoid 'Using Education Loan Money' and 'Financial Instability'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-33"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-startup-capital",
      index: 32,
    },
    {
      id: "ehe-young-adult-34",
      title: "Simulation: Pricing Strategy",
      description:
        "Scenario: You are ready to price your product. Choices: Guess a random price / Focus only on brand strength / Calculate production cost first.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-34"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-pricing-strategy",
      index: 33,
    },
    {
      id: "ehe-young-adult-35",
      title: "Quiz: Partner Selection",
      description:
        "Scenario: You choose a business partner based only on friendship. What else MUST be evaluated? Test your awareness on evaluating partnerships.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-35"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-partner-selection",
      index: 34,
    },
    {
      id: "ehe-young-adult-36",
      title: "Debate: Legal Registration",
      description:
        "You want to avoid business registration to save money. Is this a smart early-stage hack, or does it create long-term legal risk that harms trust? It creates legal risk.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-36"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-legal-registration",
      index: 35,
    },
    {
      id: "ehe-young-adult-37",
      title: "Story: Handling Customer Feedback",
      description:
        "Scenario: Your very first customers give you negative feedback. Do you ignore their complaints or improve the product based on what they said? Improve the product.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-37"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-handling-customer-feedback",
      index: 36,
    },
    {
      id: "ehe-young-adult-38",
      title: "Reflex: Social Media Business",
      description:
        "Scenario: You post online to get sales. Tap for 'Product Quality & Service', avoid 'Just Viral Content' and 'Only Likes'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-38"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-social-media-business",
      index: 37,
    },
    {
      id: "ehe-young-adult-39",
      title: "Journal: Record Keeping",
      description:
        "Scenario: You realize you haven't been tracking daily expenses. Write your strategy to maintain accurate records and avoid financial confusion.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-39"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-record-keeping",
      index: 38,
    },
    {
      id: "ehe-young-adult-40",
      title: "Badge: Startup Beginner Ready",
      description:
        "Startup Foundation Checkpoint • Task: Make 5 correct startup foundation decisions. • Mechanic: Achievement • Outcome Message: You understand structured startup basics and risk awareness. • Reward: Badge – “Startup Beginner Ready”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "10 min",
      coins: 10,
      xp: 20,
       isBadgeGame: true,
      badgeName: 'Badge: Startup Beginner Ready',
      badgeImage: '/badges/ehe/young-adult/Startup-Beginner-Ready.png',
      completed: gameCompletionStatus["ehe-young-adult-40"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-startup-beginner-ready",
      index: 39,
    },
    {
      id: "ehe-young-adult-41",
      title: "Simulation: Expanding Too Early",
      description:
        "Scenario: Your startup earned a profit for two months straight, and you want to expand immediately. Choices: Open a new branch blindly / Check cash reserves and system stability first / Spend money on a huge launch party.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-41"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-expanding-too-early",
      index: 40,
    },
    {
      id: "ehe-young-adult-42",
      title: "Reflex: Hiring First Employee",
      description:
        "Scenario: You need help managing orders. Tap for 'Role clarity & skill match', avoid 'Hiring a close friend only' and 'Lowest salary choice'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-42"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-hiring-first-employee",
      index: 41,
    },
    {
      id: "ehe-young-adult-43",
      title: "Puzzle: Customer Retention",
      description:
        "Understand the impact of retention. Match why focusing entirely on new customers carries a high marketing cost, while building loyalty creates long-term revenue.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-43"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-customer-retention",
      index: 42,
    },
    {
      id: "ehe-young-adult-44",
      title: "Story: Profit Usage",
      description:
        "Scenario: Your business earns its first real profit. Do you use it entirely for personal spending to celebrate, or do you allocate a partial reinvestment back into the business? Partial reinvestment.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-44"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-profit-usage",
      index: 43,
    },
    {
      id: "ehe-young-adult-45",
      title: "Quiz: Loan for Expansion",
      description:
        "Scenario: A bank offers you an easy loan for rapid expansion. What MUST be calculated before accepting? Test your awareness on taking business loans.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-45"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-loan-for-expansion",
      index: 44,
    },
    {
      id: "ehe-young-adult-46",
      title: "Debate: Inventory Over-Purchase",
      description:
        "You want to buy a massive amount of stock expecting high demand. Is this a smart way to guarantee profit, or does it create a huge cash blockage risk? It creates cash blockage risk.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-46"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-inventory-over-purchase",
      index: 45,
    },
    {
      id: "ehe-young-adult-47",
      title: "Reflex: Digital Payment Adoption",
      description:
        "Scenario: You operate a store. Tap for 'Offer Digital Payment Options', avoid 'Cash Transactions Only' and 'Ignoring Customer Preference'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-47"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-digital-payment-adoption",
      index: 46,
    },
    {
      id: "ehe-young-adult-48",
      title: "Journal: Sustainable Competition",
      description:
        "Scenario: A competitor reduces their price below cost to steal your customers. Write your sustainable strategy instead of panic reacting.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-48"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-sustainable-competition",
      index: 47,
    },
    {
      id: "ehe-young-adult-49",
      title: "Story: Founder Burnout",
      description:
        "Scenario: You handle all business operations completely alone to save money. Do you continue overworking until you burn out, or start delegation and process creation? Delegation and process creation.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
      completed: gameCompletionStatus["ehe-young-adult-49"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-founder-burnout",
      index: 48,
    },
    {
      id: "ehe-young-adult-50",
      title: "Badge: Startup Growth Strategist",
      description:
        "Startup Growth Checkpoint • Task: Make 5 correct growth and scaling decisions. • Mechanic: Achievement • Outcome Message: You understand structured startup growth and financial discipline. • Reward: Badge – “Startup Growth Strategist”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 10,
      xp: 20,
       isBadgeGame: true,
      badgeName: 'Badge: Startup Growth Strategist',
      badgeImage: '/badges/ehe/young-adult/Startup-Growth-Strategist.png',
      completed: gameCompletionStatus["ehe-young-adult-50"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-startup-growth-strategist",
      index: 49,
    },
    {
      id: "ehe-young-adult-51",
      title: "Puzzle: Mixing Personal and Business Money",
      description:
        "Understand financial boundaries. Match why mixing personal savings and business revenue causes financial confusion, while keeping separate accounts improves clarity and control.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-51"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-mixing-personal-business-money",
      index: 50,
    },
    {
      id: "ehe-young-adult-52",
      title: "Reflex: Tax Rules",
      description:
        "Scenario: You need to handle business taxes. Tap for 'Learn basic tax registration', avoid 'Ignore tax rules' and 'Legal penalties'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-52"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-tax-rules",
      index: 51,
    },
    {
      id: "ehe-young-adult-53",
      title: "Quiz: Single Revenue Source",
      description:
        "Scenario: Your business depends completely on one major customer. What is the biggest risk here? Test your awareness on evaluating revenue concentration.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-53"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-single-revenue-source",
      index: 52,
    },
    {
      id: "ehe-young-adult-54",
      title: "Story: No Written Agreement",
      description:
        "Scenario: You are making an important partnership decision. Do you just agree verbally to show strong trust, or insist on a written agreement? Insist on a written agreement.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-54"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-no-written-agreement",
      index: 53,
    },
    {
      id: "ehe-young-adult-55",
      title: "Simulation: Expense Tracking",
      description:
        "Scenario: You have various daily business costs. Choices: Do not record them to save time / Track daily expenses in a ledger / Guess the profit at month-end.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-55"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-expense-tracking",
      index: 54,
    },
    {
      id: "ehe-young-adult-56",
      title: "Debate: Emergency Reserve",
      description:
        "Your sales drop suddenly for a whole month. Should you resort to panic borrowing to survive, or use a pre-planned emergency reserve fund? Use the emergency reserve fund.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-56"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-emergency-reserve",
      index: 55,
    },
    {
      id: "ehe-young-adult-57",
      title: "Reflex: Over-Borrowing",
      description:
        "Scenario: You have minor business expenses coming up. Tap for 'Loan discipline', avoid 'Take multiple small loans' and 'Create debt burden'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-57"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-over-borrowing",
      index: 56,
    },
    {
      id: "ehe-young-adult-58",
      title: "Story: Ignoring Customer Complaints",
      description:
        "Scenario: Customers leave negative reviews online. Do you leave them unanswered to save face, or respond to them to improve your service? Respond to them.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-58"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-ignoring-customer-complaints",
      index: 57,
    },
    {
      id: "ehe-young-adult-59",
      title: "Journal: Business Planning",
      description:
        "Scenario: You are currently operating without any defined short-term targets. Write your strategy to avoid directionless operations.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-59"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-business-planning",
      index: 58,
    },
    {
      id: "ehe-young-adult-60",
      title: "Badge: Young Business Stability Aware",
      description:
        "Entrepreneurship Stability Checkpoint • Task: Make 5 correct financial discipline and risk decisions. • Mechanic: Achievement • Outcome Message: You understand structured business risk management and financial responsibility. • Reward: Badge – “Young Business Stability Aware”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
       isBadgeGame: true,
      badgeName: 'Badge: Young Business Stability Aware',
      badgeImage: '/badges/ehe/young-adult/Young-Business-Stability-Aware.png',
      completed: gameCompletionStatus["ehe-young-adult-60"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-young-business-stability-aware",
      index: 59,
    },
    {
      id: "ehe-young-adult-61",
      title: "Story: Choosing Degree Without Research",
      description:
        "Scenario: You select a degree based only on its popularity among your friends. Do you expect guaranteed placement, or do you realize the risk of career misalignment? Realize career misalignment.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-61"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-choosing-degree-without-research",
      index: 60,
    },
    {
      id: "ehe-young-adult-62",
      title: "Quiz: Course vs Career Demand",
      description:
        "Scenario: You are about to choose a course without checking job demand. What should be reviewed to make a smart choice? Test your awareness on aligning education with market needs.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-62"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-course-vs-career-demand",
      index: 61,
    },
    {
      id: "ehe-young-adult-63",
      title: "Simulation: Education Loan Decision",
      description:
        "Scenario: You plan to take a massive loan for higher studies. Choices: Base it on the university's advertising / Base it on peer opinion / Calculate repayment capacity and career return.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-63"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-education-loan-decision",
      index: 62,
    },
    {
      id: "ehe-young-adult-64",
      title: "Puzzle: Skill-Based Short Courses",
      description:
        "Understand the actual value of skill-based learning. Match why a 6-month course relying solely on brand name has low impact, while industry relevance creates high practical value.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-64"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-skill-based-short-courses",
      index: 63,
    },
    {
      id: "ehe-young-adult-65",
      title: "Reflex: Internship Action",
      description:
        "Scenario: You are completing your degree but lack practical exposure. Tap for 'Seek Internships', avoid 'Rely on Degree Alone' and 'Reduced Job Readiness'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-65"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-internship-action",
      index: 64,
    },
    {
      id: "ehe-young-adult-66",
      title: "Debate: Studying Abroad Decision",
      description:
        "You are planning overseas education primarily due to peer influence. Should you prioritize social status, or carefully evaluate the cost and long-term career benefit? Evaluate cost and long-term career benefit.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-66"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-studying-abroad-decision",
      index: 65,
    },
    {
      id: "ehe-young-adult-67",
      title: "Journal: College Time Management",
      description:
        "Scenario: You realize you've been focusing only on social activities. Write your strategy to shift away from ignoring academics and build balance.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-67"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-college-time-management",
      index: 66,
    },
    {
      id: "ehe-young-adult-68",
      title: "Story: Changing Course Midway",
      description:
        "Scenario: You feel your chosen field is not suitable halfway through the year. Do you drop out immediately in frustration, or evaluate your alternatives carefully? Evaluate alternatives carefully.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-68"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-changing-course-midway",
      index: 67,
    },
    {
      id: "ehe-young-adult-69",
      title: "Reflex: Certification Collection",
      description:
        "Scenario: You are completing many certifications without understanding their relevance. Tap for 'Skill Application', avoid 'Quantity Collection' and 'Certificate Design'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-69"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-certification-collection",
      index: 68,
    },
    {
      id: "ehe-young-adult-70",
      title: "Badge: Education Planner",
      description:
        "Education Planning Checkpoint • Task: Make 5 correct education planning decisions. • Mechanic: Achievement • Outcome Message: You understand structured education alignment and career direction. • Reward: Badge – “Education Planner”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
       isBadgeGame: true,
      badgeName: 'Badge: Education Planner',
      badgeImage: '/badges/ehe/young-adult/Young-Career-Starter.png',
      completed: gameCompletionStatus["ehe-young-adult-70"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-education-planner",
      index: 69,
    },
    {
      id: "ehe-young-adult-71",
      title: "Simulation: Practical Skill Gap",
      description:
        "Scenario: You complete academic exams successfully but lack practical tools knowledge. Choices: Wait for campus placement / Rely only on higher marks / Start practical skill training.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-71"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-practical-skill-gap",
      index: 70,
    },
    {
      id: "ehe-young-adult-72",
      title: "Reflex: Final Year Placement",
      description:
        "Scenario: Campus placement season begins. Tap for 'Structured resume & interview practice', avoid 'Last-minute preparation' and 'Social media activity'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-72"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-final-year-placement",
      index: 71,
    },
    {
      id: "ehe-young-adult-73",
      title: "Quiz: Industry Certification",
      description:
        "Scenario: You are thinking of delaying your certification until after graduation. What is the actual advantage of early certification? Test your awareness on securing competitive placements.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-73"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-industry-certification",
      index: 72,
    },
    {
      id: "ehe-young-adult-74",
      title: "Puzzle: Portfolio Development",
      description:
        "Understand the value of demonstrable skill. Match why applying without a portfolio makes for a weak application, while demonstrable project work boosts credibility.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-74"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-portfolio-development",
      index: 73,
    },
    {
      id: "ehe-young-adult-75",
      title: "Story: Networking in College",
      description:
        "Scenario: You usually avoid professional events and seminars to stay in your comfort zone. Do you continue staying in your room, or step out for industry exposure and mentorship? Step out for industry exposure.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 15,
      xp: 30,
      completed: gameCompletionStatus["ehe-young-adult-75"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-networking-in-college",
      index: 74,
    },
    {
      id: "ehe-young-adult-76",
      title: "Debate: Soft Skills Importance",
      description:
        "You focus only on technical knowledge and ignore communication skills. Is technical knowledge alone enough, or do communication and teamwork skills also heavily affect employability? Communication and teamwork also affect it.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-76"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-soft-skills-importance",
      index: 75,
    },
    {
      id: "ehe-young-adult-77",
      title: "Reflex: Emerging Technologies",
      description:
        "Scenario: A new technology becomes popular in your field. Tap for 'Gradual skill adaptation', avoid 'Ignoring change' and 'Complaining about trends'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-77"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-emerging-technologies",
      index: 76,
    },
    {
      id: "ehe-young-adult-78",
      title: "Journal: Balancing Work & Study",
      description:
        "Scenario: You consider taking up part-time work during college. Write your strategy to use time-management to ensure success at both.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-78"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-balancing-work-study",
      index: 77,
    },
    {
      id: "ehe-young-adult-79",
      title: "Simulation: Evaluating a Job Offer",
      description:
        "Scenario: You receive a job offer completely unrelated to your field of study. Choices: Accept for the salary only / Ask peers for social validation / Evaluate long-term career alignment.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-79"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-evaluating-a-job-offer",
      index: 78,
    },
    {
      id: "ehe-young-adult-80",
      title: "Badge: Career Ready Graduate",
      description:
        "Career Preparation Checkpoint • Task: Make 5 correct advanced career preparation decisions. • Mechanic: Achievement • Outcome Message: You understand structured career preparation and skill-building strategy. • Reward: Badge – “Career Ready Graduate”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
       isBadgeGame: true,
      badgeName: 'Badge: Career Ready Graduate',
      badgeImage: '/badges/ehe/young-adult/Career-Ready-Graduate.png',
      completed: gameCompletionStatus["ehe-young-adult-80"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-career-ready-graduate",
      index: 79,
    },
    {
      id: "ehe-young-adult-81",
      title: "Story: Ignoring Tuition Cost",
      description:
        "Scenario: You enroll in a course without reviewing total tuition and living costs. Do you assume an automatic scholarship will save you, or realize this will cause financial stress? Realize it will cause financial stress.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-81"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-ignoring-tuition-cost",
      index: 80,
    },
    {
      id: "ehe-young-adult-82",
      title: "Quiz: Depending Fully on Loans",
      description:
        "Scenario: You plan to fund 100% of your education through borrowing. What is the most important thing to assess? Test your awareness on analyzing education return on investment.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-82"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-depending-fully-on-loans",
      index: 81,
    },
    {
      id: "ehe-young-adult-83",
      title: "Reflex: Scholarship Options",
      description:
        "Scenario: You need help paying for your studies. Tap for 'Apply for Available Scholarships', avoid 'Ignore Options' and 'Lose Financial Support'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-83"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-scholarship-options",
      index: 82,
    },
    {
      id: "ehe-young-adult-84",
      title: "Puzzle: Budget During College",
      description:
        "Understand essential financial habits. Match why leaving expenses untracked risks overspending, while budgeting builds early financial responsibility.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-84"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-budget-during-college",
      index: 83,
    },
    {
      id: "ehe-young-adult-85",
      title: "Debate: Dropping Course Without Plan",
      description:
        "You consider quitting mid-course due to difficulty. Is an immediate emotional withdrawal the right choice, or should you evaluate the academic and financial impact first? Evaluate the academic and financial impact.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-85"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-dropping-course-without-plan",
      index: 84,
    },
    {
      id: "ehe-young-adult-86",
      title: "Story: Expensive Accommodation",
      description:
        "Scenario: You select premium housing that is well beyond your budget. Will this guarantee better grades, or will it result in heavy financial pressure? Financial pressure.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-86"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-expensive-accommodation",
      index: 85,
    },
    {
      id: "ehe-young-adult-87",
      title: "Journal: Part-Time Income",
      description:
        "Scenario: You start earning a part-time income during college. Write your strategy to allocate a portion to stability instead of just lifestyle expenses.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-87"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-part-time-income",
      index: 86,
    },
    {
      id: "ehe-young-adult-88",
      title: "Simulation: Education vs Immediate Job",
      description:
        "Scenario: You receive a job offer just before completing your degree. Choices: Accept for the salary only / Base it on social recognition / Evaluate the long-term career impact.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-88"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-education-vs-immediate-job",
      index: 87,
    },
    {
      id: "ehe-young-adult-89",
      title: "Reflex: Academic Performance",
      description:
        "Scenario: You assume only practical skills matter and think about ignoring your classes. Tap for 'Maintain Academic Performance', avoid 'Neglect Grades' and 'Reduced Eligibility'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-89"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-academic-performance",
      index: 88,
    },
    {
      id: "ehe-young-adult-90",
      title: "Badge: Financially Responsible Student",
      description:
        "Education Risk Checkpoint • Task: Make 5 correct education financial discipline decisions. • Mechanic: Achievement • Outcome Message: You understand financial planning and risk awareness in higher education. • Reward: Badge – “Financially Responsible Student”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
       isBadgeGame: true,
      badgeName: 'Badge: Financially Responsible Student',
      badgeImage: '/badges/ehe/young-adult/Financially-Responsible-Student.png',
      completed: gameCompletionStatus["ehe-young-adult-90"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-financially-responsible-student",
      index: 89,
    },
    {
      id: "ehe-young-adult-91",
      title: "Simulation: Career vs Startup Choice",
      description:
        "Scenario: After graduation, you must choose between taking a job or launching a startup idea. Choices: Decide based on emotional excitement / Follow a social trend / Conduct a thorough risk and financial evaluation.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-91"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/simulation-career-vs-startup-choice",
      index: 90,
    },
    {
      id: "ehe-young-adult-92",
      title: "Quiz: Skill Investment Priority",
      description:
        "Scenario: You have limited funds to either set up a business or take a skill course. What should guide your choice? Test your awareness on prioritizing investments that yield long-term returns.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-92"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/quiz-skill-investment-priority",
      index: 91,
    },
    {
      id: "ehe-young-adult-93",
      title: "Story: Delayed Career Planning",
      description:
        "Scenario: You postpone defining your long-term goals because it feels overwhelming. Will this lead to structured growth, or result in random, unpredictable progression? Random progression.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-93"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-delayed-career-planning",
      index: 92,
    },
    {
      id: "ehe-young-adult-94",
      title: "Puzzle: Multiple Income Sources",
      description:
        "Understand financial resilience. Match why single income dependency creates high financial risk, while diversified skill-based income provides stability.",
      icon: <Puzzle className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-94"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/puzzle-multiple-income-sources",
      index: 93,
    },
    {
      id: "ehe-young-adult-95",
      title: "Debate: Ethical Shortcut",
      description:
        "A shortcut promises quick money, but its legality is highly unclear. Should you go for the immediate gain, or prioritize ethical compliance to protect your future credibility? Prioritize ethical compliance.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-95"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/debate-ethical-shortcut",
      index: 94,
    },
    {
      id: "ehe-young-adult-96",
      title: "Reflex: Continuous Learning Plan",
      description:
        "Scenario: You finally secure a good job. Tap for 'Continuous Improvement', avoid 'Static Learning' and 'Waiting for Employer'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-96"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-continuous-learning-plan",
      index: 95,
    },
    {
      id: "ehe-young-adult-97",
      title: "Reflex: Financial Discipline",
      description:
        "Scenario: Your early career income increases, but your savings are still zero. Tap for 'Structured Saving Habit', avoid 'Lifestyle Expansion' and 'Borrowing'.",
      icon: <Zap className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-97"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/reflex-financial-discipline",
      index: 96,
    },
    {
      id: "ehe-young-adult-98",
      title: "Journal: Long-Term Goals",
      description:
        "Scenario: You realize you have not defined your 5-year professional goals. Write your strategy to establish structured and measurable targets.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-98"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/journal-of-long-term-goals",
      index: 97,
    },
    {
      id: "ehe-young-adult-99",
      title: "Story: Handling Early Failure",
      description:
        "Scenario: Your very first startup attempt fails. Do you quit permanently out of frustration, or do you start learning and refining your strategy? Learning and refining strategy.",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Medium",
      duration: "5 min",
      coins: 20,
      xp: 40,
      completed: gameCompletionStatus["ehe-young-adult-99"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/story-handling-early-failure",
      index: 98,
    },
    {
      id: "ehe-young-adult-100",
      title: "Badge: Young Adult Strategic Thinker",
      description:
        "Young Adult Mastery Checkpoint • Task: Make 5 correct integrated career, business, and education decisions. • Mechanic: Achievement • Outcome Message: You demonstrate structured thinking across career, entrepreneurship, and higher education pathways. • Reward: Badge – “Young Adult Strategic Thinker”",
      icon: <Briefcase className="w-6 h-6" />,
      difficulty: "Hard",
      duration: "5 min",
      coins: 20,
      xp: 40,
       isBadgeGame: true,
      badgeName: 'Badge: Young Adult Strategic Thinker',
      badgeImage: '/badges/ehe/young-adult/Young-Adult-Strategic-Thinker.png',
      completed: gameCompletionStatus["ehe-young-adult-100"] || false,
      isSpecial: true,
      reflective: false,
      path: "/student/ehe/young-adult/badge-young-adult-strategic-thinker",
      index: 99,
    },
  ];

  return eheYoungAdultGames;
};

