import {
  Hand,
  Sparkles,
  Zap,
  Target,
  Droplets,
  Sun,
  BookOpen,
  Shirt,
  Shield,
  Badge,
  Apple,
  Brain,
  Carrot,
  Activity,
  Heart,
  HandHeart
} from "lucide-react";
import buildIds from "../buildGameIds";

export const healthFemaleGameIdsKids = buildIds("health-female", "kids")

export const getHealthFemaleKidsGames = (gameCompletionStatus) => {
    const healthFemaleGamesKids = [
        {
            id: 'health-female-kids-1',
            title: 'Handwash Heroine',
            description: 'Learn proper handwashing techniques and when to wash your hands to stay healthy and clean!',
            icon: <Hand className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-1'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/handwash-heroine',
            index: 0
        },
        {
            id: 'health-female-kids-2',
            title: 'Cleanliness Quiz',
            description: 'Answer 5 questions about daily hygiene habits. Bathing, brushing, and staying clean!',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-2'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/cleanliness-quiz',
            index: 1
        },
        {
            id: 'health-female-kids-3',
            title: 'Reflex Hygiene Check',
            description: 'Quick! Tap for clean habits, avoid the dirty ones. Test your reflexes!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-3'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene',
            index: 2
        },
        {
            id: 'health-female-kids-4',
            title: 'Hygiene Match',
            description: 'Match hygiene items to their uses. Learn what each item is for!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-4'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-match',
            index: 3
        },
        {
            id: 'health-female-kids-5',
            title: 'Bath Time Story',
            description: 'Make the right choices in this interactive story about bath time!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-5'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/bath-time-story',
            index: 4
        },
        {
            id: 'health-female-kids-6',
            title: 'Fresh & Neat Poster',
            description: 'Create a poster to show what you\'ve learned about hygiene!',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-6'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/fresh-poster',
            index: 5
        },
        {
            id: 'health-female-kids-7',
            title: 'Hygiene Journal',
            description: 'Write about your favorite hygiene habit and why it\'s important!',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-7'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-journal',
            index: 6
        },
        {
            id: 'health-female-kids-8',
            title: 'Hair Care Story',
            description: 'Learn how to take care of your hair in this interactive story!',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-8'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hair-care-story',
            index: 7
        },
        {
            id: 'health-female-kids-9',
            title: 'Dress Up Reflex',
            description: 'Quick! Choose the clean clothes for different occasions!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-9'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene-alert',
            index: 8
        },
        {
            id: 'health-female-kids-10',
            title: 'Vaccine Story',
            description: 'Doctor says you need a vaccine shot. Should you take it? Learn about vaccines!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-10'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/vaccine-story',
            index: 9
        },
        
        {
            id: 'health-female-kids-11',
            title: 'Fruit vs Candy Story',
            description: 'You have grapes and candy. Which is better for your body? Learn healthy food choices!',
            icon: <Apple className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-11'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/fruit-vs-candy-story',
            index: 10
        },
        {
            id: 'health-female-kids-12',
            title: 'Quiz on Food Groups',
            description: 'Answer 5 questions about nutrition! Proteins, carbs, vitamins - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-12'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-food-groups',
            index: 11
        },
        {
            id: 'health-female-kids-13',
            title: 'Reflex Healthy Food',
            description: 'Test your reflexes with 5 quick food decisions! Choose vegetables over junk food - pass 3/5 to continue!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-13'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-healthy-food',
            index: 12
        },
        {
            id: 'health-female-kids-14',
            title: 'Puzzle: Nutrition Match',
            description: 'Match foods to nutrients! Complete 5 sequential puzzles: Milk → Calcium, Rice → Carbs, Apple → Vitamins, etc.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-14'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/nutrition-match-puzzle',
            index: 13
        },
        {
            id: 'health-female-kids-15',
            title: 'Lunchbox Story',
            description: 'Make healthy lunch choices in 5 different scenarios. Homemade meal vs fast food - make smart choices!',
            icon: <Carrot className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-15'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/lunchbox-story',
            index: 14
        },
        {
            id: 'health-female-kids-16',
            title: 'Poster: My Healthy Plate',
            description: 'Create/select poster: "Half Fruits & Veggies, Half Grains & Proteins."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-16'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-plate-poster',
            index: 15
        },
        {
            id: 'health-female-kids-17',
            title: 'Journal of Healthy Food',
            description: 'Write: "One healthy food I like is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-17'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-food-journal',
            index: 16
        },
        {
            id: 'health-female-kids-18',
            title: 'Junk Food Story',
            description: 'Friends buy chips daily. Should you? Learn to make healthy choices!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-18'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/junk-food-story',
            index: 17
        },
        {
            id: 'health-female-kids-19',
            title: 'Reflex Smart Drink',
            description: 'Test your reflexes with 5 quick drink decisions! Choose water over soda - pass 3/5 to continue!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-19'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-smart-drink',
            index: 18
        },
        {
            id: 'health-female-kids-20',
            title: 'Badge: Nutrition Smart Kid',
            description: 'Complete 5 nutrition challenges to earn your Nutrition Smart Kid Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-20'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/nutrition-smart-badge',
            index: 19
        },
        {
            id: 'health-female-kids-21',
            title: 'Growing Taller Story',
            description: 'You notice your height increasing. Is this normal? Learn about healthy growth!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-21'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growing-taller-story',
            index: 20
        },
        {
            id: 'health-female-kids-22',
            title: 'Quiz on Growth',
            description: 'Answer 5 questions about growing stronger! Exercise, nutrition, health - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-22'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-growth',
            index: 21
        },
        {
            id: 'health-female-kids-23',
            title: 'Reflex Growth Check',
            description: 'Test your reflexes with 5 quick growth decisions! Choose healthy habits over bad ones - pass 3/5 to continue!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-23'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-growth-check',
            index: 22
        },
        {
            id: 'health-female-kids-24',
            title: 'Puzzle: Growth Helpers',
            description: 'Match growth activities to body parts! Complete 5 sequential puzzles: Milk → Bones, Fruits → Vitamins, etc.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-24'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growth-helpers-puzzle',
            index: 23
        },
        {
            id: 'health-female-kids-25',
            title: 'Hair Growth Story',
            description: 'You see hair on arms and legs. Is it normal? Learn about body changes during growth!',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-25'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hair-growth-story',
            index: 24
        },
        {
            id: 'health-female-kids-26',
            title: 'Poster: Growing Up is Natural',
            description: 'Create/select poster: "Every Girl Grows Differently."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-26'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growing-up-poster',
            index: 25
        },
        {
            id: 'health-female-kids-27',
            title: 'Journal of Body Changes',
            description: 'Write: "One body change I noticed is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-27'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/body-changes-journal',
            index: 26
        },
        {
            id: 'health-female-kids-28',
            title: 'Mood Change Story',
            description: 'You feel happy one moment and sad next. Is this part of growing? Learn about emotions!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-28'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/mood-change-story',
            index: 27
        },
        {
            id: 'health-female-kids-29',
            title: 'Reflex Growth Alert',
            description: 'Quick health decisions for growing bodies! Choose exercise over laziness, healthy food over junk - pass 3/5!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-29'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-growth-alert',
            index: 28
        },
        {
            id: 'health-female-kids-30',
            title: 'Badge: Growing Strong Girl',
            description: 'Complete 5 growth challenges to earn your Growing Strong Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-30'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growing-strong-badge',
            index: 29
        },
        {
            id: 'health-female-kids-31',
            title: 'Morning Routine Story',
            description: 'Should you brush + wash face after waking up? Learn healthy morning habits!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-31'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/morning-routine-story',
            index: 30
        },
        {
            id: 'health-female-kids-32',
            title: 'Quiz on Daily Habits',
            description: 'Answer 5 questions about good daily habits! Sleep, nutrition, hygiene - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-32'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-daily-habits',
            index: 31
        },
        {
            id: 'health-female-kids-33',
            title: 'Reflex Habit Alert',
            description: 'Test your reflexes with 5 quick healthy habit decisions! Choose healthy over harmful - pass 3/5!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-33'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-habit-alert',
            index: 32
        },
        {
            id: 'health-female-kids-34',
            title: 'Puzzle: Healthy Matches',
            description: 'Match daily habits to their benefits! Complete 5 sequential puzzles!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-34'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-matches-puzzle',
            index: 33
        },
        {
            id: 'health-female-kids-35',
            title: 'Screen-Time Story',
            description: 'Should you use mobile all night or sleep early? Learn about healthy screen time!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-35'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/screen-time-story',
            index: 34
        },
        {
            id: 'health-female-kids-36',
            title: 'Poster: Healthy Girls Win',
            description: 'Create/select poster: "Good Habits Build Strong Girls."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-36'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-girls-win-poster',
            index: 35
        },
        {
            id: 'health-female-kids-37',
            title: 'Journal of Habits',
            description: 'Write: "One habit I want to improve is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-37'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/journal-of-habits',
            index: 36
        },
        {
            id: 'health-female-kids-38',
            title: 'Reading Story',
            description: 'Why read daily? Learn how reading improves knowledge and mind!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-38'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reading-story',
            index: 37
        },
        {
            id: 'health-female-kids-39',
            title: 'Reflex Daily Check',
            description: 'Quick daily hygiene decisions! Choose good habits over skipping - pass 3/5!',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-39'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-daily-check',
            index: 38
        },
        {
            id: 'health-female-kids-40',
            title: 'Badge: Healthy Routine Kid',
            description: 'Complete 5 daily habit challenges to earn your Healthy Routine Kid Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-40'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-routine-kid-badge',
            index: 39
        },
        
        {
            id: 'health-female-kids-41',
            title: 'Sweat Story',
            description: 'You start sweating more than before. What should you do? Learn about hygiene changes!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-41'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/sweat-story',
            index: 40
        },
        {
            id: 'health-female-kids-42',
            title: 'Quiz on Hygiene',
            description: 'Answer 5 questions about body odor prevention! Bathing, fresh clothes, daily care - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-42'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-hygiene',
            index: 41
        },
        {
            id: 'health-female-kids-43',
            title: 'Reflex Hygiene Alert',
            description: 'Test your reflexes with 5 quick hygiene decisions! Choose clean habits over skipping - pass 3/5!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-43'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene-alert-3',
            index: 42
        },
        {
            id: 'health-female-kids-44',
            title: 'Puzzle: Hygiene Match',
            description: 'Match hygiene items to their uses! Complete 5 sequential puzzles: Soap → Bath, Deodorant → Smell, etc.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-44'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-match-puzzle',
            index: 43
        },
        {
            id: 'health-female-kids-45',
            title: 'Dentist Visit Story',
            description: 'Doctor says: Visit dentist twice a year. Should you? Learn about dental health!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-45'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/dentist-visit-story',
            index: 44
        },
        {
            id: 'health-female-kids-46',
            title: 'Poster: Stay Fresh Everyday',
            description: 'Create/select poster: "Clean Girl, Confident Girl."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-46'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/stay-fresh-poster',
            index: 45
        },
        {
            id: 'health-female-kids-47',
            title: 'Journal: Hygiene Habits',
            description: 'Write: "One new hygiene habit I learned is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-47'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-habits-journal',
            index: 46
        },
        {
            id: 'health-female-kids-48',
            title: 'Skin Care Story',
            description: 'You notice pimples. Should you wash gently or pick them? Learn proper skin care!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-48'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/skin-care-story',
            index: 47
        },
        {
            id: 'health-female-kids-49',
            title: 'Reflex Cleanliness',
            description: 'Quick cleanliness decisions! Choose fresh clothes over dirty, hygiene over skipping - pass 3/5!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-49'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-cleanliness',
            index: 48
        },
        {
            id: 'health-female-kids-50',
            title: 'Badge: Fresh Girl',
            description: 'Complete 5 hygiene challenges to earn your Fresh Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-50'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/fresh-girl-badge',
            index: 49
        },
        {
            id: 'health-female-kids-51',
            title: 'Feelings Story',
            description: 'You feel sad when your doll breaks. Is this normal? Learn about emotions!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-51'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/feelings-story',
            index: 50
        },
        {
            id: 'health-female-kids-52',
            title: 'Quiz on Emotions',
            description: 'Answer 5 questions about emotions! Happy, sad, angry - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-52'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-emotions',
            index: 51
        },
        {
            id: 'health-female-kids-53',
            title: 'Reflex Emotion Basics',
            description: 'Test your reflexes wi th 5 quick emotion decisions! Choose happy over sad - pass 3/5!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-53'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-emotion-basics',
            index: 52
        },
        {
            id: 'health-female-kids-54',
            title: 'Puzzle: Emotion Match',
            description: 'Match emotions to expressions! Complete 5 sequential puzzles: Happy → Smile, Sad → Tears, etc.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-54'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/emotion-match-puzzle',
            index: 53
        },
        {
            id: 'health-female-kids-55',
            title: 'Sharing Story',
            description: 'You feel scared. Should you hide it or tell your parents? Learn about sharing feelings!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-55'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/sharing-story',
            index: 54
        },
        {
            id: 'health-female-kids-56',
            title: 'Poster: All Feelings Are Okay',
            description: 'Create/select poster: "It\'s Okay to Feel."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-56'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/all-feelings-poster',
            index: 55
        },
        {
            id: 'health-female-kids-57',
            title: 'Journal of Feelings',
            description: 'Write: "Today I felt ___ because __."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-57'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/feelings-journal',
            index: 56
        },
        {
            id: 'health-female-kids-58',
            title: 'Anger Story',
            description: 'Friend breaks your toy. Should you hit her? Learn to manage anger!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-58'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/anger-story',
            index: 57
        },
        {
            id: 'health-female-kids-59',
            title: 'Reflex Emotion Safety',
            description: 'Quick emotion management decisions! Choose talking over hiding - pass 3/5!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-59'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-emotion-safety',
            index: 58
        },
        {
            id: 'health-female-kids-60',
            title: 'Badge: Emotion Explorer',
            description: 'Identify 5 emotions correctly to earn your Emotion Explorer Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-60'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/emotion-explorer-badge',
            index: 59
        },
        {
            id: 'health-female-kids-61',
            title: 'Friend\'s Dare Story',
            description: 'A friend dares you to skip homework. Do you follow? Learn to make good choices!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-61'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/friends-dare-story',
            index: 60
        },
        {
            id: 'health-female-kids-62',
            title: 'Quiz on Peer Pressure',
            description: 'Answer 5 questions about peer pressure! Friends, dares, influence - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-62'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-peer-pressure',
            index: 61
        },
        {
            id: 'health-female-kids-63',
            title: 'Reflex Peer Safety',
            description: 'Test your reflexes with 5 quick peer pressure decisions! Choose safe choices over risky dares - pass 3/5!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-63'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-peer-safety',
            index: 62
        },
        {
            id: 'health-female-kids-64',
            title: 'Puzzle: Peer Choices',
            description: 'Match peer pressure responses to outcomes! Complete 5 sequential puzzles: Say No → Safe, etc.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-64'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-choices-puzzle',
            index: 63
        },
        {
            id: 'health-female-kids-65',
            title: 'Bully Story',
            description: 'Older girl pressures you to steal candy. Do you? Learn to stand up to bullies!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-65'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/bully-story',
            index: 64
        },
        {
            id: 'health-female-kids-66',
            title: 'Poster: Power of No',
            description: 'Create/select poster: "Saying No Makes Me Strong."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-66'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/power-of-no-poster',
            index: 65
        },
        {
            id: 'health-female-kids-67',
            title: 'Journal of Peer Choices',
            description: 'Write: "One time I said no to pressure was ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-67'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-choices-journal',
            index: 66
        },
        {
            id: 'health-female-kids-68',
            title: 'Mobile Pressure Story',
            description: 'Friends force you to use phone secretly. Do you? Learn to resist peer pressure!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-68'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/mobile-pressure-story',
            index: 67
        },
        {
            id: 'health-female-kids-69',
            title: 'Reflex Respect Alert',
            description: 'Quick respect decisions! Choose self-respect over following wrong crowd - pass 3/5!',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-69'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-respect-alert',
            index: 68
        },
        {
            id: 'health-female-kids-70',
            title: 'Badge: Peer Pressure Fighter',
            description: 'Handle 5 peer pressure cases to earn your Peer Pressure Fighter Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-70'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-pressure-fighter-badge',
            index: 69
        },
        {
            id: 'health-female-kids-71',
            title: 'Clean Girl Badge',
            description: 'Complete all hygiene challenges to earn your Clean Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '1 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-71'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/clean-girl-badge',
            index: 70
        },
        {
            id: 'health-female-kids-72',
            title: 'Quiz on Prevention',
            description: 'Answer 5 questions about disease prevention! Washing hands, vaccines, checkups - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-72'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-prevention',
            index: 71
        },
        {
            id: 'health-female-kids-73',
            title: 'Reflex Safety',
            description: 'Test your reflexes with 5 quick safety decisions! Choose protection over risk - pass 3/5!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-73'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-safety',
            index: 72
        },
        {
            id: 'health-female-kids-74',
            title: 'Puzzle: Safety Tools',
            description: 'Match safety tools to their uses! Complete 5 sequential puzzles: Helmet → Bike, etc.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-74'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/safety-tools-puzzle',
            index: 73
        },
        {
            id: 'health-female-kids-75',
            title: 'Sick Day Story',
            description: 'You feel unwell. Should you hide or tell parents? Learn about illness management!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-75'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/sick-day-story',
            index: 74
        },
        {
            id: 'health-female-kids-76',
            title: 'Poster: Prevention First',
            description: 'Create/select poster: "Prevention is Better Than Cure."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-76'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/prevention-first-poster',
            index: 75
        },
        {
            id: 'health-female-kids-77',
            title: 'Journal of Safety',
            description: 'Write: "One safety habit I follow is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-77'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/journal-of-safety',
            index: 76
        },
        {
            id: 'health-female-kids-78',
            title: 'Period Hygiene Story',
            description: 'A girl doesn\'t change pad for many hours. What happens? Learn about period hygiene!',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-78'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-hygiene-story',
            index: 77
        },
        
        {
            id: 'health-female-kids-79',
            title: 'Reflex Doctor Alert',
            description: 'Quick health decisions! Choose seeing doctors over ignoring illness - pass 3/5!',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-79'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-doctor-alert',
            index: 78
        },
        {
            id: 'health-female-kids-80',
            title: 'Badge: Safety Smart Girl',
            description: 'Complete 5 prevention tasks to earn your Safety Smart Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-80'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/safety-smart-girl-badge',
            index: 79
        },
        {
            id: 'health-female-kids-81',
            title: 'Cigarette Story',
            description: 'A friend offers you a cigarette. Should you try? Learn to make healthy choices!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-81'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/cigarette-story',
            index: 80
        },
        {
            id: 'health-female-kids-82',
            title: 'Quiz on Harmful Things',
            description: 'Answer 5 questions about harmful substances! Cigarettes, energy drinks, drugs - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-82'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-harmful-things',
            index: 81
        },
        {
            id: 'health-female-kids-83',
            title: 'Reflex Safe Choice',
            description: 'Test your reflexes with 5 quick healthy decisions! Choose nutritious over harmful - pass 3/5!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-83'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-safe-choice',
            index: 82
        },
        {
            id: 'health-female-kids-84',
            title: 'Puzzle: Healthy vs Harmful',
            description: 'Match items to healthy or harmful categories! Complete 5 sequential puzzles!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-84'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-vs-harmful-puzzle',
            index: 83
        },
        {
            id: 'health-female-kids-85',
            title: 'Energy Drinks story',
            description: 'An older girl offers energy drinks. Should you drink? Learn to resist peer pressure!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-85'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/energy-drinks-story',
            index: 84
        },
        {
            id: 'health-female-kids-86',
            title: 'Poster: Say No to Substances',
            description: 'Create/select poster: "I Choose Health, Not Drugs."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-86'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/say-no-substances-poster',
            index: 85
        },
        {
            id: 'health-female-kids-87',
            title: 'Journal of Refusal',
            description: 'Write: "I will always say no to ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-87'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/journal-of-refusal',
            index: 86
        },
        {
            id: 'health-female-kids-88',
            title: 'Peer Story',
            description: 'A classmate says "Cool girls drink." Should you follow? Learn to resist peer pressure!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-88'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-story',
            index: 87
        },
        {
            id: 'health-female-kids-89',
            title: 'Reflex Danger Alert',
            description: 'Quick healthy lifestyle decisions! Choose exercise over drugs - pass 3/5!',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-89'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-danger-alert',
            index: 88
        },
        {
            id: 'health-female-kids-90',
            title: 'Badge: Safe Girl',
            description: 'Complete 5 refusal challenges to earn your Safe Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-90'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/safe-girl-badge',
            index: 89
        },
        {
            id: 'health-female-kids-91',
            title: 'First Period Story',
            description: 'A girl gets her first period at school. What should she do? Learn about periods!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-91'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/first-period-story',
            index: 90
        },
        {
            id: 'health-female-kids-92',
            title: 'Quiz on Period Basics',
            description: 'Answer 5 questions about periods! Normal body process vs sickness - pass 3/5 to continue!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-92'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-period-basics',
            index: 91
        },
        {
            id: 'health-female-kids-93',
            title: 'Reflex Period Awareness',
            description: 'Test your reflexes with 5 quick period decisions! Choose hygiene over shame - pass 3/5 to continue!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-93'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-period-awareness',
            index: 92
        },
        {
            id: 'health-female-kids-94',
            title: 'Puzzle: Period Tools',
            description: 'Match period items to their uses! Complete 5 sequential puzzles: Pad → Absorb, Soap → Clean, etc.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-94'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-tools-puzzle',
            index: 93
        },
        {
            id: 'health-female-kids-95',
            title: 'Support Story',
            description: 'A girl feels scared of periods. Should friends mock or comfort her? Learn about empathy!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-95'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/support-story',
            index: 94
        },
        {
            id: 'health-female-kids-96',
            title: 'Poster: Periods Are Normal',
            description: 'Create/select poster: "Periods = Strength, Not Shame."',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-96'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/periods-are-normal-poster',
            index: 95
        },
        {
            id: 'health-female-kids-97',
            title: 'Journal of Period Awareness',
            description: 'Write: "One thing I learned about periods is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-97'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-awareness-journal',
            index: 96
        },
        {
            id: 'health-female-kids-98',
            title: 'Hygiene Story',
            description: 'A girl doesn\'t change pad all day. What happens? Learn about hygiene risks!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-98'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-story',
            index: 97
        },
        {
            id: 'health-female-kids-99',
            title: 'Reflex Hygiene Alert',
            description: 'Quick hygiene decisions for periods! Choose change pads over keeping same - pass 3/5!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-99'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene-alert-2',
            index: 98
        },
        {
            id: 'health-female-kids-100',
            title: 'Badge: Period Ready Kid',
            description: 'Complete 5 period-awareness challenges to earn your Period Ready Kid Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-100'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-ready-badge',
            index: 99
        },
    ];

    return healthFemaleGamesKids;
};

export default getHealthFemaleKidsGames;
