import {
    Activity,
    Shield,
    Heart,
    Target,
    BookOpen,
    Zap,
    Droplets,
    Brain,
    HandHeart,
    Badge,
    MessageCircle,
    Smartphone
} from "lucide-react";
import buildIds from "../buildGameIds";

export const healthMaleGameIdsTeen = buildIds("health-male", "teen");

export const getHealthMaleTeenGames = (gameCompletionStatus) => {
    const healthMaleGamesTeens = [
        {
            id: 'health-male-teen-1',
            title: 'Puberty Hygiene Story',
            description: 'You sweat more during puberty. Use deodorant or ignore? Learn proper puberty hygiene!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-1'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/puberty-hygiene-story',
            index: 0
        },
        {
            id: 'health-male-teen-2',
            title: 'Quiz on Hygiene Changes',
            description: 'During puberty, which is correct? Bathe twice if needed or ignore sweat? Test your knowledge!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-2'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-hygiene-changes',
            index: 1
        },
        {
            id: 'health-male-teen-3',
            title: 'Reflex Smart Hygiene',
            description: 'Quick! Tap for "Shave Safely" or "Skip Hygiene" in fast reflex challenges!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-3'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-smart-hygiene',
            index: 2
        },
        {
            id: 'health-male-teen-4',
            title: 'Puzzle: Hygiene Tools',
            description: 'Match "Shaving Kit → Beard, Soap → Body, Face Wash → Acne" in hygiene tool puzzles!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-4'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/hygiene-tools-puzzle',
            index: 3
        },
        {
            id: 'health-male-teen-5',
            title: 'Sports Hygiene Story',
            description: 'After football, do you shower or stay sweaty? Learn proper sports hygiene!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-5'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/sports-hygiene-story',
            index: 4
        },
        {
            id: 'health-male-teen-6',
            title: 'Debate: Hygiene = Confidence?',
            description: 'Does hygiene improve confidence in teens? Debate the connection between hygiene and self-esteem!',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-6'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/hygiene-confidence-debate',
            index: 5
        },
        {
            id: 'health-male-teen-7',
            title: 'Journal of Self-Care',
            description: 'Write: "One hygiene routine I started as a teen is ___." Reflect on personal hygiene growth!',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-7'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/self-care-journal',
            index: 6
        },
        {
            id: 'health-male-teen-8',
            title: 'Simulation: Daily Routine',
            description: 'Teen wakes up. Options: Brush + shower, Brush only, Skip both. Choose the healthy routine!',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-8'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/daily-routine-simulation',
            index: 7
        },
        {
            id: 'health-male-teen-9',
            title: 'Reflex Hygiene Alert',
            description: 'Quick! Tap for "Fresh Clothes" or "Dirty Clothes" in hygiene reflex challenges!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-9'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/hygiene-alert-reflex',
            index: 8
        },
        {
            id: 'health-male-teen-10',
            title: 'Hygiene Pro Badge',
            description: 'Complete 5 hygiene routines correctly to earn your Hygiene Pro Teen Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-10'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/hygiene-pro-badge',
            index: 9
        },
        {
            id: 'health-male-teen-11',
            title: 'Balanced Diet Story',
            description: 'Teen chooses only fast food or mix of dal, rice, veggies, fruit? Choose balanced nutrition!',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-11'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/balanced-diet-story',
            index: 10
        },
        {
            id: 'health-male-teen-12',
            title: 'Quiz on Nutrition',
            description: 'Which helps muscles grow? (a) Protein, (b) Sugar). Test your nutrition knowledge!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-12'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-nutrition-teen',
            index: 11
        },
        {
            id: 'health-male-teen-13',
            title: 'Reflex Diet Check',
            description: 'Quick! Tap 🥗 for "Balanced Plate," 🍕 for "Pizza Every Day" in fast food decisions!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-13'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-diet-check',
            index: 12
        },
        {
            id: 'health-male-teen-14',
            title: 'Puzzle: Nutrient Match',
            description: 'Match "Iron → Spinach, Protein → Eggs, Vitamin C → Orange" in nutrition puzzles!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-14'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/nutrient-match-puzzle',
            index: 13
        },
        {
            id: 'health-male-teen-15',
            title: 'Sports Nutrition Story',
            description: 'After football, should you drink cola or water? Learn proper sports nutrition!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-15'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/sports-nutrition-story',
            index: 14
        },
        {
            id: 'health-male-teen-16',
            title: 'Debate: Junk Food in Moderation?',
            description: 'Is junk food okay sometimes? Debate the balance between treats and healthy eating!',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-16'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/junk-food-debate',
            index: 15
        },
        {
            id: 'health-male-teen-17',
            title: 'Journal of Diet Change',
            description: 'Write: "One diet change I made as a teen is ___." Reflect on your nutrition journey!',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-17'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/diet-change-journal',
            index: 16
        },
        {
            id: 'health-male-teen-18',
            title: 'Simulation: Weekly Meals',
            description: 'Teen plans meals. Options: (a) Only fast food, (b) Balanced menu, (c) Skip meals. Choose wisely!',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-18'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/weekly-meals-simulation',
            index: 17
        },
        {
            id: 'health-male-teen-19',
            title: 'Reflex Smart Drink',
            description: 'Quick! Tap 💧 for "Water," 🥤 for "Sugary Cola" in hydration decisions!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-19'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-smart-drink',
            index: 18
        },
        {
            id: 'health-male-teen-20',
            title: 'Badge: Nutrition Pro',
            description: 'Complete 5 healthy food choices to earn your Nutrition Pro Teen Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-20'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/nutrition-pro-badge',
            index: 19
        },
        {
            id: 'health-male-teen-21',
            title: 'Puberty Story',
            description: 'Teen notices sweat + voice change + mood swings. What\'s happening? → Puberty.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-21'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/puberty-story-teen',
            index: 20
        },
        {
            id: 'health-male-teen-22',
            title: 'Quiz on Puberty',
            description: 'Which is a sign of puberty? (a) Taller height, (b) Beard growth, (c) Both). Correct = Both.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-22'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-puberty-teen',
            index: 21
        },
        {
            id: 'health-male-teen-23',
            title: 'Reflex Puberty Check',
            description: 'Tap ✅ for "Normal Changes," ❌ for "Embarrassment."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-23'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-puberty-check-teen',
            index: 22
        },
        {
            id: 'health-male-teen-24',
            title: 'Puzzle: Puberty Signs',
            description: 'Match "Voice Cracks → Puberty, Sweating More → Puberty, Acne → Puberty."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-24'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/puberty-signs-puzzle-teen',
            index: 23
        },
        {
            id: 'health-male-teen-25',
            title: 'Acne Story',
            description: 'Teen gets pimples. Should he squeeze them or wash face gently? → Wash face gently.',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-teen-25'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/acne-story-teen',
            index: 24
        },
        {
            id: 'health-male-teen-26',
            title: 'Debate: Puberty = Awkward?',
            description: 'Is puberty embarrassing or natural? → Natural.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-26'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/puberty-awkward-debate-teen',
            index: 25
        },
        {
            id: 'health-male-teen-27',
            title: 'Journal of Growth',
            description: 'Write: "One puberty change I learned to handle is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-27'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/teen-growth-journal',
            index: 26
        },
        {
            id: 'health-male-teen-28',
            title: 'Simulation: Teen Routine',
            description: 'Teen builds a routine: Shower + Exercise + Study. Which is correct? → Balanced routine.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-28'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/teen-routine-simulation',
            index: 27
        },
        {
            id: 'health-male-teen-29',
            title: 'Reflex Healthy',
            description: 'Tap 🥗 for "Healthy Food + Sleep," ❌ for "Skipping Meals."',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-29'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-healthy-teen',
            index: 28
        },
        {
            id: 'health-male-teen-30',
            title: 'Badge: Puberty Smart',
            description: 'Handle 5 puberty scenarios responsibly to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-30'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/puberty-smart-teen-badge',
            index: 29
        },
        {
            id: 'health-male-teen-31',
            title: 'Puberty Health Story',
            description: 'Teacher explains reproductive health as part of growing up. What should you do? → Listen calmly.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-31'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/puberty-health-story-teen',
            index: 30
        },
        {
            id: 'health-male-teen-32',
            title: 'Quiz on Puberty Health',
            description: 'Test your knowledge on puberty health and hygiene!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-32'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-puberty-health-teen',
            index: 31
        },
        {
            id: 'health-male-teen-33',
            title: 'Reflex Puberty Health',
            description: 'Quick! React to puberty health scenarios!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-33'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-puberty-health-teen',
            index: 32
        },
        {
            id: 'health-male-teen-34',
            title: 'Puzzle: Puberty Health',
            description: 'Match health concepts with their meanings!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-34'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/puberty-health-puzzle-teen',
            index: 33
        },
        {
            id: 'health-male-teen-35',
            title: 'Shaving Story',
            description: 'Learn the basics of shaving safely!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-35'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/shaving-story-teen',
            index: 34
        },
        {
            id: 'health-male-teen-36',
            title: 'Debate: Shaving',
            description: 'Debate common myths and facts about shaving!',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-36'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/shaving-debate-teen',
            index: 35
        },
        {
            id: 'health-male-teen-37',
            title: 'Journal of Teen Hygiene',
            description: 'Reflect on your personal hygiene habits.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-37'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/teen-hygiene-journal',
            index: 36
        },
        {
            id: 'health-male-teen-38',
            title: 'Simulation: Teen Shaving',
            description: 'Simulate the shaving process step-by-step!',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-38'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/teen-shaving-simulation',
            index: 37
        },
        {
            id: 'health-male-teen-39',
            title: 'Reflex Shaving',
            description: 'Quick decisions for a safe shave!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-39'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-shaving-teen',
            index: 38
        },
        {
            id: 'health-male-teen-40',
            title: 'Badge: Shaving Pro',
            description: 'Earn your badge by mastering shaving knowledge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-40'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/shaving-pro-badge-teen',
            index: 39
        },
        {
            id: 'health-male-teen-41',
            title: 'Sweat Control Story',
            description: 'Teen plays sports. Should he shower after? → Yes, always.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-41'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/sweat-control-story',
            index: 40
        },
        {
            id: 'health-male-teen-42',
            title: 'Quiz on Hygiene',
            description: 'Which helps reduce acne? (a) Gentle wash, (b) Squeezing pimples). Correct = Gentle wash.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-42'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-hygiene',
            index: 41
        },
        {
            id: 'health-male-teen-43',
            title: 'Reflex Smart Hygiene',
            description: 'Tap 🚿 for "Daily Bath," ❌ for "Skip Hygiene."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-43'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-smart-hygiene-43',
            index: 42
        },
        {
            id: 'health-male-teen-44',
            title: 'Puzzle: Hygiene Tools',
            description: 'Match "Shaving Kit → Beard, Soap → Body, Face Wash → Acne."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-44'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/hygiene-tools-puzzle-44',
            index: 43
        },
        {
            id: 'health-male-teen-45',
            title: 'Night Sweat Story',
            description: 'Teen has night sweats. Should he ignore or shower? → Shower.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-45'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/night-sweat-story',
            index: 44
        },
        {
            id: 'health-male-teen-46',
            title: 'Debate: Hygiene = Confidence?',
            description: 'Does hygiene increase confidence in teens? → Yes.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-46'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/hygiene-confidence-debate-46',
            index: 45
        },
        {
            id: 'health-male-teen-47',
            title: 'Journal of Care',
            description: 'Write: "One hygiene challenge I overcame is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-47'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/journal-of-care',
            index: 46
        },
        {
            id: 'health-male-teen-48',
            title: 'Simulation: Daily Routine',
            description: 'Options: (a) Shower + Brush, (b) Only Brush, (c) Skip Both. Correct = Shower + Brush.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-48'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/daily-routine-simulation-48',
            index: 47
        },
        {
            id: 'health-male-teen-49',
            title: 'Reflex Hygiene Alert',
            description: 'Tap 👕 for "Fresh Clothes," ❌ for "Repeat Dirty Clothes."',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-49'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-hygiene-alert-49',
            index: 48
        },
        {
            id: 'health-male-teen-50',
            title: 'Badge: Hygiene Pro',
            description: 'Complete all hygiene mastery activities to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-teen-50'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/hygiene-pro-badge-50',
            index: 49
        },
        {
            id: 'health-male-teen-51',
            title: 'Stress Story',
            description: 'Exams coming. Should you take breaks or study nonstop? → Take breaks.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-51'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/stress-story',
            index: 50
        },
        {
            id: 'health-male-teen-52',
            title: 'Quiz on Stress Relief',
            description: 'Which reduces stress? (a) Sleep + Exercise, (b) Worry More). Correct = Sleep + Exercise.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-52'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-stress-relief',
            index: 51
        },
        {
            id: 'health-male-teen-53',
            title: 'Reflex Stress Check',
            description: 'Tap 💬 for "Talk to Friend," 🤐 for "Bottle Emotions."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-53'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-stress-check',
            index: 52
        },
        {
            id: 'health-male-teen-54',
            title: 'Puzzle: Mind-Body Match',
            description: 'Match "Exercise → Energy, Sleep → Relax, Deep Breath → Calm."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-54'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/mind-body-match-puzzle',
            index: 53
        },
        {
            id: 'health-male-teen-55',
            title: 'Body Image Story',
            description: 'Teen feels short compared to peers. Should he feel worthless? → No.',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-55'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/body-image-story',
            index: 54
        },
        {
            id: 'health-male-teen-56',
            title: 'Debate: Boys Should Not Cry?',
            description: 'Is crying weakness or natural? → Natural.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-56'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/boys-should-not-cry-debate',
            index: 55
        },
        {
            id: 'health-male-teen-57',
            title: 'Journal of Stress',
            description: 'Write: "One way I reduce stress is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-57'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/journal-of-stress',
            index: 56
        },
        {
            id: 'health-male-teen-58',
            title: 'Simulation: Teen Stress Day',
            description: 'Teen has exams + sports. Choose: Relax + Plan or Panic. Correct = Relax + Plan.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-58'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/teen-stress-day-simulation',
            index: 57
        },
        {
            id: 'health-male-teen-59',
            title: 'Reflex Emotional Health',
            description: 'Tap 👨‍🏫 for "Talk to Mentor," ❌ for "Hide Stress."',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-59'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-emotional-health',
            index: 58
        },
        {
            id: 'health-male-teen-60',
            title: 'Badge: Emotion Smart Teen',
            description: 'Handle 5 emotional health scenarios to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-60'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/emotion-smart-teen-badge',
            index: 59
        },
        {
            id: 'health-male-teen-61',
            title: 'Masculinity Story',
            description: 'Teen hears "Real men don\'t cry." Should he believe? → No, feelings are human.',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-61'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/masculinity-story',
            index: 60
        },
        {
            id: 'health-male-teen-62',
            title: 'Quiz on Masculinity Myths',
            description: 'Which is true? (a) Men must fight, (b) Men can show emotions). Correct = Men can show emotions.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-62'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-masculinity-myths',
            index: 61
        },
        {
            id: 'health-male-teen-63',
            title: 'Reflex Masculinity Check',
            description: 'Tap 💪 for "Kind & Strong," ❌ for "Tough Only."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-63'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-masculinity-check',
            index: 62
        },
        {
            id: 'health-male-teen-64',
            title: 'Puzzle: Masculinity Myths',
            description: 'Match "Real Men Help → True, Men Can\'t Cry → False, Men Respect Women → True."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-64'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/masculinity-myths-puzzle',
            index: 63
        },
        {
            id: 'health-male-teen-65',
            title: 'Violence Story',
            description: 'Peer says: "Be a man, fight him." Should you? → No.',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-65'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/violence-story',
            index: 64
        },
        {
            id: 'health-male-teen-66',
            title: 'Debate: Emotions = Weakness?',
            description: 'Is showing emotions weak or strong? → Strong.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-66'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/emotions-equals-weakness-debate',
            index: 65
        },
        {
            id: 'health-male-teen-67',
            title: 'Journal of Masculinity',
            description: 'Write: "Being a good man means ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-67'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/journal-of-masculinity',
            index: 66
        },
        {
            id: 'health-male-teen-68',
            title: 'Simulation: Respect Women',
            description: 'Teen hears friends make rude jokes about girls. Should he join or stop? → Stop.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-68'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/respect-women-simulation',
            index: 67
        },
        {
            id: 'health-male-teen-69',
            title: 'Reflex Respect Check',
            description: 'Tap 🤝 for "Help Others," ❌ for "Mock Others."',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-69'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-respect-check',
            index: 68
        },
        {
            id: 'health-male-teen-70',
            title: 'Badge: Healthy Man Teen',
            description: 'Complete 5 masculinity myth-busting tasks to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-70'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/healthy-man-teen-badge',
            index: 69
        },
        {
            id: 'health-male-teen-71',
            title: 'Checkup Story',
            description: 'Teen feels weak often. Should he go for a health check? → Yes.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-71'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/checkup-story',
            index: 70
        },
        {
            id: 'health-male-teen-72',
            title: 'Quiz on Preventive Health',
            description: 'Which is preventive care? (a) Vaccines, (b) Ignoring fever). Correct = Vaccines.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-72'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-preventive-health',
            index: 71
        },
        {
            id: 'health-male-teen-73',
            title: 'Reflex Preventive Health',
            description: 'Tap 🏥 for "Regular Checkups," ❌ for "Avoid Doctor."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-73'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-preventive-health',
            index: 72
        },
        {
            id: 'health-male-teen-74',
            title: 'Puzzle: Doctor Tools',
            description: 'Match "Stethoscope → Heart, Thermometer → Fever, Vaccine → Protection."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-74'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/doctor-tools-puzzle',
            index: 73
        },
        {
            id: 'health-male-teen-75',
            title: 'Specialist Story',
            description: 'Teen has acne problem. Should he see dermatologist? → Yes.',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-teen-75'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/specialist-story',
            index: 74
        },
        {
            id: 'health-male-teen-76',
            title: 'Debate: Doctor Fear',
            description: 'Is visiting doctors scary or safe? → Safe.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-76'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/doctor-fear-debate',
            index: 75
        },
        {
            id: 'health-male-teen-77',
            title: 'Journal of Doctor Visits',
            description: 'Write: "One time I visited a doctor for ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-77'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/journal-of-doctor-visits',
            index: 76
        },
        {
            id: 'health-male-teen-78',
            title: 'Simulation: Clinic Visit',
            description: 'Teen books a doctor visit. Choose: Wait calmly, Panic, Leave. Correct = Wait calmly.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-78'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/clinic-visit-simulation',
            index: 77
        },
        {
            id: 'health-male-teen-79',
            title: 'Reflex Teen Safety',
            description: 'Tap 💊 for "Take Medicines Properly," ❌ for "Skip Doses."',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-79'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-teen-safety',
            index: 78
        },
        {
            id: 'health-male-teen-80',
            title: 'Badge: Preventive Health Teen',
            description: 'Complete 5 preventive health activities to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-80'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/preventive-health-teen-badge',
            index: 79
        },
        {
            id: 'health-male-teen-81',
            title: 'Peer Pressure Story',
            description: 'Friends say "Try smoking once." Should you? → No.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-81'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/peer-pressure-story',
            index: 80
        },
        {
            id: 'health-male-teen-82',
            title: 'Quiz on Dangers',
            description: 'Smoking causes? (a) Stronger lungs, (b) Cancer, (c) Healthy teeth). Correct = Cancer.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-82'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-on-dangers',
            index: 81
        },
        {
            id: 'health-male-teen-83',
            title: 'Reflex Teen Choice',
            description: 'Tap ⚽ for "Sports," ❌ for "Alcohol."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-83'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-teen-choice',
            index: 82
        },
        {
            id: 'health-male-teen-84',
            title: 'Puzzle: Effects',
            description: 'Match "Smoking → Lung Damage, Alcohol → Liver Damage, Drugs → Brain Damage."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-84'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/effects-puzzle',
            index: 83
        },
        {
            id: 'health-male-teen-85',
            title: 'Substance Story',
            description: 'Teen at party sees drugs. Should he take them? → No.',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-85'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/substance-story',
            index: 84
        },
        {
            id: 'health-male-teen-86',
            title: 'Debate: Cool or Fool?',
            description: 'Is smoking/drinking cool or harmful? → Harmful.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-86'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/cool-or-fool-debate',
            index: 85
        },
        {
            id: 'health-male-teen-87',
            title: 'Journal of Awareness',
            description: 'Write: "Substance I will never try is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-87'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/journal-of-awareness',
            index: 86
        },
        {
            id: 'health-male-teen-88',
            title: 'Simulation: Peer Pressure',
            description: 'Teen is pressured at a party. Options: Say No, Walk Away, Join. Correct = Say No/Walk Away.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-88'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/peer-pressure-simulation',
            index: 87
        },
        {
            id: 'health-male-teen-89',
            title: 'Reflex Safe Teen',
            description: 'Tap 🩺 for "Doctor Advice," ❌ for "Drug Use."',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-89'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-safe-teen',
            index: 88
        },
        {
            id: 'health-male-teen-90',
            title: 'Badge: Drug-Free Teen',
            description: 'Complete 5 refusal scenarios to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-90'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/drug-free-teen-badge',
            index: 89
        },
        {
            id: 'health-male-teen-91',
            title: 'Routine Story',
            description: 'Teen wakes up late every day. Should he fix his routine? → Yes.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-91'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/routine-story',
            index: 90
        },
        {
            id: 'health-male-teen-92',
            title: 'Quiz on Teen Habits',
            description: 'Which supports health? (a) Sleep + balanced diet, (b) Skipping meals). Correct = Sleep + balanced diet.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-92'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/quiz-teen-habits',
            index: 91
        },
        {
            id: 'health-male-teen-93',
            title: 'Reflex Teen Routine',
            description: 'Tap ⏰ for "Discipline," ❌ for "Laziness."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-93'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-teen-routine',
            index: 92
        },
        {
            id: 'health-male-teen-94',
            title: 'Puzzle: Habit Builder',
            description: 'Match "Water → Hydration, Sports → Fitness, Study → Focus."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-94'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/habit-builder-puzzle',
            index: 93
        },
        {
            id: 'health-male-teen-95',
            title: 'Discipline Story',
            description: 'Teen skips all chores. Should he change this? → Yes, chores build responsibility.',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-95'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/discipline-story',
            index: 94
        },
        {
            id: 'health-male-teen-96',
            title: 'Debate: Discipline = Freedom?',
            description: 'Does discipline give freedom or restrict life? → Gives freedom.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-96'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/discipline-equals-freedom-debate',
            index: 95
        },
        {
            id: 'health-male-teen-97',
            title: 'Journal of Teen Habits',
            description: 'Write: "One good habit I built as a teen is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-97'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/journal-of-teen-habits',
            index: 96
        },
        {
            id: 'health-male-teen-98',
            title: 'Simulation: Time Management',
            description: 'Teen has exams + sports. Options: Balance time / Waste time. Correct = Balance time.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-98'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/time-management-simulation',
            index: 97
        },
        {
            id: 'health-male-teen-99',
            title: 'Reflex Teen Alert',
            description: 'Tap 🔄 for "Consistency," ❌ for "Skipping Habits."',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-99'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/reflex-teen-alert',
            index: 98
        },
        {
            id: 'health-male-teen-100',
            title: 'Badge: Lifelong Healthy Man',
            description: 'Complete all healthy habit challenges to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-teen-100'] || false,
            isSpecial: true,
            path: '/student/health-male/teens/lifelong-healthy-man-badge',
            index: 99
        }
    ]
    return healthMaleGamesTeens;
};
