import {
  Star,
  Zap,
  Gamepad2,
  Brain,
  Globe,
  Target,
  Cpu,
  Smartphone,
  Eye,
  Smile,
  MessageSquare,
  Home,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const aiGamesTeenIds = buildIds('ai', 'teen');

export const getAiTeenGames = (gameCompletionStatus)=> {
    const aiGamesTeen = [
        {
          id: "ai-teen-1",
          title: "What is AI? Quiz",
          description: "Define what AI stands for",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-1"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/what-is-ai-quiz",
          index: 0,
        },
        {
          id: "ai-teen-2",
          title: "Pattern Prediction Puzzle",
          description: "Predict the next number in sequences",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-2"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/pattern-prediction-puzzle",
          index: 1,
        },
        {
          id: "ai-teen-3",
          title: "Image Classifier Game",
          description: "Sort images into categories",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-3"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/image-classifier-game",
          index: 2,
        },
        {
          id: "ai-teen-4",
          title: "Human vs AI Quiz",
          description: "Is Google Translate powered by AI?",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-4"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/human-vs-ai-quiz",
          index: 3,
        },
        {
          id: "ai-teen-5",
          title: "Predict the Next Word",
          description: "Complete sentences like GPT does",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-5"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/predict-next-word",
          index: 4,
        },
        {
          id: "ai-teen-6",
          title: "Self-Driving Car Reflex",
          description: "React fast to traffic lights",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-6"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/self-driving-car-reflex",
          index: 5,
        },
        {
          id: "ai-teen-7",
          title: "Sorting Emotions Game",
          description: "Classify emotions from emojis",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-7"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/sorting-emotions-game",
          index: 6,
        },
        {
          id: "ai-teen-8",
          title: "True or False AI Quiz",
          description: "Is a calculator AI?",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-8"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/true-false-ai-quiz",
          index: 7,
        },
        {
          id: "ai-teen-9",
          title: "Chatbot Simulation",
          description: "Have a conversation with an AI bot",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-9"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/chatbot-simulation",
          index: 8,
        },
        {
          id: "ai-teen-10",
          title: "AI in Gaming Story",
          description: "Who controls video game enemies?",
          icon: <Gamepad2 className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-10"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-in-gaming-story",
          index: 9,
        },
        {
          id: "ai-teen-11",
          title: "Pattern Music Reflex",
          description: "Repeat rhythm patterns",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-11"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/pattern-music-reflex",
          index: 10,
        },
        {
          id: "ai-teen-12",
          title: "Computer Vision Basics",
          description: "Identify objects with AI eyes",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-12"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/computer-vision-basics",
          index: 11,
        },
        {
          id: "ai-teen-13",
          title: "AI in Smartphones Quiz",
          description: "Does face unlock use AI?",
          icon: <Smartphone className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-13"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-in-smartphones-quiz",
          index: 12,
        },
        {
          id: "ai-teen-14",
          title: "Prediction Story",
          description: "How AI forecasts weather",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-14"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/prediction-story",
          index: 13,
        },
        {
          id: "ai-teen-15",
          title: "Machine vs Human Reflex",
          description: "Identify Human or AI quickly",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-15"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/machine-vs-human-reflex",
          index: 14,
        },
        {
          id: "ai-teen-16",
          title: "Language AI Quiz",
          description: "Is Google Translate an AI?",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-16"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/language-ai-quiz",
          index: 15,
        },
        {
          id: "ai-teen-17",
          title: "Simple Algorithm Puzzle",
          description: "Arrange steps to solve a problem",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-17"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/simple-algorithm-puzzle",
          index: 16,
        },
        {
          id: "ai-teen-18",
          title: "Smart Home Story",
          description: "How AI controls smart homes",
          icon: <Home className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-18"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/smart-home-story",
          index: 17,
        },
        {
          id: "ai-teen-19",
          title: "Recommendation Simulation",
          description: "How AI recommends content",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-19"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/recommendation-simulation",
          index: 18,
        },
        {
          id: "ai-teen-20",
          title: "AI Everywhere Quiz",
          description: "Understand AI's reach in our world",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-20"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-everywhere-quiz",
          index: 19,
        },
        {
          id: "ai-teen-21",
          title: "Spam Filter Reflex",
          description: "Identify spam vs real messages",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-21"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/spam-filter-reflex",
          index: 20,
        },
        {
          id: "ai-teen-22",
          title: "Robot Vision Mistake",
          description: "Correct robot mistakes like 'Cow = Dog'",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-22"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/robot-vision-mistake",
          index: 21,
        },
        {
          id: "ai-teen-23",
          title: "AI vs Tools Quiz",
          description: "Decide if everyday tools are AI or not",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-23"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-vs-tools-quiz",
          index: 22,
        },
        {
          id: "ai-teen-24",
          title: "Future of AI Reflection",
          description: "Write one thing AI can do in 2050",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-24"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/future-of-ai-reflection",
          index: 23,
        },
        {
          id: "ai-teen-25",
          title: "Ai Basics Badge",
          description: "Complete 10 AI basics games to earn badge",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10+ min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-25"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-basics-badge",
          index: 24,
        },
        {
          id: "ai-teen-26",
          title: "Smart Maps Story",
          description: "Use AI for fastest navigation",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-26"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/smart-maps-story",
          index: 25,
        },
        {
          id: "ai-teen-27",
          title: "Voice Assistant Reflex",
          description: "Click Siri/Alexa when instructed",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-27"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/voice-assistant-reflex",
          index: 26,
        },
        {
          id: "ai-teen-28",
          title: "Social Media Recommendation Game",
          description: "AI suggests content based on likes",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-28"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/social-media-recommendation-game",
          index: 27,
        },
        {
          id: "ai-teen-29",
          title: "Face Unlock Simulation",
          description: "Unlock phone with correct face",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-29"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/face-unlock-simulation",
          index: 28,
        },
        {
          id: "ai-teen-30",
          title: "E-commerce AI Story",
          description: "AI suggests products while shopping online",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-30"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/e-commerce-ai-story",
          index: 29,
        },
        {
          id: "ai-teen-31",
          title: "Ai Doctor Quizz",
          description: "Decide if AI can detect diseases from X-rays",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-31"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-doctor-quizz",
          index: 30,
        },
        {
          id: "ai-teen-32",
          title: "Music Playlist AI",
          description: "Create a playlist based on teen's music preferences",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-32"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/music-playlist-ai",
          index: 31,
        },
        {
          id: "ai-teen-33",
          title: "Airport Security Story",
          description: "AI helps detect dangerous items in luggage",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-33"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/airport-security-story",
          index: 32,
        },
        {
          id: "ai-teen-34",
          title: "AI Translator Reflex",
          description: "Click correct translation when word appears",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-34"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-translator-reflex",
          index: 33,
        },
        {
          id: "ai-teen-35",
          title: "AI in Farming Story",
          description: "AI forecasts help farmers decide when to water crops",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-35"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-in-farming-story",
          index: 34,
        },
        {
          id: "ai-teen-36",
          title: "AI in Banking Quiz",
          description: "Decide if ATM fraud detection uses AI",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-36"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-in-banking-quiz",
          index: 35,
        },
        {
          id: "ai-teen-37",
          title: "News Recommendation Game",
          description: "AI recommends news based on teen interests",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-37"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/news-recommendation-game",
          index: 36,
        },
        {
          id: "ai-teen-38",
          title: "Self-Driving Car Reflex 2",
          description: "Click correct traffic signals for autonomous vehicle",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-38"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/self-driving-car-reflexx",
          index: 37,
        },
        {
          id: "ai-teen-39",
          title: "Smartwatch Health Story",
          description: "AI monitors heartbeat and alerts teen",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-39"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/smartwatch-health-story",
          index: 38,
        },
        {
          id: "ai-teen-40",
          title: "Smart City Traffic Game",
          description: "Follow AI traffic signals in urban simulation",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-40"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/smart-city-traffic-gamee",
          index: 39,
        },
        {
          id: "ai-teen-41",
          title: "AI Artist Simulation",
          description: "Generate drawings using AI based on teen input",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-41"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-artist-simulation",
          index: 40,
        },
        {
          id: "ai-teen-42",
          title: "Online Safety Quiz",
          description: "Decide if sharing password with AI is safe",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-42"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/online-safety-quiz",
          index: 41,
        },
        {
          id: "ai-teen-43",
          title: "AI in Games Story",
          description: "See how AI controls video game enemies",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-43"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-in-games-story",
          index: 42,
        },
        {
          id: "ai-teen-44",
          title: "Fraud Detector Reflex",
          description: "Click 'Fraud' for suspicious messages",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-44"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/fraud-detector-reflex",
          index: 43,
        },
        {
          id: "ai-teen-45",
          title: "AI in Movies Quiz",
          description: "Decide if Netflix uses AI to suggest films",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-45"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-in-movies-quiz",
          index: 44,
        },
        {
          id: "ai-teen-46",
          title: "Smart Farming Reflex",
          description: "Click correct action based on weather for crops",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-46"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/smart-farming-reflex",
          index: 45,
        },
        {
          id: "ai-teen-47",
          title: "AI Teacher Story",
          description: "Online tutor adjusts difficulty using AI",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-47"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-teacher-story",
          index: 46,
        },
        {
          id: "ai-teen-48",
          title: "Cybersecurity AI Quiz",
          description: "Decide if AI can detect hackers",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-48"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/cybersecurity-ai-quiz",
          index: 47,
        },
        {
          id: "ai-teen-49",
          title: "Smart Home Simulation",
          description: "AI controls home lights; teen confirms action",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-49"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/smart-home-simulation",
          index: 48,
        },
        {
          id: "ai-teen-50",
          title: "AI Explorer Badge",
          description: "Complete 10 daily AI games to earn badge",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10+ min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-50"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-explorer-badge",
          index: 49,
        },
        {
          id: "ai-teen-51",
          title: "Data Labeling Game",
          description: "Drag images to correct categories. Robot learns supervised basics.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-51"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/data-labeling-gamee",
          index: 50,
        },
        {
          id: "ai-teen-52",
          title: "Bad Data Story",
          description:"AI trained on wrong labels → learns incorrectly. Teen corrects it.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-52"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/bad-data-story",
          index: 51,
        },
        {
          id: "ai-teen-53",
          title: "Missing Data Puzzle",
          description:"AI can’t answer due to missing info. Teen adds correct data.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-53"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/missing-data-puzzlee",
          index: 52,
        },
        {
          id: "ai-teen-54",
          title: "Train with Sounds",
          description:"Hear sound → click correct animal. Reinforces audio recognition.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-54"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/train-with-sounds",
          index: 53,
        },
        {
          id: "ai-teen-55",
          title: "Overfitting Story",
          description:"AI trained on limited data fails on new input. Teen learns variety helps.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-55"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/overfitting-storyy",
          index: 54,
        },
        {
          id: "ai-teen-56",
          title: "AI Mistake Reflex",
          description: "Robot gives wrong answer. Teen clicks 'Correct it.'",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-56"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-mistake-reflex",
          index: 55,
        },
        {
          id: "ai-teen-57",
          title: "Data Diversity Story",
          description:"AI trained only on limited data → teen adds diversity to improve fairness.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-57"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/data-diversity-story",
          index: 56,
        },
        {
          id: "ai-teen-58",
          title: "Training Accuracy Game",
          description: "Each correct correction fills AI’s 'accuracy bar'.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-58"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/training-accuracy-game",
          index: 57,
        },
        {
          id: "ai-teen-59",
          title: "Label Error Puzzle",
          description: "Incorrect labeling → robot fails. Teen corrects it.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-59"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/label-error-puzzle",
          index: 58,
        },
        {
          id: "ai-teen-60",
          title: "AI Training Badge",
          description: "Finish 5 training games to earn badge.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10+ min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-60"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-training-badgee",
          index: 59,
        },
        {
          id: "ai-teen-61",
          title: "Dataset Builder Simulation",
          description: "Collect images, sounds, and words to build datasets.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-61"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/dataset-builder-simulation",
          index: 60,
        },
        {
          id: "ai-teen-62",
          title: "Bias in Data Quiz",
          description: "Will AI trained only on city photos work in villages?",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-62"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/bias-in-data-quiz",
          index: 61,
        },
        {
          id: "ai-teen-63",
          title: "Robot Confusion Story",
          description:"AI mistakes lion for tiger. Teen corrects with better data.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-63"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/robot-confusion-storyy",
          index: 62,
        },
        {
          id: "ai-teen-64",
          title: "Feedback Loop Reflex",
          description: "AI asks Correct/Incorrect? Teen clicks correct option each time.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-64"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/feedback-loop-reflex",
          index: 63,
        },
        {
          id: "ai-teen-65",
          title: "Small Data vs Big Data Story",
          description: "Compare AI trained on few vs many examples; teen sees difference.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-65"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/small-vs-big-data-story",
          index: 64,
        },
        {
          id: "ai-teen-66",
          title: "Robot Exam Game",
          description:"AI fails test with limited training; teen retrains with variety.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-66"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/robot-exam-game",
          index: 65,
        },
        {
          id: "ai-teen-67",
          title: "Data Cleaning Reflex",
          description: "Click Keep/Delete on clear vs blurry photos to teach preprocessing.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-67"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/data-cleaning-reflex",
          index: 66,
        },
        {
          id: "ai-teen-68",
          title: "AI Bias Roleplay",
          description: "AI hiring only boys. Teen adjusts to include girls for fairness.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-68"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-bias-roleplay",
          index: 67,
        },
        {
          id: "ai-teen-69",
          title: "Wrong Prediction Quiz",
          description: "Can AI always be right? Teen learns AI has limits.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-69"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/wrong-prediction-quizz",
          index: 68,
        },
        {
          id: "ai-teen-70",
          title: "Pattern vs Noise Game",
          description:"Pick correct training data from noisy vs clean patterns.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-70"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/pattern-vs-noise-game",
          index: 69,
        },
        {
          id: "ai-teen-71",
          title: "Teach AI Emotions",
          description: "Drag items into Happy or Sad. Robot learns emotions.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-71"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/teach-ai-emotions",
          index: 70,
        },
        {
          id: "ai-teen-72",
          title: "Training Feedback Story",
          description:"Robot improves only after teacher feedback. Teen selects 'Give Feedback'.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-72"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/training-feedback-story",
          index: 71,
        },
        {
          id: "ai-teen-73",
          title: "Human vs AI Errors Quiz",
          description: "Can humans make mistakes like AI? Teen learns yes.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-73"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/human-vs-ai-errors-quiz",
          index: 72,
        },
        {
          id: "ai-teen-74",
          title: "Balanced Data Story",
          description: "AI trained only on daylight photos fails at night. Teen adds night photos.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-74"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/balanced-data-story",
          index: 73,
        },
        {
          id: "ai-teen-75",
          title: "Training Hero Badge",
          description:"Complete 10 training & bias games → badge 'AI Teacher'.",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-75"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/training-hero-badgee",
          index: 74,
        },
        {
          id: "ai-teen-76",
          title: "Good AI vs Bad AI Quiz",
          description:"AI used for helping hospitals = Good AI? Teen learns yes.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-76"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/good-ai-vs-bad-ai-quiz",
          index: 75,
        },
        {
          id: "ai-teen-77",
          title: "Privacy Protection Story",
          description: "AI asks for home address. Teen selects 'Keep private'.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-77"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/privacy-protection-story",
          index: 76,
        },
        {
          id: "ai-teen-78",
          title: "AI Bias Roleplay 2",
          description:"AI gives jobs only to boys. Teen corrects to include all for fairness.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-78"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-bias-roleplayy",
          index: 77,
        },
        {
          id: "ai-teen-79",
          title: "Fake News Detector Game",
          description:"Breaking News: Alien invasion today! Teen identifies as Fake.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-79"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/fake-news-detector-game",
          index: 78,
        },
        {
          id: "ai-teen-80",
          title: "AI Safety Reflex",
          description:"Robot flashes 'Help people' or 'Steal phone'. Teen clicks only 'Help'.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-80"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-safety-reflex",
          index: 79,
        },
        {
          id: "ai-teen-81",
          title: "Cyberbullying Story",
          description: "Robot posts mean comments online. Teen must report.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-81"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/cyberbullying-storyy",
          index: 80,
        },
        {
          id: "ai-teen-82",
          title: "Ethics in AI Quiz",
          description: "Should AI follow human laws? Teen learns Yes.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-82"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ethics-in-ai-quiz",
          index: 81,
        },
        {
          id: "ai-teen-83",
          title: "Human + AI Story",
          description:"AI diagnoses disease. Doctor gives final word. Teen observes human-in-loop.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-83"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/human-plus-ai-story",
          index: 82,
        },
        {
          id: "ai-teen-84",
          title: "Dangerous Robot Story",
          description: "Robot starts harming. Teen clicks 'Switch off' to stay safe.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-84"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/dangerous-robot-storyy",
          index: 83,
        },
        {
          id: "ai-teen-85",
          title: "Good Data vs Bad Data Puzzle",
          description:"Drag 'Clear photo = Good', 'Blurry photo = Bad'. Teen learns ethical dataset creation.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-85"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/good-vs-bad-data-puzzle",
          index: 84,
        },
        {
          id: "ai-teen-86",
          title: "AI & Jobs Debate",
          description:"AI replaces some jobs. Teen chooses 'Learn new skills' to adapt.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-86"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-jobs-debate",
          index: 85,
        },
        {
          id: "ai-teen-87",
          title: "Sustainability Quiz",
          description:"Can AI save electricity by turning off lights? Teen learns Yes.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-87"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/sustainability-quiz",
          index: 86,
        },
        {
          id: "ai-teen-88",
          title: "Robot Honesty Game",
          description: "Robot says 'Cheat to win.' Teen clicks 'No'.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-88"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/robot-honesty-game",
          index: 87,
        },
        {
          id: "ai-teen-89",
          title: "AI for Good Story",
          description:"AI helps blind person cross road. Teen clicks 'This is Good AI'.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-89"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-for-good-story",
          index: 88,
        },
        {
          id: "ai-teen-90",
          title: "Future of AI Quiz",
          description: "Will AI fly cars in 2050? Teen chooses 'Maybe'.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-90"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/future-of-ai-quiz",
          index: 89,
        },
        {
          id: "ai-teen-91",
          title: "Ethics Badge",
          description:"Complete 5 ethics activities to earn recognition for ethical choices.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "N/A",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-91"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ethics-badge",
          index: 90,
        },
        {
          id: "ai-teen-92",
          title: "AI & Human Roles Story",
          description: "Who should decide court judgment? Human judge or AI? Correct = Human.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-92"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-human-roles-story",
          index: 91,
        },
        {
          id: "ai-teen-93",
          title: "Cyber Safety Reflex",
          description:"Messages flash: 'Click unknown link' vs 'Stay safe.' Teen clicks 'Stay safe.'",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-93"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/cyber-safety-reflex",
          index: 92,
        },
        {
          id: "ai-teen-94",
          title: "Global Fairness Quiz",
          description: "Should boys and girls have equal digital rights? Correct = Yes.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-94"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/global-fairness-quiz",
          index: 93,
        },
        {
          id: "ai-teen-95",
          title: "AI & Space Story",
          description:"AI helps astronauts on Mars. Teen observes that humans control it.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-95"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-space-story",
          index: 94,
        },
        {
          id: "ai-teen-96",
          title: "AI & Creativity Simulation",
          description:"Teen types 'Write a poem.' AI generates poem. Teen reflects on creativity.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-96"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-creativity-simulation",
          index: 95,
        },
        {
          id: "ai-teen-97",
          title: "Empathy & AI Roleplay",
          description:"AI says 'I am sad.' Teen clicks 'Comfort' to practice empathy.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-97"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/empathy-ai-roleplay",
          index: 96,
        },
        {
          id: "ai-teen-98",
          title: "AI Career Quiz",
          description: "Which jobs use AI? (A) Doctor, (B) Engineer, (C) Teacher, (D) All. Correct = D.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-98"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-career-quiz",
          index: 97,
        },
        {
          id: "ai-teen-99",
          title: "Future Journal",
          description: "Write 'One job I think AI will create in 2050.'",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-99"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/future-journal",
          index: 98,
        },
        {
          id: "ai-teen-100",
          title: "AI Explorer Hero Badge",
          description:"Finish all 25 ethics/future games for full AI literacy recognition.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "N/A",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-teen-100"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/teen/ai-explorer-hero-badgee",
          index: 99,
        },
      ];

    return aiGamesTeen;
}
