import {
  Trophy, 
  Coins, 
  Puzzle, 
  Users, 
  Calendar, 
  Star, 
  Zap,  
  Heart, 
  Target, 
  BookOpen, 
  GraduationCap, 
  HandHeart, 
  Eye, 
  Smile, 
  MessageSquare, 
  Flag,  
  Home,  
  Sun, 
  Book,  
  HelpCircle,  
  HeartHandshake, 
  Image, 
  AlertTriangle, 
  HandHelping, 
  Layers, 
  Notebook, 
  Drama, 
  Monitor, 
  ShieldCheck, 
  Wind, 
  Feather, 
  Settings, 
  Coffee, 
  Ear, 
  Volume, 
  Map, 
  Scale, 
  Eraser, 
  ListChecks, 
  CheckSquare, 
  Clock, 
} from "lucide-react";
import buildIds from "../buildGameIds";


export const uvlsGamesKidsIds = buildIds("uvls", "kids")

export const getUvlsKidsGames = (gameCompletionStatus)=> {
    const uvlsGamesKid = [
        {
          id: "uvls-kids-1",
          title: "Share Your Toy",
          description: "Practice simple sharing in play",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-1"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/share-your-toy",
          index: 0,
        },
        {
          id: "uvls-kids-2",
          title: "Feelings Quiz",
          description: "Recognize caregiving actions",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-2"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/feelings-quiz",
          index: 1,
        },
        {
          id: "uvls-kids-3",
          title: "Kind Reflex",
          description: "Rapidly identify kind vs mean actions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-3"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/kind-reflex",
          index: 2,
        },
        {
          id: "uvls-kids-4",
          title: "Match Faces",
          description: "Link facial expressions to feelings",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-4"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/match-faces",
          index: 3,
        },
        {
          id: "uvls-kids-5",
          title: "Spot Help",
          description: "Notice peers who need help",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-5"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/spot-help",
          index: 4,
        },
        {
          id: "uvls-kids-6",
          title: "Kind Poster",
          description: "Express compassion visually",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-6"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/kind-poster",
          index: 5,
        },
        {
          id: "uvls-kids-7",
          title: "Mini Journal",
          description: "Put helping into words (very short)",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-7"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mini-journal",
          index: 6,
        },
        {
          id: "uvls-kids-8",
          title: "Comfort Roleplay",
          description: "Choose kind phrases to comfort a sad peer",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-8"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/comfort-roleplay",
          index: 7,
        },
        {
          id: "uvls-kids-9",
          title: "Share Reflex",
          description: "Reinforce sharing cue recognition",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-9"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/share-reflex",
          index: 8,
        },
        {
          id: "uvls-kids-10",
          title: "Little Empath Badge",
          description: "Encourage consistent small acts of empathy",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "Cumulative",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-10"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/little-empath-badge",
          index: 9,
        },
        {
          id: "uvls-kids-11",
          title: "Greet the New Kid",
          description: "Model welcoming behaviour",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-11"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/greet-the-new-kid",
          index: 10,
        },
        {
          id: "uvls-kids-12",
          title: "Polite Words Quiz",
          description: "Identify polite language",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-12"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/polite-words-quiz",
          index: 11,
        },
        {
          id: "uvls-kids-13",
          title: "Respect Tap",
          description: "Spot respectful actions quickly",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-13"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/respect-tap",
          index: 12,
        },
        {
          id: "uvls-kids-14",
          title: "Inclusion Match",
          description: "Link inclusive acts to positive outcomes",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-14"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusion-match",
          index: 13,
        },
        {
          id: "uvls-kids-15",
          title: "Invite to Play",
          description: "Practice inviting someone to join",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-15"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/invite-to-play",
          index: 14,
        },
        {
          id: "uvls-kids-16",
          title: "Inclusion Poster",
          description: 'Visualize "everyone belongs"',
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-16"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusion-poster",
          index: 15,
        },
        {
          id: "uvls-kids-17",
          title: "Inclusion Journal",
          description: "Reflect on an inclusion act (one line)",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-17"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusion-journal",
          index: 16,
        },
        {
          id: "uvls-kids-18",
          title: "Invite Roleplay",
          description: "Choose inviting phrases to include shy students",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-18"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/invite-roleplay",
          index: 17,
        },
        {
          id: "uvls-kids-19",
          title: "Respect Signals",
          description: "Recognize respect signals (eye contact, listening)",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-19"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/respect-signals",
          index: 18,
        },
        {
          id: "uvls-kids-20",
          title: "Inclusive Kid Badge",
          description: "Reinforce repeated inclusive actions",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "Cumulative",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-20"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusive-kid-badge",
          index: 19,
        },
        {
          id: "uvls-kids-21",
          title: "Share Chores",
          description:
            "Show chores are for everyone by assigning tasks fairly.",
          icon: <HandHelping className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-21"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/share-chores",
          index: 20,
        },
        {
          id: "uvls-kids-22",
          title: "Equality Quiz",
          description:
            "Understand equal access to education through simple MCQs.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-22"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/equality-quiz",
          index: 21,
        },
        {
          id: "uvls-kids-23",
          title: "Spot Stereotype",
          description:
            "Recognise and correct stereotyping in short statements.",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3–4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-23"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/spot-stereotype",
          index: 22,
        },
        {
          id: "uvls-kids-24",
          title: "Rights Match",
          description:
            "Match kids’ situations to basic rights like learn, play, and safety.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-24"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/rights-match",
          index: 23,
        },
        {
          id: "uvls-kids-25",
          title: "Encourage Dream",
          description: "Encourage peers’ ambitions without gender limits.",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-25"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/encourage-dream",
          index: 24,
        },
        {
          id: "uvls-kids-26",
          title: "Equality Poster",
          description:
            "Create a poster showing equal opportunity for everyone.",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-26"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/equality-poster",
          index: 25,
        },
        {
          id: "uvls-kids-27",
          title: "Role Model Journal",
          description:
            "Name a role model who broke stereotypes and inspired others.",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-27"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/role-model-journal",
          index: 26,
        },
        {
          id: "uvls-kids-28",
          title: "Support Roleplay",
          description:
            "Respond positively when someone feels discouraged in a roleplay.",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-28"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/support-roleplay",
          index: 27,
        },
        {
          id: "uvls-kids-29",
          title: "Challenge Stereotypes",
          description: "Tap to reject stereotypes and reinforce fairness.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "2–3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-29"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/challenge-stereotypes",
          index: 28,
        },
        {
          id: "uvls-kids-30",
          title: "Equality Ally Badge",
          description:
            "Complete 5 equality-support actions to earn your Equality Ally badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-30"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/equality-ally-badge",
          index: 29,
        },
        {
          id: "uvls-kids-31",
          title: "Stop the Tease",
          description:
            "Choose safe ways to intervene when someone is being teased.",
          icon: <HandHelping className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-31"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/stop-the-tease",
          index: 30,
        },
        {
          id: "uvls-kids-32",
          title: "Bullying Quiz",
          description:
            "Identify the difference between bullying, joking, and accidents.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-32"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/bullying-quiz",
          index: 31,
        },
        {
          id: "uvls-kids-33",
          title: "Report Reflex",
          description:
            "Tap quickly when you see a bullying icon to report it safely.",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-33"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/report-reflex",
          index: 32,
        },
        {
          id: "uvls-kids-34",
          title: "Types Match",
          description:
            "Match examples of physical, verbal, and cyber bullying.",
          icon: <Layers className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-34"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/types-match",
          index: 33,
        },
        {
          id: "uvls-kids-35",
          title: "Support Friend",
          description:
            "Choose kind and supportive actions for a bullied friend.",
          icon: <HeartHandshake className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-35"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/support-friend",
          index: 34,
        },
        {
          id: "uvls-kids-36",
          title: "Anti-Bullying Poster",
          description: "Create and share your own anti-bullying poster.",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-36"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/anti-bullying-poster",
          index: 35,
        },
        {
          id: "uvls-kids-37",
          title: "Witness Journal",
          description:
            "Reflect on a time you stood up for someone being bullied.",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-37"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/witness-journal",
          index: 36,
        },
        {
          id: "uvls-kids-38",
          title: "Bystander Roleplay",
          description:
            "Practice safe bystander actions through roleplay choices.",
          icon: <Drama className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-38"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/bystander-roleplay",
          index: 37,
        },
        {
          id: "uvls-kids-39",
          title: "Cyber Spot",
          description: "Identify harmful online posts and report them safely.",
          icon: <Monitor className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3–4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-39"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/cyber-spot",
          index: 38,
        },
        {
          id: "uvls-kids-40",
          title: "Peer Protector Badge",
          description: "Earn a badge for consistent anti-bullying actions.",
          icon: <ShieldCheck className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-40"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/peer-protector-badge",
          index: 39,
        },
        {
          id: "uvls-kids-41",
          title: "Name That Feeling",
          description:
            "Pick the correct emotion word from a short story scene.",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-41"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/name-that-feeling",
          index: 40,
        },
        {
          id: "uvls-kids-42",
          title: "Breathe with Me",
          description:
            "Practice simple breathing techniques using rhythm and animation.",
          icon: <Wind className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3–4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-42"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/breathe-with-me",
          index: 41,
        },
        {
          id: "uvls-kids-43",
          title: "Mood Match",
          description:
            "Match everyday behaviors with moods like happy, sad, or calm.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-43"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mood-match",
          index: 42,
        },
        {
          id: "uvls-kids-44",
          title: "Mood Journal",
          description: "Write a one-line entry about your mood and its reason.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5–7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-44"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mood-journal",
          index: 43,
        },
        {
          id: "uvls-kids-45",
          title: "Calm Choice",
          description: "Choose calm responses in moments of frustration.",
          icon: <Feather className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-45"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/calm-choice",
          index: 44,
        },
        {
          id: "uvls-kids-46",
          title: "Toolbox Poster",
          description:
            "Build your own calming tools poster with stickers and icons.",
          icon: <Settings className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-46"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/toolbox-poster",
          index: 45,
        },
        {
          id: "uvls-kids-47",
          title: "Ask for Help Roleplay",
          description: "Practice politely asking a teacher or adult for help.",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-47"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/ask-for-help-roleplay",
          index: 46,
        },
        {
          id: "uvls-kids-48",
          title: "Calm Reflex",
          description: "Tap quickly when calm behavior appears on screen.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-48"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/calm-reflex",
          index: 47,
        },
        {
          id: "uvls-kids-49",
          title: "Trigger Map Puzzle",
          description:
            "Match triggers to calming strategies and learn what works best.",
          icon: <Map className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-49"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/trigger-map-puzzle",
          index: 48,
        },
        {
          id: "uvls-kids-50",
          title: "Self-Aware Badge",
          description:
            "Earn your Self-Aware Badge by using emotion tools regularly.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-50"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/self-aware-badge",
          index: 49,
        },
        {
          id: "uvls-kids-51",
          title: "Snack Choice",
          description: "Choose based on hunger vs desire; basic trade-offs.",
          icon: <Coffee className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-51"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/snack-choice",
          index: 50,
        },
        {
          id: "uvls-kids-52",
          title: "Cause & Effect Quiz",
          description: "Relate actions to consequences simply.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-52"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/cause-effect-quiz",
          index: 51,
        },
        {
          id: "uvls-kids-53",
          title: "True/False Reflex",
          description: "Quick identification of true facts vs silly claims.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-53"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/true-false-reflex",
          index: 52,
        },
        {
          id: "uvls-kids-54",
          title: "Logic Puzzle",
          description: "Solve simple pattern or sequence puzzles.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-54"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/logic-puzzle",
          index: 53,
        },
        {
          id: "uvls-kids-55",
          title: "Risky Offer",
          description: "Make a safe choice when offered a risky shortcut.",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-55"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/risky-offer",
          index: 54,
        },
        {
          id: "uvls-kids-56",
          title: "Decision Poster",
          description: "Learn simple steps to decide: stop → think → choose.",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-56"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/decision-poster",
          index: 55,
        },
        {
          id: "uvls-kids-57",
          title: "Decision Journal",
          description: "Reflect on why you chose X today.",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-57"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/decision-journal",
          index: 56,
        },
        {
          id: "uvls-kids-58",
          title: "Ethics Roleplay",
          description: "Pick the honest option in a kid-appropriate situation.",
          icon: <Drama className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-58"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/ethics-roleplay",
          index: 57,
        },
        {
          id: "uvls-kids-59",
          title: "Spot Fallacy",
          description:
            "Identify clearly wrong reasoning with child-friendly examples.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-59"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/spot-fallacy",
          index: 58,
        },
        {
          id: "uvls-kids-60",
          title: "Critical Thinker Badge",
          description: "Reward consistent use of simple decision steps.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-60"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/critical-thinker-badge",
          index: 59,
        },
        {
          id: "uvls-kids-61",
          title: "Say Hello",
          description: "Practice polite greetings and eye contact.",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-61"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/say-hello",
          index: 60,
        },
        {
          id: "uvls-kids-62",
          title: "Active Listening Quiz",
          description: "Identify active listening behaviours.",
          icon: <Ear className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-62"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/active-listening-quiz",
          index: 61,
        },
        {
          id: "uvls-kids-63",
          title: "Stop & Listen Reflex",
          description: "Train the habit to stop and listen when signaled.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-63"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/stop-listen-reflex",
          index: 62,
        },
        {
          id: "uvls-kids-64",
          title: "Tone Match",
          description: "Match tone (happy/angry/soft) to intent.",
          icon: <Volume className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-64"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/tone-match",
          index: 63,
        },
        {
          id: "uvls-kids-65",
          title: "Ask Clearly Story",
          description: "Practice asking for help clearly.",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-65"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/ask-clearly-story",
          index: 64,
        },
        {
          id: "uvls-kids-66",
          title: "Communication Poster",
          description: "Show simple steps to speak clearly.",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-66"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/communication-poster",
          index: 65,
        },
        {
          id: "uvls-kids-67",
          title: "Feedback Journal",
          description:
            "Reflect on a time you received feedback and what you learned.",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-67"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/feedback-journal",
          index: 66,
        },
        {
          id: "uvls-kids-68",
          title: "Difficult Talk Roleplay",
          description: "Choose kind words for a gentle correction.",
          icon: <Drama className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-68"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/difficult-talk-roleplay",
          index: 67,
        },
        {
          id: "uvls-kids-69",
          title: "Empathic Tap",
          description: "Identify validating statements quickly.",
          icon: <HeartHandshake className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-69"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/empathic-tap",
          index: 68,
        },
        {
          id: "uvls-kids-70",
          title: "Good Communicator Badge",
          description:
            "Reward successful practice of listening & speaking tasks.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-70"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/good-communicator-badge",
          index: 69,
        },
        {
          id: "uvls-kids-71",
          title: "Toy Dispute",
          description: "Mediate toy dispute using share/turn rules.",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-71"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/toy-dispute",
          index: 70,
        },
        {
          id: "uvls-kids-72",
          title: "Win-Win Quiz",
          description: "Identify win-win conflict solutions.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-72"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/win-win-quiz",
          index: 71,
        },
        {
          id: "uvls-kids-73",
          title: "Calm Reflex",
          description: "Choose calming tactics quickly in conflict prompts.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-73"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/calm-reflexx",
          index: 72,
        },
        {
          id: "uvls-kids-74",
          title: "Resolve Steps Puzzle",
          description: "Arrange mediation steps in correct order.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-74"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/resolve-steps-puzzle",
          index: 73,
        },
        {
          id: "uvls-kids-75",
          title: "Split Fairly Roleplay",
          description: "Negotiate fair sharing of limited resources.",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-75"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/split-fairly-roleplay",
          index: 74,
        },
        {
          id: "uvls-kids-76",
          title: "Mediation Poster",
          description: "Create poster showing mediation steps.",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-76"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mediation-poster",
          index: 75,
        },
        {
          id: "uvls-kids-77",
          title: "Resolution Journal",
          description: "Write about a conflict and how it was resolved.",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-77"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/resolution-journal",
          index: 76,
        },
        {
          id: "uvls-kids-78",
          title: "Family Simulation",
          description: "Allocate chores/time fairly in a family setting.",
          icon: <Home className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-78"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/family-simulation",
          index: 77,
        },
        {
          id: "uvls-kids-79",
          title: "Identify Needs Reflex",
          description: "Recognize when someone expresses a need and respond.",
          icon: <HeartHandshake className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3–4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-79"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/identify-needs-reflex",
          index: 78,
        },
        {
          id: "uvls-kids-80",
          title: "Mediator Badge",
          description: "Reward consistent fair mediation actions.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-80"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mediator-badge",
          index: 79,
        },
        {
          id: "uvls-kids-81",
          title: "Clean-up Story",
          description: "Encourage participation in community clean-up.",
          icon: <Eraser className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-81"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/clean-up-story",
          index: 80,
        },
        {
          id: "uvls-kids-82",
          title: "Citizen Duties Quiz",
          description: "Identify simple civic duties.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-82"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/citizen-duties-quiz",
          index: 81,
        },
        {
          id: "uvls-kids-83",
          title: "Volunteer Reflex",
          description: "Tap to volunteer for visible needs quickly.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-83"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/volunteer-reflex",
          index: 82,
        },
        {
          id: "uvls-kids-84",
          title: "Community Roles Puzzle",
          description: "Match community helper to correct job.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-84"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/community-roles-puzzle",
          index: 83,
        },
        {
          id: "uvls-kids-85",
          title: "Fundraiser Story",
          description: "Plan simple fundraiser steps.",
          icon: <Coins className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-85"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/fundraiser-story",
          index: 84,
        },
        {
          id: "uvls-kids-86",
          title: "Civic Poster",
          description: "Create a 'Be a Good Citizen' poster.",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-86"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/civic-poster",
          index: 85,
        },
        {
          id: "uvls-kids-87",
          title: "Contribution Journal",
          description: "Record one small community service done.",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-87"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/contribution-journal",
          index: 86,
        },
        {
          id: "uvls-kids-88",
          title: "Help Elder Roleplay",
          description: "Practice polite help for an elderly neighbor.",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-88"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/help-elder-roleplay",
          index: 87,
        },
        {
          id: "uvls-kids-89",
          title: "Report Need Reflex",
          description: "Identify and flag community needs quickly.",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3–4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-89"] || false, 
          isSpecial: true,
          path: "/student/uvls/kids/report-need-reflex",
          index: 88,
        },
        {
          id: "uvls-kids-90",
          title: "Community Helper Badge",
          description: "Reward hands-on community contributions.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-90"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/community-helper-badge",
          index: 89,
        },
        {
          id: "uvls-kids-91",
          title: "Morning Routine",
          description: "Build a simple morning routine to be on time.",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-91"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/morning-routine",
          index: 90,
        },
        {
          id: "uvls-kids-92",
          title: "Priority Quiz",
          description: "Choose which tasks should come before play.",
          icon: <ListChecks className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4–5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-92"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/priority-quiz",
          index: 91,
        },
        {
          id: "uvls-kids-93",
          title: "Task Done Reflex",
          description: "Tap to check off completed daily routine items.",
          icon: <CheckSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-93"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/task-done-reflex",
          index: 92,
        },
        {
          id: "uvls-kids-94",
          title: "Plan Your Day Puzzle",
          description: "Order daily tasks into an effective plan.",
          icon: <Calendar className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-94"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/plan-your-day-puzzle",
          index: 93,
        },
        {
          id: "uvls-kids-95",
          title: "Goal Steps",
          description: "Break a big goal into smaller steps.",
          icon: <Flag className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-95"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/goal-steps",
          index: 94,
        },
        {
          id: "uvls-kids-96",
          title: "SMART Poster",
          description: "Learn simple SMART goal planning for kids.",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-96"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/smart-poster",
          index: 95,
        },
        {
          id: "uvls-kids-97",
          title: "Weekly Plan Journal",
          description: "Make a 3-point weekly plan (study, play, rest).",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-97"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/weekly-plan-journal",
          index: 96,
        },
        {
          id: "uvls-kids-98",
          title: "Time Budget Simulation",
          description: "Allocate time sensibly between study, fun, and rest.",
          icon: <Clock className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-98"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/time-budget-simulation",
          index: 97,
        },
        {
          id: "uvls-kids-99",
          title: "Safety Reflex",
          description: "Choose safe options quickly in everyday scenes.",
          icon: <ShieldCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2–3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-99"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/safety-reflexx",
          index: 98,
        },
        {
          id: "uvls-kids-100",
          title: "Life Skills Starter Badge",
          description: "Reward mastery of basic daily life skills.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-100"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/life-skills-starter-badge",
          index: 99,
        },
      ];

    return uvlsGamesKid;
}
