import {
  Trophy, 
  Timer, 
  Puzzle, 
  Users, 
  Calendar, 
  Lightbulb, 
  Zap,  
  Heart, 
  Shield, 
  Globe, 
  Target, 
  BookOpen, 
  GraduationCap, 
  HandHeart,  
  Eye, 
  MessageSquare,  
  RefreshCw,  
  Book, 
  HelpCircle,  
  FileText, 
  Mic, 
  AlertCircle, 
  MessageCircle, 
  PlayCircle, 
  Wind, 
  Scale, 
  CheckSquare, 
  Clock, 
  MonitorPlay, 
  Megaphone, 
  PenLine, 
  Theater, 
  ShieldAlert, 
  ClipboardCheck, 
  CheckCircle, 
  Briefcase, 
  ThumbsUp, 
  Edit3, 
  Handshake, 
  LogOut, 
  DollarSign, 
  Speech, 
  BarChart3, 
  Bell, 
  Siren, 
  Mail, 
  Link, 
  MapPin, 
} from "lucide-react";
import buildIds from "../buildGameIds";


export const uvlsGamesTeenIds = buildIds("uvls", "teen")

export const getUvlsTeenGames = (gameCompletionStatus)=> {
    const uvlsGamesTeen = [
        {
          id: "uvls-teen-1",
          title: "Listen Deep",
          description:
            "Respond supportively to a peer sharing a personal problem",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-1"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/listen-deep",
          index: 0,
        },
        {
          id: "uvls-teen-2",
          title: "Empathy Quiz",
          description: "Distinguish empathy vs sympathy in scenarios",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-2"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/empathy-quiz",
          index: 1,
        },
        {
          id: "uvls-teen-3",
          title: "Perspective Puzzle",
          description: "Map responses to how they help others",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-3"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/perspective-puzzle",
          index: 2,
        },
        {
          id: "uvls-teen-4",
          title: "Walk in Shoes Simulation",
          description: "Experience choices as a marginalized student",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-4"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/walk-in-shoes",
          index: 3,
        },
        {
          id: "uvls-teen-5",
          title: "Empathy Debate",
          description: "Argue for school empathy curriculum",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20-30 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-5"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/empathy-debate",
          index: 4,
        },
        {
          id: "uvls-teen-6",
          title: "Reflective Journal",
          description: "Write reflecting on understanding someone different",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-6"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/reflective-journal",
          index: 5,
        },
        {
          id: "uvls-teen-7",
          title: "Peer Support Roleplay",
          description: "Practice a peer-support conversation",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-7"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/peer-support-roleplay",
          index: 6,
        },
        {
          id: "uvls-teen-8",
          title: "Case-Response Puzzle",
          description: "Choose best empathetic responses in a multi-part case",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-8"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/case-response-puzzle",
          index: 7,
        },
        {
          id: "uvls-teen-9",
          title: "Spot Distress Reflex",
          description: "Rapidly detect subtle distress cues",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-9"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/spot-distress-reflex",
          index: 8,
        },
        {
          id: "uvls-teen-10",
          title: "Empathy Champion Badge",
          description: "Complete 5 teen empathy tasks",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "Cumulative",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-10"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/empathy-champion-badge",
          index: 9,
        },
        {
          id: "uvls-teen-11",
          title: "Cultural Greeting",
          description:
            "Choose respectful greeting for different cultural contexts",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-11"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/cultural-greeting",
          index: 10,
        },
        {
          id: "uvls-teen-12",
          title: "Inclusion Quiz",
          description: "Identify inclusive school actions/policies",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-12"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/inclusion-quiz",
          index: 11,
        },
        {
          id: "uvls-teen-13",
          title: "Accessibility Puzzle",
          description: "Match accommodations to student needs",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-13"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/accessibility-puzzle",
          index: 12,
        },
        {
          id: "uvls-teen-14",
          title: "Inclusive Class Simulation",
          description: "Design an activity that allows participation for all",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-14"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/inclusive-class-simulation",
          index: 13,
        },
        {
          id: "uvls-teen-15",
          title: "Respect Debate",
          description: "Debate whether respect equals agreement",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-15"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/respect-debate",
          index: 14,
        },
        {
          id: "uvls-teen-16",
          title: "Inclusion Journal",
          description: "Describe when you challenged exclusion & outcome",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-16"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/inclusion-journal",
          index: 15,
        },
        {
          id: "uvls-teen-17",
          title: "Correcting Bias Roleplay",
          description: "Practice calling out bias respectfully",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-17"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/correcting-bias-roleplay",
          index: 16,
        },
        {
          id: "uvls-teen-18",
          title: "Name Respect Reflex",
          description: "Identify correct pronunciation & respond respectfully",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-18"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/name-respect-reflex",
          index: 17,
        },
        {
          id: "uvls-teen-19",
          title: "Policy Case Puzzle",
          description: "Recommend inclusive policy actions for a school case",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-19"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/policy-case-puzzle",
          index: 18,
        },
        {
          id: "uvls-teen-20",
          title: "Respect Leader Badge",
          description: "Complete 5 inclusion leadership tasks",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-20"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/respect-leader-badge",
          index: 19,
        },
        {
          id: "uvls-teen-21",
          title: "Encourage Ambition",
          description:
            "Model supportive responses when peers state career ambitions.",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-21"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/encourage-ambition",
          index: 20,
        },
        {
          id: "uvls-teen-22",
          title: "Rights & Law Quiz",
          description: "Learn about gender equality laws and key policies.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-22"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/rights-law-quiz",
          index: 21,
        },
        {
          id: "uvls-teen-23",
          title: "Bias Spot Reflex",
          description: "Tap when biased remarks appear in short clips.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-23"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/bias-spot-reflex",
          index: 22,
        },
        {
          id: "uvls-teen-24",
          title: "Workplace Puzzle",
          description:
            "Identify biased practices and match effective remedies.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-24"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/workplace-puzzle",
          index: 23,
        },
        {
          id: "uvls-teen-25",
          title: "Program Design Simulation",
          description: "Draft a school program to increase girl participation.",
          icon: <MonitorPlay className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12–15 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-25"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/program-design-simulation",
          index: 24,
        },
        {
          id: "uvls-teen-26",
          title: "Equality Debate",
          description: "Debate policy vs culture in gender equality.",
          icon: <Megaphone className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-26"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/equality-debate",
          index: 25,
        },
        {
          id: "uvls-teen-27",
          title: "Ally Journal",
          description:
            "Plan a concrete ally action to support gender equality.",
          icon: <PenLine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-27"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/ally-journal",
          index: 26,
        },
        {
          id: "uvls-teen-28",
          title: "Intervention Roleplay",
          description: "Practice safely confronting discriminatory comments.",
          icon: <Theater className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-28"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/intervention-roleplay",
          index: 27,
        },
        {
          id: "uvls-teen-29",
          title: "Rights Application Puzzle",
          description: "Match legal steps to protect rights effectively.",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-29"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/rights-application-puzzle",
          index: 28,
        },
        {
          id: "uvls-teen-30",
          title: "Gender Justice Leader Badge",
          description: "Lead 5 equality initiatives to earn badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-30"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/gender-justice-leader-badge",
          index: 29,
        },
        {
          id: "uvls-teen-31",
          title: "Online Harass Scenario",
          description: "Choose safe responses to online harassment.",
          icon: <ShieldAlert className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-31"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/online-harass-scenario",
          index: 30,
        },
        {
          id: "uvls-teen-32",
          title: "Reporting Quiz",
          description: "Learn how to report bullying safely and correctly.",
          icon: <ClipboardCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-32"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/reporting-quiz",
          index: 31,
        },
        {
          id: "uvls-teen-33",
          title: "Support Network Puzzle",
          description: "Match support roles (teacher, parent) to actions.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-33"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/support-network-puzzle",
          index: 32,
        },
        {
          id: "uvls-teen-34",
          title: "Intervention Simulation",
          description: "Choose calm actions in a bully scenario simulation.",
          icon: <MonitorPlay className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-34"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/intervention-simulation",
          index: 33,
        },
        {
          id: "uvls-teen-35",
          title: "Rehab vs Punish Debate",
          description: "Argue best approach for dealing with bullies.",
          icon: <Megaphone className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-35"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/rehab-vs-punish-debate",
          index: 34,
        },
        {
          id: "uvls-teen-36",
          title: "Long-term Journal",
          description:
            "Create a step-by-step support plan for a bullied student.",
          icon: <PenLine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-36"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/long-term-journal",
          index: 35,
        },
        {
          id: "uvls-teen-37",
          title: "Counselor Roleplay",
          description: "Simulate a support conversation with a counselor.",
          icon: <Theater className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-37"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/counselor-roleplay",
          index: 36,
        },
        {
          id: "uvls-teen-38",
          title: "Cyber Safety Reflex",
          description: "Tap to report trolling or abusive online posts.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-38"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/cyber-safety-reflex",
          index: 37,
        },
        {
          id: "uvls-teen-39",
          title: "Systemic Case Puzzle",
          description: "Design a school-wide anti-bullying program.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12–15 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-39"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/systemic-case-puzzle",
          index: 38,
        },
        {
          id: "uvls-teen-40",
          title: "Anti-Bullying Champion Badge",
          description:
            "Complete 5 sustained anti-bullying actions to earn this badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-40"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/anti-bullying-champion-badge",
          index: 39,
        },
        {
          id: "uvls-teen-41",
          title: "Emotional Check-in",
          description:
            "Identify and label emotions accurately using emotion wheel.",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-41"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emotional-check-in",
          index: 40,
        },
        {
          id: "uvls-teen-42",
          title: "Trigger Quiz",
          description:
            "Recognize common personal and academic stress triggers.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-42"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/trigger-quiz",
          index: 41,
        },
        {
          id: "uvls-teen-43",
          title: "Advanced Breathing Simulation",
          description: "Practice guided breathing to regulate emotions.",
          icon: <Wind className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5–8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-43"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/advanced-breathing-sim",
          index: 42,
        },
        {
          id: "uvls-teen-44",
          title: "Coping Strategy Puzzle",
          description: "Match problem types to best coping strategies.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-44"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/coping-strategy-puzzle",
          index: 43,
        },
        {
          id: "uvls-teen-45",
          title: "De-escalation Roleplay",
          description: "Choose calm words to defuse heated arguments.",
          icon: <Theater className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-45"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/de-escalation-roleplay",
          index: 44,
        },
        {
          id: "uvls-teen-46",
          title: "Emotion Pattern Journal",
          description: "Track moods and reflect on patterns over a week.",
          icon: <PenLine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "15–20 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-46"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emotion-pattern-journal",
          index: 45,
        },
        {
          id: "uvls-teen-47",
          title: "Peer Support Simulation",
          description:
            "Plan a small group support session for a stressed peer.",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-47"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/peer-support-simulation",
          index: 46,
        },
        {
          id: "uvls-teen-48",
          title: "Self-check Reflex",
          description:
            "Tap when tension cues appear to practice self-awareness.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-48"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/self-check-reflex",
          index: 47,
        },
        {
          id: "uvls-teen-49",
          title: "Build Toolbox Puzzle",
          description: "Assemble your personalized emotion regulation toolbox.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-49"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/build-toolbox-puzzle",
          index: 48,
        },
        {
          id: "uvls-teen-50",
          title: "Emotional Responder Badge",
          description:
            "Demonstrate 5 emotion regulation strategies to earn badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-50"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emotional-responder-badge",
          index: 49,
        },
        {
          id: "uvls-teen-51",
          title: "Evidence Check",
          description: "Evaluate a short claim using quick evidence checks.",
          icon: <CheckCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-51"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/evidence-check",
          index: 50,
        },
        {
          id: "uvls-teen-52",
          title: "Fake News Quiz",
          description: "Spot false headlines and explain why.",
          icon: <AlertCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-52"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/fake-news-quiz",
          index: 51,
        },
        {
          id: "uvls-teen-53",
          title: "Trade-offs Puzzle",
          description: "Compare pros/cons and pick best compromise.",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-53"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/trade-offs-puzzle",
          index: 52,
        },
        {
          id: "uvls-teen-54",
          title: "Scenario Simulation",
          description: "Run simulated outcomes of different choices.",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-54"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/scenario-simulation",
          index: 53,
        },
        {
          id: "uvls-teen-55",
          title: "Ethical Roleplay",
          description:
            "Negotiate honest vs convenient shortcut & justify choice.",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8–10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-55"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/ethical-roleplay",
          index: 54,
        },
        {
          id: "uvls-teen-56",
          title: "Bias Detection Reflex",
          description: "Rapidly detect biased statements.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-56"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/bias-detection-reflex",
          index: 55,
        },
        {
          id: "uvls-teen-57",
          title: "Evidence Journal",
          description: "Record evidence used in a recent personal decision.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-57"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/evidence-journal",
          index: 56,
        },
        {
          id: "uvls-teen-58",
          title: "Timed Debate",
          description: "Prepare and defend a stance in 60 seconds.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10–15 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-58"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/timed-debate",
          index: 57,
        },
        {
          id: "uvls-teen-59",
          title: "Policy Puzzle",
          description: "Suggest practical improvements to a school policy.",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-59"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/policy-puzzle",
          index: 58,
        },
        {
          id: "uvls-teen-60",
          title: "Decision Master Badge",
          description:
            "Complete 5 evidence-based decision tasks to earn badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-60"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/decision-master-badge",
          index: 59,
        },
        {
          id: "uvls-teen-61",
          title: "Tough Conversation",
          description: "Choose tone & phrasing for an honest talk with friend.",
          icon: <MessageCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-61"] || false, 
          isSpecial: true,
          path: "/student/uvls/teen/tough-conversation",
          index: 60,
        },
        {
          id: "uvls-teen-62",
          title: "Nonverbal Quiz",
          description: "Match body language cues with intent.",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-62"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/nonverbal-quiz",
          index: 61,
        },
        {
          id: "uvls-teen-63",
          title: "Clarify Reflex",
          description: "Spot when a speaker needs clarification and prompt.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-63"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/clarify-reflex",
          index: 62,
        },
        {
          id: "uvls-teen-64",
          title: "Interview Simulation",
          description: "Practice answers to common interview questions.",
          icon: <Briefcase className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-64"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/interview-simulation",
          index: 63,
        },
        {
          id: "uvls-teen-65",
          title: "Feedback Roleplay",
          description: "Give constructive feedback in a roleplay.",
          icon: <ThumbsUp className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8–10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-65"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/feedback-roleplay",
          index: 64,
        },
        {
          id: "uvls-teen-66",
          title: "Persuasion Puzzle",
          description: "Build a short persuasive sequence.",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-66"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/persuasion-puzzle",
          index: 65,
        },
        {
          id: "uvls-teen-67",
          title: "Communication Journal",
          description: "Set a communication improvement goal and action plan.",
          icon: <Edit3 className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-67"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/communication-journal",
          index: 66,
        },
        {
          id: "uvls-teen-68",
          title: "Public Speaking Prep",
          description: "Draft a 60-second opening & get feedback.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-68"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/public-speaking-prep",
          index: 67,
        },
        {
          id: "uvls-teen-69",
          title: "Listening vs Speaking Debate",
          description: "Argue which is more important for leadership.",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-69"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/listening-vs-speaking-debate",
          index: 68,
        },
        {
          id: "uvls-teen-70",
          title: "Communication Pro Badge",
          description: "Completion of 5 advanced communication tasks.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-70"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/communication-pro-badge",
          index: 69,
        },
        {
          id: "uvls-teen-71",
          title: "Power Dynamics Scenario",
          description: "Resolve a conflict where one party has more authority.",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-71"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/power-dynamics-scenario",
          index: 70,
        },
        {
          id: "uvls-teen-72",
          title: "Negotiation Tactics Quiz",
          description: "Identify tactics like anchoring, trade-offs.",
          icon: <CheckSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-72"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/negotiation-tactics-quiz",
          index: 71,
        },
        {
          id: "uvls-teen-73",
          title: "Mediation Simulation",
          description: "Facilitate a council dispute to consensus.",
          icon: <Handshake className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12–15 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-73"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/mediation-simulation",
          index: 72,
        },
        {
          id: "uvls-teen-74",
          title: "BATNA Puzzle",
          description: "Identify the Best Alternative to Negotiated Agreement.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6–8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-74"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/batna-puzzle",
          index: 73,
        },
        {
          id: "uvls-teen-75",
          title: "Tough Bargain Roleplay",
          description: "Negotiate resources with limited supply fairly.",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10–12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-75"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/tough-bargain-roleplay",
          index: 74,
        },
        {
          id: "uvls-teen-76",
          title: "Ethics in Negotiation Debate",
          description: "Debate when compromise becomes unethical.",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-76"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/ethics-in-negotiation-debate",
          index: 75,
        },
        {
          id: "uvls-teen-77",
          title: "Negotiation Journal",
          description: "Reflect on a negotiation you led and lessons learned.",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-77"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/negotiation-journal",
          index: 76,
        },
        {
          id: "uvls-teen-78",
          title: "Walk-away Reflex",
          description:
            "Rapidly spot situations where walking away is justified.",
          icon: <LogOut className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-78"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/walk-away-reflex",
          index: 77,
        },
        {
          id: "uvls-teen-79",
          title: "Workplace Conflict Sim",
          description:
            "Resolve intern-team conflict with fair role assignments.",
          icon: <Briefcase className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12–15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-79"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/workplace-conflict-sim",
          index: 78,
        },
        {
          id: "uvls-teen-80",
          title: "Conflict Solver Badge",
          description: "Demonstrate multi-step resolutions in 5 cases.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-80"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/conflict-solver-badge",
          index: 79,
        },
        {
          id: "uvls-teen-81",
          title: "Campaign Story",
          description: "Plan an awareness campaign for a local issue.",
          icon: <Megaphone className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12–15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-81"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/campaign-story",
          index: 80,
        },
        {
          id: "uvls-teen-82",
          title: "SDG Quiz",
          description: "Match local projects to relevant UN SDGs.",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-82"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/sdg-quiz",
          index: 81,
        },
        {
          id: "uvls-teen-83",
          title: "Volunteer Simulation",
          description: "Run a volunteer event schedule (logistics).",
          icon: <Calendar className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-83"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/volunteer-simulation",
          index: 82,
        },
        {
          id: "uvls-teen-84",
          title: "Public Budget Puzzle",
          description: "Allocate limited budget to competing school needs.",
          icon: <DollarSign className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-84"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/public-budget-puzzle",
          index: 83,
        },
        {
          id: "uvls-teen-85",
          title: "Advocacy Roleplay",
          description: "Argue before local council for safer crossing.",
          icon: <Speech className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10–12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-85"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/advocacy-roleplay",
          index: 84,
        },
        {
          id: "uvls-teen-86",
          title: "Impact Journal",
          description: "Record measurable outcome of a community action.",
          icon: <BarChart3 className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-86"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/impact-journal",
          index: 85,
        },
        {
          id: "uvls-teen-87",
          title: "Service Design Puzzle",
          description: "Design a low-cost service project for school.",
          icon: <Lightbulb className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-87"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/service-design-puzzle",
          index: 86,
        },
        {
          id: "uvls-teen-88",
          title: "Coalition Simulation",
          description: "Form coalition of stakeholders for larger change.",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-88"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/coalition-simulation",
          index: 87,
        },
        {
          id: "uvls-teen-89",
          title: "Civic Reflex",
          description: "Quickly flag urgent community needs in short prompts.",
          icon: <Bell className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4–6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-89"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/civic-reflex",
          index: 88,
        },
        {
          id: "uvls-teen-90",
          title: "Citizen Leader Badge",
          description: "Lead a small community initiative to completion.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-90"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/citizen-leader-badge",
          index: 89,
        },
        {
          id: "uvls-teen-91",
          title: "Short vs Long Goals Debate",
          description:
            "Discuss priorities between short-term wins & long-term planning.",
          icon: <Clock className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-91"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/short-vs-long-goals-debate",
          index: 90,
        },
        {
          id: "uvls-teen-92",
          title: "Emergency Steps Quiz",
          description: "Match emergencies to correct immediate actions.",
          icon: <Siren className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-92"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emergency-steps-quiz",
          index: 91,
        },
        {
          id: "uvls-teen-93",
          title: "One-year Plan Journal",
          description: "Write a 1-year learning goal and milestones.",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-93"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/one-year-plan-journal",
          index: 92,
        },
        {
          id: "uvls-teen-94",
          title: "Crisis Simulation",
          description:
            "Prioritise night-before-exam tasks to maximize study + sleep.",
          icon: <Timer className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-94"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/crisis-simulation",
          index: 93,
        },
        {
          id: "uvls-teen-95",
          title: "Request Extension Roleplay",
          description: "Request an extension politely with reasons & plan.",
          icon: <Mail className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8–10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-95"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/request-extension-roleplay",
          index: 94,
        },
        {
          id: "uvls-teen-96",
          title: "Safety Offer Reflex",
          description: "Rapidly refuse suspicious offers.",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3–5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-96"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/safety-offer-reflex",
          index: 95,
        },
        {
          id: "uvls-teen-97",
          title: "Habit Chain Puzzle",
          description:
            "Link small daily habits into a chain to produce big outcomes.",
          icon: <Link className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8–10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-97"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/habit-chain-puzzle",
          index: 96,
        },
        {
          id: "uvls-teen-98",
          title: "Habit Change Journal",
          description: "Describe one habit to change, plan steps & obstacles.",
          icon: <RefreshCw className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10–12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-98"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/habit-change-journal",
          index: 97,
        },
        {
          id: "uvls-teen-99",
          title: "Solo Trip Simulation",
      description: "Plan a safe solo trip checklist.",
          icon: <MapPin className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12–15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-99"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/solo-trip-simulation",
          index: 98,
        },
        {
          id: "uvls-teen-100",
          title: "Life Skills Champion Badge",
          description:
            "Demonstrate 5 advanced life-skill challenges & receive capstone badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-100"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/life-skills-champion-badge",
          index: 99,
        },
      ];

    return uvlsGamesTeen;
}
